//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.DataAccess.SearchProvider.Enum
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Data;
    using System.Threading;
    using System.Diagnostics;
    using System.Data.SqlClient;
    using System.Data.OleDb;
    using System.Data.Odbc;
    using System.Collections;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    
    
    #region EnumDataStoreTableName Enum Type
    /// <summary>
    /// The enumerator enumdatastoretablename object.
    /// </summary>
    [SerializableAttribute()]
    [DataContractAttribute()]
    public enum EnumDataStoreTableName
    {
        
        /// <summary>
        /// The A enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        A = 1,
        
        /// <summary>
        /// The B enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        B = 2,
        
        /// <summary>
        /// The C enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        C = 3,
        
        /// <summary>
        /// The D enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        D = 4,
        
        /// <summary>
        /// The E enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        E = 5,
        
        /// <summary>
        /// The F enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        F = 6,
        
        /// <summary>
        /// The G enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        G = 7,
        
        /// <summary>
        /// The H enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        H = 8,
        
        /// <summary>
        /// The I enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        I = 9,
        
        /// <summary>
        /// The J enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        J = 10,
        
        /// <summary>
        /// The K enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        K = 11,
        
        /// <summary>
        /// The L enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        L = 12,
        
        /// <summary>
        /// The M enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        M = 13,
        
        /// <summary>
        /// The N enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        N = 14,
        
        /// <summary>
        /// The O enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        O = 15,
        
        /// <summary>
        /// The P enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        P = 16,
        
        /// <summary>
        /// The Q enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Q = 17,
        
        /// <summary>
        /// The R enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        R = 18,
        
        /// <summary>
        /// The S enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        S = 19,
        
        /// <summary>
        /// The T enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        T = 20,
        
        /// <summary>
        /// The U enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        U = 21,
        
        /// <summary>
        /// The V enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        V = 22,
        
        /// <summary>
        /// The W enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        W = 23,
        
        /// <summary>
        /// The X enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        X = 24,
        
        /// <summary>
        /// The Y enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Y = 25,
        
        /// <summary>
        /// The Z enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Z = 26,
        
        /// <summary>
        /// The Number enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Number = 27,
        
        /// <summary>
        /// The Phrase enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Phrase = 28,
        
        /// <summary>
        /// The Special enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Special = 29,
    }
    #endregion
}
