/*  Company :       Nequeo Pty Ltd, http://www.nequeo.com.au/
 *  Copyright :     Copyright © Nequeo Pty Ltd 2015 http://www.nequeo.com.au/
 * 
 *  File :          
 *  Purpose :       
 * 
 */

#region Nequeo Pty Ltd License
/*
    Permission is hereby granted, free of charge, to any person
    obtaining a copy of this software and associated documentation
    files (the "Software"), to deal in the Software without
    restriction, including without limitation the rights to use,
    copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following
    conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
    OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
    WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
    OTHER DEALINGS IN THE SOFTWARE.
*/
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using NHunspell;

namespace Nequeo.Spelling
{
    /// <summary>
    /// Holds the result of a thesaurus synonym lookup.
    /// </summary>
    public class ThesaurusResult
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThesaurusResult"/> class.
        /// </summary>
        /// <param name="meanings">
        /// The meanings. 
        /// </param>
        /// <param name="generatedByStem">
        /// if set to <c>true</c> , the meanings are generated by word stemming. 
        /// </param>
        public ThesaurusResult(List<ThesaurusMeaning> meanings, bool generatedByStem)
        {
            _meanings = meanings;
            _generatedByStem = generatedByStem;
        }

        /// <summary>
        ///   The generated by stem.
        /// </summary>
        private readonly bool _generatedByStem;

        /// <summary>
        ///   The meanings.
        /// </summary>
        private readonly List<ThesaurusMeaning> _meanings;

        /// <summary>
        /// Gets a value indicating whether the meanings are generated by word stemming.
        /// </summary>
        /// <value> <c>true</c> if the meanings are generated by word stemming; otherwise, <c>false</c> . </value>
        public bool IsGenerated
        {
            get
            {
                return _generatedByStem;
            }
        }

        /// <summary>
        /// Gets the meanings.
        /// </summary>
        /// <value> The meanings. </value>
        public List<ThesaurusMeaning> Meanings
        {
            get
            {
                return _meanings;
            }
        }
    }
}
