// This source file is part of OpenGL Code Samples
// For the latest info, see http://es.g0dsoft.com/
// Copyright (c) 2010 Michal Ziulek
// This source is under MIT License

#include "OpenGL.hpp"
#include "SDL.h"
#include <stdexcept>
#include <string>
#include <sstream>
using namespace std;

//PFNGLCULLFACEPROC glCullFace;
//PFNGLFRONTFACEPROC glFrontFace;
//PFNGLHINTPROC glHint;
//PFNGLLINEWIDTHPROC glLineWidth;
//PFNGLPOINTSIZEPROC glPointSize;
//PFNGLPOLYGONMODEPROC glPolygonMode;
//PFNGLSCISSORPROC glScissor;
//PFNGLTEXPARAMETERFPROC glTexParameterf;
//PFNGLTEXPARAMETERFVPROC glTexParameterfv;
//PFNGLTEXPARAMETERIPROC glTexParameteri;
//PFNGLTEXPARAMETERIVPROC glTexParameteriv;
//PFNGLTEXIMAGE1DPROC glTexImage1D;
//PFNGLTEXIMAGE2DPROC glTexImage2D;
//PFNGLDRAWBUFFERPROC glDrawBuffer;
//PFNGLCLEARPROC glClear;
//PFNGLCLEARCOLORPROC glClearColor;
//PFNGLCLEARSTENCILPROC glClearStencil;
//PFNGLCLEARDEPTHPROC glClearDepth;
//PFNGLSTENCILMASKPROC glStencilMask;
//PFNGLCOLORMASKPROC glColorMask;
//PFNGLDEPTHMASKPROC glDepthMask;
//PFNGLDISABLEPROC glDisable;
//PFNGLENABLEPROC glEnable;
//PFNGLFINISHPROC glFinish;
//PFNGLFLUSHPROC glFlush;
//PFNGLBLENDFUNCPROC glBlendFunc;
//PFNGLLOGICOPPROC glLogicOp;
//PFNGLSTENCILFUNCPROC glStencilFunc;
//PFNGLSTENCILOPPROC glStencilOp;
//PFNGLDEPTHFUNCPROC glDepthFunc;
//PFNGLPIXELSTOREFPROC glPixelStoref;
//PFNGLPIXELSTOREIPROC glPixelStorei;
//PFNGLREADBUFFERPROC glReadBuffer;
//PFNGLREADPIXELSPROC glReadPixels;
//PFNGLGETBOOLEANVPROC glGetBooleanv;
//PFNGLGETDOUBLEVPROC glGetDoublev;
//PFNGLGETERRORPROC glGetError;
//PFNGLGETFLOATVPROC glGetFloatv;
//PFNGLGETINTEGERVPROC glGetIntegerv;
//PFNGLGETSTRINGPROC glGetString;
//PFNGLGETTEXIMAGEPROC glGetTexImage;
//PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv;
//PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv;
//PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv;
//PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv;
//PFNGLISENABLEDPROC glIsEnabled;
//PFNGLDEPTHRANGEPROC glDepthRange;
//PFNGLVIEWPORTPROC glViewport;
//PFNGLDRAWARRAYSPROC glDrawArrays;
//PFNGLDRAWELEMENTSPROC glDrawElements;
//PFNGLGETPOINTERVPROC glGetPointerv;
//PFNGLPOLYGONOFFSETPROC glPolygonOffset;
//PFNGLCOPYTEXIMAGE1DPROC glCopyTexImage1D;
//PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D;
//PFNGLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D;
//PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D;
//PFNGLTEXSUBIMAGE1DPROC glTexSubImage1D;
//PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D;
//PFNGLBINDTEXTUREPROC glBindTexture;
//PFNGLDELETETEXTURESPROC glDeleteTextures;
//PFNGLGENTEXTURESPROC glGenTextures;
//PFNGLISTEXTUREPROC glIsTexture;
PFNGLBLENDCOLORPROC glBlendColor;
PFNGLBLENDEQUATIONPROC glBlendEquation;
PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements;
PFNGLTEXIMAGE3DPROC glTexImage3D;
PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D;
PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D;
PFNGLACTIVETEXTUREPROC glActiveTexture;
PFNGLSAMPLECOVERAGEPROC glSampleCoverage;
PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D;
PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;
PFNGLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D;
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D;
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D;
PFNGLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage;
PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;
PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays;
PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements;
PFNGLPOINTPARAMETERFPROC glPointParameterf;
PFNGLPOINTPARAMETERFVPROC glPointParameterfv;
PFNGLPOINTPARAMETERIPROC glPointParameteri;
PFNGLPOINTPARAMETERIVPROC glPointParameteriv;
PFNGLGENQUERIESPROC glGenQueries;
PFNGLDELETEQUERIESPROC glDeleteQueries;
PFNGLISQUERYPROC glIsQuery;
PFNGLBEGINQUERYPROC glBeginQuery;
PFNGLENDQUERYPROC glEndQuery;
PFNGLGETQUERYIVPROC glGetQueryiv;
PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv;
PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv;
PFNGLBINDBUFFERPROC glBindBuffer;
PFNGLDELETEBUFFERSPROC glDeleteBuffers;
PFNGLGENBUFFERSPROC glGenBuffers;
PFNGLISBUFFERPROC glIsBuffer;
PFNGLBUFFERDATAPROC glBufferData;
PFNGLBUFFERSUBDATAPROC glBufferSubData;
PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData;
PFNGLMAPBUFFERPROC glMapBuffer;
PFNGLUNMAPBUFFERPROC glUnmapBuffer;
PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;
PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv;
PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;
PFNGLDRAWBUFFERSPROC glDrawBuffers;
PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate;
PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate;
PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate;
PFNGLATTACHSHADERPROC glAttachShader;
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
PFNGLCOMPILESHADERPROC glCompileShader;
PFNGLCREATEPROGRAMPROC glCreateProgram;
PFNGLCREATESHADERPROC glCreateShader;
PFNGLDELETEPROGRAMPROC glDeleteProgram;
PFNGLDELETESHADERPROC glDeleteShader;
PFNGLDETACHSHADERPROC glDetachShader;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib;
PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform;
PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;
PFNGLGETPROGRAMIVPROC glGetProgramiv;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
PFNGLGETSHADERIVPROC glGetShaderiv;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
PFNGLGETSHADERSOURCEPROC glGetShaderSource;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
PFNGLGETUNIFORMFVPROC glGetUniformfv;
PFNGLGETUNIFORMIVPROC glGetUniformiv;
PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv;
PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv;
PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv;
PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv;
PFNGLISPROGRAMPROC glIsProgram;
PFNGLISSHADERPROC glIsShader;
PFNGLLINKPROGRAMPROC glLinkProgram;
PFNGLSHADERSOURCEPROC glShaderSource;
PFNGLUSEPROGRAMPROC glUseProgram;
PFNGLUNIFORM1FPROC glUniform1f;
PFNGLUNIFORM2FPROC glUniform2f;
PFNGLUNIFORM3FPROC glUniform3f;
PFNGLUNIFORM4FPROC glUniform4f;
PFNGLUNIFORM1IPROC glUniform1i;
PFNGLUNIFORM2IPROC glUniform2i;
PFNGLUNIFORM3IPROC glUniform3i;
PFNGLUNIFORM4IPROC glUniform4i;
PFNGLUNIFORM1FVPROC glUniform1fv;
PFNGLUNIFORM2FVPROC glUniform2fv;
PFNGLUNIFORM3FVPROC glUniform3fv;
PFNGLUNIFORM4FVPROC glUniform4fv;
PFNGLUNIFORM1IVPROC glUniform1iv;
PFNGLUNIFORM2IVPROC glUniform2iv;
PFNGLUNIFORM3IVPROC glUniform3iv;
PFNGLUNIFORM4IVPROC glUniform4iv;
PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
PFNGLVALIDATEPROGRAMPROC glValidateProgram;
PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d;
PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv;
PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f;
PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv;
PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s;
PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv;
PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d;
PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv;
PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f;
PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv;
PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s;
PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv;
PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d;
PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv;
PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f;
PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv;
PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s;
PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv;
PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv;
PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv;
PFNGLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv;
PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub;
PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv;
PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv;
PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv;
PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv;
PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d;
PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv;
PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f;
PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv;
PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv;
PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s;
PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv;
PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv;
PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv;
PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv;
PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv;
PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv;
PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv;
PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv;
PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv;
PFNGLCOLORMASKIPROC glColorMaski;
PFNGLGETBOOLEANI_VPROC glGetBooleani_v;
PFNGLGETINTEGERI_VPROC glGetIntegeri_v;
PFNGLENABLEIPROC glEnablei;
PFNGLDISABLEIPROC glDisablei;
PFNGLISENABLEDIPROC glIsEnabledi;
PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback;
PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback;
PFNGLBINDBUFFERRANGEPROC glBindBufferRange;
PFNGLBINDBUFFERBASEPROC glBindBufferBase;
PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings;
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying;
PFNGLCLAMPCOLORPROC glClampColor;
PFNGLBEGINCONDITIONALRENDERPROC glBeginConditionalRender;
PFNGLENDCONDITIONALRENDERPROC glEndConditionalRender;
PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer;
PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv;
PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv;
PFNGLVERTEXATTRIBI1IPROC glVertexAttribI1i;
PFNGLVERTEXATTRIBI2IPROC glVertexAttribI2i;
PFNGLVERTEXATTRIBI3IPROC glVertexAttribI3i;
PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i;
PFNGLVERTEXATTRIBI1UIPROC glVertexAttribI1ui;
PFNGLVERTEXATTRIBI2UIPROC glVertexAttribI2ui;
PFNGLVERTEXATTRIBI3UIPROC glVertexAttribI3ui;
PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui;
PFNGLVERTEXATTRIBI1IVPROC glVertexAttribI1iv;
PFNGLVERTEXATTRIBI2IVPROC glVertexAttribI2iv;
PFNGLVERTEXATTRIBI3IVPROC glVertexAttribI3iv;
PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv;
PFNGLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv;
PFNGLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv;
PFNGLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv;
PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv;
PFNGLVERTEXATTRIBI4BVPROC glVertexAttribI4bv;
PFNGLVERTEXATTRIBI4SVPROC glVertexAttribI4sv;
PFNGLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv;
PFNGLVERTEXATTRIBI4USVPROC glVertexAttribI4usv;
PFNGLGETUNIFORMUIVPROC glGetUniformuiv;
PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation;
PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation;
PFNGLUNIFORM1UIPROC glUniform1ui;
PFNGLUNIFORM2UIPROC glUniform2ui;
PFNGLUNIFORM3UIPROC glUniform3ui;
PFNGLUNIFORM4UIPROC glUniform4ui;
PFNGLUNIFORM1UIVPROC glUniform1uiv;
PFNGLUNIFORM2UIVPROC glUniform2uiv;
PFNGLUNIFORM3UIVPROC glUniform3uiv;
PFNGLUNIFORM4UIVPROC glUniform4uiv;
PFNGLTEXPARAMETERIIVPROC glTexParameterIiv;
PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv;
PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv;
PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv;
PFNGLCLEARBUFFERIVPROC glClearBufferiv;
PFNGLCLEARBUFFERUIVPROC glClearBufferuiv;
PFNGLCLEARBUFFERFVPROC glClearBufferfv;
PFNGLCLEARBUFFERFIPROC glClearBufferfi;
PFNGLGETSTRINGIPROC glGetStringi;
PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;
PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;
PFNGLTEXBUFFERPROC glTexBuffer;
PFNGLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex;
PFNGLGETINTEGER64I_VPROC glGetInteger64i_v;
PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v;
PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture;
//PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor;
PFNGLMINSAMPLESHADINGPROC glMinSampleShading;
PFNGLBLENDEQUATIONIPROC glBlendEquationi;
PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei;
PFNGLBLENDFUNCIPROC glBlendFunci;
PFNGLBLENDFUNCSEPARATEIPROC glBlendFuncSeparatei;
PFNGLISRENDERBUFFERPROC glIsRenderbuffer;
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv;
PFNGLISFRAMEBUFFERPROC glIsFramebuffer;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
PFNGLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
PFNGLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv;
PFNGLGENERATEMIPMAPPROC glGenerateMipmap;
PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample;
PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer;
PFNGLMAPBUFFERRANGEPROC glMapBufferRange;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
PFNGLISVERTEXARRAYPROC glIsVertexArray;
PFNGLGETUNIFORMINDICESPROC glGetUniformIndices;
PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv;
PFNGLGETACTIVEUNIFORMNAMEPROC glGetActiveUniformName;
PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv;
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName;
PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding;
PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData;
PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex;
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex;
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex;
PFNGLPROVOKINGVERTEXPROC glProvokingVertex;
PFNGLFENCESYNCPROC glFenceSync;
PFNGLISSYNCPROC glIsSync;
PFNGLDELETESYNCPROC glDeleteSync;
PFNGLCLIENTWAITSYNCPROC glClientWaitSync;
PFNGLWAITSYNCPROC glWaitSync;
PFNGLGETINTEGER64VPROC glGetInteger64v;
PFNGLGETSYNCIVPROC glGetSynciv;
PFNGLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample;
PFNGLTEXIMAGE3DMULTISAMPLEPROC glTexImage3DMultisample;
PFNGLGETMULTISAMPLEFVPROC glGetMultisamplefv;
PFNGLSAMPLEMASKIPROC glSampleMaski;
PFNGLBLENDEQUATIONIARBPROC glBlendEquationiARB;
PFNGLBLENDEQUATIONSEPARATEIARBPROC glBlendEquationSeparateiARB;
PFNGLBLENDFUNCIARBPROC glBlendFunciARB;
PFNGLBLENDFUNCSEPARATEIARBPROC glBlendFuncSeparateiARB;
PFNGLMINSAMPLESHADINGARBPROC glMinSampleShadingARB;
PFNGLNAMEDSTRINGARBPROC glNamedStringARB;
PFNGLDELETENAMEDSTRINGARBPROC glDeleteNamedStringARB;
PFNGLCOMPILESHADERINCLUDEARBPROC glCompileShaderIncludeARB;
PFNGLISNAMEDSTRINGARBPROC glIsNamedStringARB;
PFNGLGETNAMEDSTRINGARBPROC glGetNamedStringARB;
PFNGLGETNAMEDSTRINGIVARBPROC glGetNamedStringivARB;
PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed;
PFNGLGETFRAGDATAINDEXPROC glGetFragDataIndex;
PFNGLGENSAMPLERSPROC glGenSamplers;
PFNGLDELETESAMPLERSPROC glDeleteSamplers;
PFNGLISSAMPLERPROC glIsSampler;
PFNGLBINDSAMPLERPROC glBindSampler;
//PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri;
//PFNGLSAMPLERPARAMETERIVPROC glSamplerParameteriv;
//PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf;
//PFNGLSAMPLERPARAMETERFVPROC glSamplerParameterfv;
//PFNGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv;
//PFNGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv;
//PFNGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv;
//PFNGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv;
//PFNGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv;
//PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv;
PFNGLQUERYCOUNTERPROC glQueryCounter;
PFNGLGETQUERYOBJECTI64VPROC glGetQueryObjecti64v;
PFNGLGETQUERYOBJECTUI64VPROC glGetQueryObjectui64v;
PFNGLVERTEXP2UIPROC glVertexP2ui;
PFNGLVERTEXP2UIVPROC glVertexP2uiv;
PFNGLVERTEXP3UIPROC glVertexP3ui;
PFNGLVERTEXP3UIVPROC glVertexP3uiv;
PFNGLVERTEXP4UIPROC glVertexP4ui;
PFNGLVERTEXP4UIVPROC glVertexP4uiv;
PFNGLTEXCOORDP1UIPROC glTexCoordP1ui;
PFNGLTEXCOORDP1UIVPROC glTexCoordP1uiv;
PFNGLTEXCOORDP2UIPROC glTexCoordP2ui;
PFNGLTEXCOORDP2UIVPROC glTexCoordP2uiv;
PFNGLTEXCOORDP3UIPROC glTexCoordP3ui;
PFNGLTEXCOORDP3UIVPROC glTexCoordP3uiv;
PFNGLTEXCOORDP4UIPROC glTexCoordP4ui;
PFNGLTEXCOORDP4UIVPROC glTexCoordP4uiv;
PFNGLMULTITEXCOORDP1UIPROC glMultiTexCoordP1ui;
PFNGLMULTITEXCOORDP1UIVPROC glMultiTexCoordP1uiv;
PFNGLMULTITEXCOORDP2UIPROC glMultiTexCoordP2ui;
PFNGLMULTITEXCOORDP2UIVPROC glMultiTexCoordP2uiv;
PFNGLMULTITEXCOORDP3UIPROC glMultiTexCoordP3ui;
PFNGLMULTITEXCOORDP3UIVPROC glMultiTexCoordP3uiv;
PFNGLMULTITEXCOORDP4UIPROC glMultiTexCoordP4ui;
PFNGLMULTITEXCOORDP4UIVPROC glMultiTexCoordP4uiv;
PFNGLNORMALP3UIPROC glNormalP3ui;
PFNGLNORMALP3UIVPROC glNormalP3uiv;
PFNGLCOLORP3UIPROC glColorP3ui;
PFNGLCOLORP3UIVPROC glColorP3uiv;
PFNGLCOLORP4UIPROC glColorP4ui;
PFNGLCOLORP4UIVPROC glColorP4uiv;
PFNGLSECONDARYCOLORP3UIPROC glSecondaryColorP3ui;
PFNGLSECONDARYCOLORP3UIVPROC glSecondaryColorP3uiv;
PFNGLVERTEXATTRIBP1UIPROC glVertexAttribP1ui;
PFNGLVERTEXATTRIBP1UIVPROC glVertexAttribP1uiv;
PFNGLVERTEXATTRIBP2UIPROC glVertexAttribP2ui;
PFNGLVERTEXATTRIBP2UIVPROC glVertexAttribP2uiv;
PFNGLVERTEXATTRIBP3UIPROC glVertexAttribP3ui;
PFNGLVERTEXATTRIBP3UIVPROC glVertexAttribP3uiv;
PFNGLVERTEXATTRIBP4UIPROC glVertexAttribP4ui;
PFNGLVERTEXATTRIBP4UIVPROC glVertexAttribP4uiv;
PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect;
PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect;
//PFNGLUNIFORM1DPROC glUniform1d;
//PFNGLUNIFORM2DPROC glUniform2d;
//PFNGLUNIFORM3DPROC glUniform3d;
//PFNGLUNIFORM4DPROC glUniform4d;
//PFNGLUNIFORM1DVPROC glUniform1dv;
//PFNGLUNIFORM2DVPROC glUniform2dv;
//PFNGLUNIFORM3DVPROC glUniform3dv;
//PFNGLUNIFORM4DVPROC glUniform4dv;
//PFNGLUNIFORMMATRIX2DVPROC glUniformMatrix2dv;
//PFNGLUNIFORMMATRIX3DVPROC glUniformMatrix3dv;
//PFNGLUNIFORMMATRIX4DVPROC glUniformMatrix4dv;
//PFNGLUNIFORMMATRIX2X3DVPROC glUniformMatrix2x3dv;
//PFNGLUNIFORMMATRIX2X4DVPROC glUniformMatrix2x4dv;
//PFNGLUNIFORMMATRIX3X2DVPROC glUniformMatrix3x2dv;
//PFNGLUNIFORMMATRIX3X4DVPROC glUniformMatrix3x4dv;
//PFNGLUNIFORMMATRIX4X2DVPROC glUniformMatrix4x2dv;
//PFNGLUNIFORMMATRIX4X3DVPROC glUniformMatrix4x3dv;
//PFNGLGETUNIFORMDVPROC glGetUniformdv;
PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC glGetSubroutineUniformLocation;
PFNGLGETSUBROUTINEINDEXPROC glGetSubroutineIndex;
PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC glGetActiveSubroutineUniformiv;
PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC glGetActiveSubroutineUniformName;
PFNGLGETACTIVESUBROUTINENAMEPROC glGetActiveSubroutineName;
PFNGLUNIFORMSUBROUTINESUIVPROC glUniformSubroutinesuiv;
PFNGLGETUNIFORMSUBROUTINEUIVPROC glGetUniformSubroutineuiv;
PFNGLGETPROGRAMSTAGEIVPROC glGetProgramStageiv;
PFNGLPATCHPARAMETERIPROC glPatchParameteri;
PFNGLPATCHPARAMETERFVPROC glPatchParameterfv;
PFNGLBINDTRANSFORMFEEDBACKPROC glBindTransformFeedback;
PFNGLDELETETRANSFORMFEEDBACKSPROC glDeleteTransformFeedbacks;
PFNGLGENTRANSFORMFEEDBACKSPROC glGenTransformFeedbacks;
PFNGLISTRANSFORMFEEDBACKPROC glIsTransformFeedback;
PFNGLPAUSETRANSFORMFEEDBACKPROC glPauseTransformFeedback;
PFNGLRESUMETRANSFORMFEEDBACKPROC glResumeTransformFeedback;
PFNGLDRAWTRANSFORMFEEDBACKPROC glDrawTransformFeedback;
PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC glDrawTransformFeedbackStream;
PFNGLBEGINQUERYINDEXEDPROC glBeginQueryIndexed;
PFNGLENDQUERYINDEXEDPROC glEndQueryIndexed;
PFNGLGETQUERYINDEXEDIVPROC glGetQueryIndexediv;
//PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler;
//PFNGLSHADERBINARYPROC glShaderBinary;
//PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat;
//PFNGLDEPTHRANGEFPROC glDepthRangef;
//PFNGLCLEARDEPTHFPROC glClearDepthf;
//PFNGLGETPROGRAMBINARYPROC glGetProgramBinary;
//PFNGLPROGRAMBINARYPROC glProgramBinary;
//PFNGLPROGRAMPARAMETERIPROC glProgramParameteri;
//PFNGLUSEPROGRAMSTAGESPROC glUseProgramStages;
//PFNGLACTIVESHADERPROGRAMPROC glActiveShaderProgram;
//PFNGLCREATESHADERPROGRAMVPROC glCreateShaderProgramv;
//PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline;
//PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines;
//PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines;
//PFNGLISPROGRAMPIPELINEPROC glIsProgramPipeline;
//PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramPipelineiv;
//PFNGLPROGRAMUNIFORM1IPROC glProgramUniform1i;
//PFNGLPROGRAMUNIFORM1IVPROC glProgramUniform1iv;
//PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f;
//PFNGLPROGRAMUNIFORM1FVPROC glProgramUniform1fv;
//PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d;
//PFNGLPROGRAMUNIFORM1DVPROC glProgramUniform1dv;
//PFNGLPROGRAMUNIFORM1UIPROC glProgramUniform1ui;
//PFNGLPROGRAMUNIFORM1UIVPROC glProgramUniform1uiv;
//PFNGLPROGRAMUNIFORM2IPROC glProgramUniform2i;
//PFNGLPROGRAMUNIFORM2IVPROC glProgramUniform2iv;
//PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f;
//PFNGLPROGRAMUNIFORM2FVPROC glProgramUniform2fv;
//PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d;
//PFNGLPROGRAMUNIFORM2DVPROC glProgramUniform2dv;
//PFNGLPROGRAMUNIFORM2UIPROC glProgramUniform2ui;
//PFNGLPROGRAMUNIFORM2UIVPROC glProgramUniform2uiv;
//PFNGLPROGRAMUNIFORM3IPROC glProgramUniform3i;
//PFNGLPROGRAMUNIFORM3IVPROC glProgramUniform3iv;
//PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f;
//PFNGLPROGRAMUNIFORM3FVPROC glProgramUniform3fv;
//PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d;
//PFNGLPROGRAMUNIFORM3DVPROC glProgramUniform3dv;
//PFNGLPROGRAMUNIFORM3UIPROC glProgramUniform3ui;
//PFNGLPROGRAMUNIFORM3UIVPROC glProgramUniform3uiv;
//PFNGLPROGRAMUNIFORM4IPROC glProgramUniform4i;
//PFNGLPROGRAMUNIFORM4IVPROC glProgramUniform4iv;
//PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f;
//PFNGLPROGRAMUNIFORM4FVPROC glProgramUniform4fv;
//PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d;
//PFNGLPROGRAMUNIFORM4DVPROC glProgramUniform4dv;
//PFNGLPROGRAMUNIFORM4UIPROC glProgramUniform4ui;
//PFNGLPROGRAMUNIFORM4UIVPROC glProgramUniform4uiv;
//PFNGLPROGRAMUNIFORMMATRIX2FVPROC glProgramUniformMatrix2fv;
//PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv;
//PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv;
//PFNGLPROGRAMUNIFORMMATRIX2DVPROC glProgramUniformMatrix2dv;
//PFNGLPROGRAMUNIFORMMATRIX3DVPROC glProgramUniformMatrix3dv;
//PFNGLPROGRAMUNIFORMMATRIX4DVPROC glProgramUniformMatrix4dv;
//PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glProgramUniformMatrix2x3fv;
//PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glProgramUniformMatrix3x2fv;
//PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glProgramUniformMatrix2x4fv;
//PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glProgramUniformMatrix4x2fv;
//PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glProgramUniformMatrix3x4fv;
//PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glProgramUniformMatrix4x3fv;
//PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC glProgramUniformMatrix2x3dv;
//PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC glProgramUniformMatrix3x2dv;
//PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC glProgramUniformMatrix2x4dv;
//PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC glProgramUniformMatrix4x2dv;
//PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC glProgramUniformMatrix3x4dv;
//PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC glProgramUniformMatrix4x3dv;
//PFNGLVALIDATEPROGRAMPIPELINEPROC glValidateProgramPipeline;
//PFNGLGETPROGRAMPIPELINEINFOLOGPROC glGetProgramPipelineInfoLog;
//PFNGLVERTEXATTRIBL1DPROC glVertexAttribL1d;
//PFNGLVERTEXATTRIBL2DPROC glVertexAttribL2d;
//PFNGLVERTEXATTRIBL3DPROC glVertexAttribL3d;
//PFNGLVERTEXATTRIBL4DPROC glVertexAttribL4d;
//PFNGLVERTEXATTRIBL1DVPROC glVertexAttribL1dv;
//PFNGLVERTEXATTRIBL2DVPROC glVertexAttribL2dv;
//PFNGLVERTEXATTRIBL3DVPROC glVertexAttribL3dv;
//PFNGLVERTEXATTRIBL4DVPROC glVertexAttribL4dv;
//PFNGLVERTEXATTRIBLPOINTERPROC glVertexAttribLPointer;
//PFNGLGETVERTEXATTRIBLDVPROC glGetVertexAttribLdv;
//PFNGLVIEWPORTARRAYVPROC glViewportArrayv;
//PFNGLVIEWPORTINDEXEDFPROC glViewportIndexedf;
//PFNGLVIEWPORTINDEXEDFVPROC glViewportIndexedfv;
//PFNGLSCISSORARRAYVPROC glScissorArrayv;
//PFNGLSCISSORINDEXEDPROC glScissorIndexed;
//PFNGLSCISSORINDEXEDVPROC glScissorIndexedv;
//PFNGLDEPTHRANGEARRAYVPROC glDepthRangeArrayv;
//PFNGLDEPTHRANGEINDEXEDPROC glDepthRangeIndexed;
//PFNGLGETFLOATI_VPROC glGetFloati_v;
//PFNGLGETDOUBLEI_VPROC glGetDoublei_v;
//PFNGLCREATESYNCFROMCLEVENTARBPROC glCreateSyncFromCLeventARB;
//PFNGLDEBUGMESSAGECONTROLARBPROC glDebugMessageControlARB;
//PFNGLDEBUGMESSAGEINSERTARBPROC glDebugMessageInsertARB;
//PFNGLDEBUGMESSAGECALLBACKARBPROC glDebugMessageCallbackARB;
//PFNGLGETDEBUGMESSAGELOGARBPROC glGetDebugMessageLogARB;
//PFNGLGETGRAPHICSRESETSTATUSARBPROC glGetGraphicsResetStatusARB;
//PFNGLGETNMAPDVARBPROC glGetnMapdvARB;
//PFNGLGETNMAPFVARBPROC glGetnMapfvARB;
//PFNGLGETNMAPIVARBPROC glGetnMapivARB;
//PFNGLGETNPIXELMAPFVARBPROC glGetnPixelMapfvARB;
//PFNGLGETNPIXELMAPUIVARBPROC glGetnPixelMapuivARB;
//PFNGLGETNPIXELMAPUSVARBPROC glGetnPixelMapusvARB;
//PFNGLGETNPOLYGONSTIPPLEARBPROC glGetnPolygonStippleARB;
//PFNGLGETNCOLORTABLEARBPROC glGetnColorTableARB;
//PFNGLGETNCONVOLUTIONFILTERARBPROC glGetnConvolutionFilterARB;
//PFNGLGETNSEPARABLEFILTERARBPROC glGetnSeparableFilterARB;
//PFNGLGETNHISTOGRAMARBPROC glGetnHistogramARB;
//PFNGLGETNMINMAXARBPROC glGetnMinmaxARB;
//PFNGLGETNTEXIMAGEARBPROC glGetnTexImageARB;
//PFNGLREADNPIXELSARBPROC glReadnPixelsARB;
//PFNGLGETNCOMPRESSEDTEXIMAGEARBPROC glGetnCompressedTexImageARB;
//PFNGLGETNUNIFORMFVARBPROC glGetnUniformfvARB;
//PFNGLGETNUNIFORMIVARBPROC glGetnUniformivARB;
//PFNGLGETNUNIFORMUIVARBPROC glGetnUniformuivARB;
//PFNGLGETNUNIFORMDVARBPROC glGetnUniformdvARB;

namespace {

int MajorVer, MinorVer;

//-----------------------------------------------------------------------------
void* LoadEntryPoint(const char* name) {
    void* proc = SDL_GL_GetProcAddress(name);
    printf("%-40s %s\n", name, (proc ? "supported" : "not supported"));
    if (!proc) {
        ostringstream ss;
        ss << "OpenGL " << MajorVer << "." << MinorVer <<
            " is not supported by the graphics driver (failed to load " << name << " function).";
        throw runtime_error(ss.str());
    }
    return proc;
}
//-----------------------------------------------------------------------------

} // namespace

namespace gl {

//-----------------------------------------------------------------------------
void LoadCommandPointers(int version) {
    MajorVer = version / 10;
    MinorVer = version % 10;

    printf(
        "--------------------------------------------------\n"
        "\nLoading OpenGL %d.%d commands...\n\n"
        "--------------------------------------------------\n", MajorVer, MinorVer);

    /*if (version >= 10) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 1.0 commands\n"
            "--------------------------------------------------\n");
        glCullFace = (PFNGLCULLFACEPROC) LoadEntryPoint("glCullFace");
        glFrontFace = (PFNGLFRONTFACEPROC) LoadEntryPoint("glFrontFace");
        glHint = (PFNGLHINTPROC) LoadEntryPoint("glHint");
        glLineWidth = (PFNGLLINEWIDTHPROC) LoadEntryPoint("glLineWidth");
        glPointSize = (PFNGLPOINTSIZEPROC) LoadEntryPoint("glPointSize");
        glPolygonMode = (PFNGLPOLYGONMODEPROC) LoadEntryPoint("glPolygonMode");
        glScissor = (PFNGLSCISSORPROC) LoadEntryPoint("glScissor");
        glTexParameterf = (PFNGLTEXPARAMETERFPROC) LoadEntryPoint("glTexParameterf");
        glTexParameterfv = (PFNGLTEXPARAMETERFVPROC) LoadEntryPoint("glTexParameterfv");
        glTexParameteri = (PFNGLTEXPARAMETERIPROC) LoadEntryPoint("glTexParameteri");
        glTexParameteriv = (PFNGLTEXPARAMETERIVPROC) LoadEntryPoint("glTexParameteriv");
        glTexImage1D = (PFNGLTEXIMAGE1DPROC) LoadEntryPoint("glTexImage1D");
        glTexImage2D = (PFNGLTEXIMAGE2DPROC) LoadEntryPoint("glTexImage2D");
        glDrawBuffer = (PFNGLDRAWBUFFERPROC) LoadEntryPoint("glDrawBuffer");
        glClear = (PFNGLCLEARPROC) LoadEntryPoint("glClear");
        glClearColor = (PFNGLCLEARCOLORPROC) LoadEntryPoint("glClearColor");
        glClearStencil = (PFNGLCLEARSTENCILPROC) LoadEntryPoint("glClearStencil");
        glClearDepth = (PFNGLCLEARDEPTHPROC) LoadEntryPoint("glClearDepth");
        glStencilMask = (PFNGLSTENCILMASKPROC) LoadEntryPoint("glStencilMask");
        glColorMask = (PFNGLCOLORMASKPROC) LoadEntryPoint("glColorMask");
        glDepthMask = (PFNGLDEPTHMASKPROC) LoadEntryPoint("glDepthMask");
        glDisable = (PFNGLDISABLEPROC) LoadEntryPoint("glDisable");
        glEnable = (PFNGLENABLEPROC) LoadEntryPoint("glEnable");
        glFinish = (PFNGLFINISHPROC) LoadEntryPoint("glFinish");
        glFlush = (PFNGLFLUSHPROC) LoadEntryPoint("glFlush");
        glBlendFunc = (PFNGLBLENDFUNCPROC) LoadEntryPoint("glBlendFunc");
        glLogicOp = (PFNGLLOGICOPPROC) LoadEntryPoint("glLogicOp");
        glStencilFunc = (PFNGLSTENCILFUNCPROC) LoadEntryPoint("glStencilFunc");
        glStencilOp = (PFNGLSTENCILOPPROC) LoadEntryPoint("glStencilOp");
        glDepthFunc = (PFNGLDEPTHFUNCPROC) LoadEntryPoint("glDepthFunc");
        glPixelStoref = (PFNGLPIXELSTOREFPROC) LoadEntryPoint("glPixelStoref");
        glPixelStorei = (PFNGLPIXELSTOREIPROC) LoadEntryPoint("glPixelStorei");
        glReadBuffer = (PFNGLREADBUFFERPROC) LoadEntryPoint("glReadBuffer");
        glReadPixels = (PFNGLREADPIXELSPROC) LoadEntryPoint("glReadPixels");
        glGetBooleanv = (PFNGLGETBOOLEANVPROC) LoadEntryPoint("glGetBooleanv");
        glGetDoublev = (PFNGLGETDOUBLEVPROC) LoadEntryPoint("glGetDoublev");
        glGetError = (PFNGLGETERRORPROC) LoadEntryPoint("glGetError");
        glGetFloatv = (PFNGLGETFLOATVPROC) LoadEntryPoint("glGetFloatv");
        glGetIntegerv = (PFNGLGETINTEGERVPROC) LoadEntryPoint("glGetIntegerv");
        glGetString = (PFNGLGETSTRINGPROC) LoadEntryPoint("glGetString");
        glGetTexImage = (PFNGLGETTEXIMAGEPROC) LoadEntryPoint("glGetTexImage");
        glGetTexParameterfv = (PFNGLGETTEXPARAMETERFVPROC) LoadEntryPoint("glGetTexParameterfv");
        glGetTexParameteriv = (PFNGLGETTEXPARAMETERIVPROC) LoadEntryPoint("glGetTexParameteriv");
        glGetTexLevelParameterfv = (PFNGLGETTEXLEVELPARAMETERFVPROC) LoadEntryPoint("glGetTexLevelParameterfv");
        glGetTexLevelParameteriv = (PFNGLGETTEXLEVELPARAMETERIVPROC) LoadEntryPoint("glGetTexLevelParameteriv");
        glIsEnabled = (PFNGLISENABLEDPROC) LoadEntryPoint("glIsEnabled");
        glDepthRange = (PFNGLDEPTHRANGEPROC) LoadEntryPoint("glDepthRange");
        glViewport = (PFNGLVIEWPORTPROC) LoadEntryPoint("glViewport");
    }
    if (version >= 11) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 1.1 commands\n"
            "--------------------------------------------------\n");
        glDrawArrays = (PFNGLDRAWARRAYSPROC) LoadEntryPoint("glDrawArrays");
        glDrawElements = (PFNGLDRAWELEMENTSPROC) LoadEntryPoint("glDrawElements");
        glGetPointerv = (PFNGLGETPOINTERVPROC) LoadEntryPoint("glGetPointerv");
        glPolygonOffset = (PFNGLPOLYGONOFFSETPROC) LoadEntryPoint("glPolygonOffset");
        glCopyTexImage1D = (PFNGLCOPYTEXIMAGE1DPROC) LoadEntryPoint("glCopyTexImage1D");
        glCopyTexImage2D = (PFNGLCOPYTEXIMAGE2DPROC) LoadEntryPoint("glCopyTexImage2D");
        glCopyTexSubImage1D = (PFNGLCOPYTEXSUBIMAGE1DPROC) LoadEntryPoint("glCopyTexSubImage1D");
        glCopyTexSubImage2D = (PFNGLCOPYTEXSUBIMAGE2DPROC) LoadEntryPoint("glCopyTexSubImage2D");
        glTexSubImage1D = (PFNGLTEXSUBIMAGE1DPROC) LoadEntryPoint("glTexSubImage1D");
        glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC) LoadEntryPoint("glTexSubImage2D");
        glBindTexture = (PFNGLBINDTEXTUREPROC) LoadEntryPoint("glBindTexture");
        glDeleteTextures = (PFNGLDELETETEXTURESPROC) LoadEntryPoint("glDeleteTextures");
        glGenTextures = (PFNGLGENTEXTURESPROC) LoadEntryPoint("glGenTextures");
        glIsTexture = (PFNGLISTEXTUREPROC) LoadEntryPoint("glIsTexture");
    }*/

    if (version >= 12) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 1.2 commands\n"
            "--------------------------------------------------\n");
        glBlendColor = (PFNGLBLENDCOLORPROC) LoadEntryPoint("glBlendColor");
        glBlendEquation = (PFNGLBLENDEQUATIONPROC) LoadEntryPoint("glBlendEquation");
        glDrawRangeElements = (PFNGLDRAWRANGEELEMENTSPROC) LoadEntryPoint("glDrawRangeElements");
        glTexImage3D = (PFNGLTEXIMAGE3DPROC) LoadEntryPoint("glTexImage3D");
        glTexSubImage3D = (PFNGLTEXSUBIMAGE3DPROC) LoadEntryPoint("glTexSubImage3D");
        glCopyTexSubImage3D = (PFNGLCOPYTEXSUBIMAGE3DPROC) LoadEntryPoint("glCopyTexSubImage3D");
    }
    if (version >= 13) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 1.3 commands\n"
            "--------------------------------------------------\n");
        glActiveTexture = (PFNGLACTIVETEXTUREPROC) LoadEntryPoint("glActiveTexture");
        glSampleCoverage = (PFNGLSAMPLECOVERAGEPROC) LoadEntryPoint("glSampleCoverage");
        glCompressedTexImage3D = (PFNGLCOMPRESSEDTEXIMAGE3DPROC) LoadEntryPoint("glCompressedTexImage3D");
        glCompressedTexImage2D = (PFNGLCOMPRESSEDTEXIMAGE2DPROC) LoadEntryPoint("glCompressedTexImage2D");
        glCompressedTexImage1D = (PFNGLCOMPRESSEDTEXIMAGE1DPROC) LoadEntryPoint("glCompressedTexImage1D");
        glCompressedTexSubImage3D = (PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC) LoadEntryPoint("glCompressedTexSubImage3D");
        glCompressedTexSubImage2D = (PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC) LoadEntryPoint("glCompressedTexSubImage2D");
        glCompressedTexSubImage1D = (PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC) LoadEntryPoint("glCompressedTexSubImage1D");
        glGetCompressedTexImage = (PFNGLGETCOMPRESSEDTEXIMAGEPROC) LoadEntryPoint("glGetCompressedTexImage");
    }
    if (version >= 14) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 1.4 commands\n"
            "--------------------------------------------------\n");
        glBlendFuncSeparate = (PFNGLBLENDFUNCSEPARATEPROC) LoadEntryPoint("glBlendFuncSeparate");
        glMultiDrawArrays = (PFNGLMULTIDRAWARRAYSPROC) LoadEntryPoint("glMultiDrawArrays");
        glMultiDrawElements = (PFNGLMULTIDRAWELEMENTSPROC) LoadEntryPoint("glMultiDrawElements");
        glPointParameterf = (PFNGLPOINTPARAMETERFPROC) LoadEntryPoint("glPointParameterf");
        glPointParameterfv = (PFNGLPOINTPARAMETERFVPROC) LoadEntryPoint("glPointParameterfv");
        glPointParameteri = (PFNGLPOINTPARAMETERIPROC) LoadEntryPoint("glPointParameteri");
        glPointParameteriv = (PFNGLPOINTPARAMETERIVPROC) LoadEntryPoint("glPointParameteriv");
    }
    if (version >= 15) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 1.5 commands\n"
            "--------------------------------------------------\n");
        glGenQueries = (PFNGLGENQUERIESPROC) LoadEntryPoint("glGenQueries");
        glDeleteQueries = (PFNGLDELETEQUERIESPROC) LoadEntryPoint("glDeleteQueries");
        glIsQuery = (PFNGLISQUERYPROC) LoadEntryPoint("glIsQuery");
        glBeginQuery = (PFNGLBEGINQUERYPROC) LoadEntryPoint("glBeginQuery");
        glEndQuery = (PFNGLENDQUERYPROC) LoadEntryPoint("glEndQuery");
        glGetQueryiv = (PFNGLGETQUERYIVPROC) LoadEntryPoint("glGetQueryiv");
        glGetQueryObjectiv = (PFNGLGETQUERYOBJECTIVPROC) LoadEntryPoint("glGetQueryObjectiv");
        glGetQueryObjectuiv = (PFNGLGETQUERYOBJECTUIVPROC) LoadEntryPoint("glGetQueryObjectuiv");
        glBindBuffer = (PFNGLBINDBUFFERPROC) LoadEntryPoint("glBindBuffer");
        glDeleteBuffers = (PFNGLDELETEBUFFERSPROC) LoadEntryPoint("glDeleteBuffers");
        glGenBuffers = (PFNGLGENBUFFERSPROC) LoadEntryPoint("glGenBuffers");
        glIsBuffer = (PFNGLISBUFFERPROC) LoadEntryPoint("glIsBuffer");
        glBufferData = (PFNGLBUFFERDATAPROC) LoadEntryPoint("glBufferData");
        glBufferSubData = (PFNGLBUFFERSUBDATAPROC) LoadEntryPoint("glBufferSubData");
        glGetBufferSubData = (PFNGLGETBUFFERSUBDATAPROC) LoadEntryPoint("glGetBufferSubData");
        glMapBuffer = (PFNGLMAPBUFFERPROC) LoadEntryPoint("glMapBuffer");
        glUnmapBuffer = (PFNGLUNMAPBUFFERPROC) LoadEntryPoint("glUnmapBuffer");
        glGetBufferParameteriv = (PFNGLGETBUFFERPARAMETERIVPROC) LoadEntryPoint("glGetBufferParameteriv");
        glGetBufferPointerv = (PFNGLGETBUFFERPOINTERVPROC) LoadEntryPoint("glGetBufferPointerv");
    }
    if (version >= 20) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 2.0 commands\n"
            "--------------------------------------------------\n");
        glBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC) LoadEntryPoint("glBlendEquationSeparate");
        glDrawBuffers = (PFNGLDRAWBUFFERSPROC) LoadEntryPoint("glDrawBuffers");
        glStencilOpSeparate = (PFNGLSTENCILOPSEPARATEPROC) LoadEntryPoint("glStencilOpSeparate");
        glStencilFuncSeparate = (PFNGLSTENCILFUNCSEPARATEPROC) LoadEntryPoint("glStencilFuncSeparate");
        glStencilMaskSeparate = (PFNGLSTENCILMASKSEPARATEPROC) LoadEntryPoint("glStencilMaskSeparate");
        glAttachShader = (PFNGLATTACHSHADERPROC) LoadEntryPoint("glAttachShader");
        glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC) LoadEntryPoint("glBindAttribLocation");
        glCompileShader = (PFNGLCOMPILESHADERPROC) LoadEntryPoint("glCompileShader");
        glCreateProgram = (PFNGLCREATEPROGRAMPROC) LoadEntryPoint("glCreateProgram");
        glCreateShader = (PFNGLCREATESHADERPROC) LoadEntryPoint("glCreateShader");
        glDeleteProgram = (PFNGLDELETEPROGRAMPROC) LoadEntryPoint("glDeleteProgram");
        glDeleteShader = (PFNGLDELETESHADERPROC) LoadEntryPoint("glDeleteShader");
        glDetachShader = (PFNGLDETACHSHADERPROC) LoadEntryPoint("glDetachShader");
        glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC) LoadEntryPoint("glDisableVertexAttribArray");
        glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC) LoadEntryPoint("glEnableVertexAttribArray");
        glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC) LoadEntryPoint("glGetActiveAttrib");
        glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC) LoadEntryPoint("glGetActiveUniform");
        glGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC) LoadEntryPoint("glGetAttachedShaders");
        glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC) LoadEntryPoint("glGetAttribLocation");
        glGetProgramiv = (PFNGLGETPROGRAMIVPROC) LoadEntryPoint("glGetProgramiv");
        glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC) LoadEntryPoint("glGetProgramInfoLog");
        glGetShaderiv = (PFNGLGETSHADERIVPROC) LoadEntryPoint("glGetShaderiv");
        glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC) LoadEntryPoint("glGetShaderInfoLog");
        glGetShaderSource = (PFNGLGETSHADERSOURCEPROC) LoadEntryPoint("glGetShaderSource");
        glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC) LoadEntryPoint("glGetUniformLocation");
        glGetUniformfv = (PFNGLGETUNIFORMFVPROC) LoadEntryPoint("glGetUniformfv");
        glGetUniformiv = (PFNGLGETUNIFORMIVPROC) LoadEntryPoint("glGetUniformiv");
        glGetVertexAttribdv = (PFNGLGETVERTEXATTRIBDVPROC) LoadEntryPoint("glGetVertexAttribdv");
        glGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC) LoadEntryPoint("glGetVertexAttribfv");
        glGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC) LoadEntryPoint("glGetVertexAttribiv");
        glGetVertexAttribPointerv = (PFNGLGETVERTEXATTRIBPOINTERVPROC) LoadEntryPoint("glGetVertexAttribPointerv");
        glIsProgram = (PFNGLISPROGRAMPROC) LoadEntryPoint("glIsProgram");
        glIsShader = (PFNGLISSHADERPROC) LoadEntryPoint("glIsShader");
        glLinkProgram = (PFNGLLINKPROGRAMPROC) LoadEntryPoint("glLinkProgram");
        glShaderSource = (PFNGLSHADERSOURCEPROC) LoadEntryPoint("glShaderSource");
        glUseProgram = (PFNGLUSEPROGRAMPROC) LoadEntryPoint("glUseProgram");
        glUniform1f = (PFNGLUNIFORM1FPROC) LoadEntryPoint("glUniform1f");
        glUniform2f = (PFNGLUNIFORM2FPROC) LoadEntryPoint("glUniform2f");
        glUniform3f = (PFNGLUNIFORM3FPROC) LoadEntryPoint("glUniform3f");
        glUniform4f = (PFNGLUNIFORM4FPROC) LoadEntryPoint("glUniform4f");
        glUniform1i = (PFNGLUNIFORM1IPROC) LoadEntryPoint("glUniform1i");
        glUniform2i = (PFNGLUNIFORM2IPROC) LoadEntryPoint("glUniform2i");
        glUniform3i = (PFNGLUNIFORM3IPROC) LoadEntryPoint("glUniform3i");
        glUniform4i = (PFNGLUNIFORM4IPROC) LoadEntryPoint("glUniform4i");
        glUniform1fv = (PFNGLUNIFORM1FVPROC) LoadEntryPoint("glUniform1fv");
        glUniform2fv = (PFNGLUNIFORM2FVPROC) LoadEntryPoint("glUniform2fv");
        glUniform3fv = (PFNGLUNIFORM3FVPROC) LoadEntryPoint("glUniform3fv");
        glUniform4fv = (PFNGLUNIFORM4FVPROC) LoadEntryPoint("glUniform4fv");
        glUniform1iv = (PFNGLUNIFORM1IVPROC) LoadEntryPoint("glUniform1iv");
        glUniform2iv = (PFNGLUNIFORM2IVPROC) LoadEntryPoint("glUniform2iv");
        glUniform3iv = (PFNGLUNIFORM3IVPROC) LoadEntryPoint("glUniform3iv");
        glUniform4iv = (PFNGLUNIFORM4IVPROC) LoadEntryPoint("glUniform4iv");
        glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC) LoadEntryPoint("glUniformMatrix2fv");
        glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC) LoadEntryPoint("glUniformMatrix3fv");
        glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC) LoadEntryPoint("glUniformMatrix4fv");
        glValidateProgram = (PFNGLVALIDATEPROGRAMPROC) LoadEntryPoint("glValidateProgram");
        glVertexAttrib1d = (PFNGLVERTEXATTRIB1DPROC) LoadEntryPoint("glVertexAttrib1d");
        glVertexAttrib1dv = (PFNGLVERTEXATTRIB1DVPROC) LoadEntryPoint("glVertexAttrib1dv");
        glVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC) LoadEntryPoint("glVertexAttrib1f");
        glVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC) LoadEntryPoint("glVertexAttrib1fv");
        glVertexAttrib1s = (PFNGLVERTEXATTRIB1SPROC) LoadEntryPoint("glVertexAttrib1s");
        glVertexAttrib1sv = (PFNGLVERTEXATTRIB1SVPROC) LoadEntryPoint("glVertexAttrib1sv");
        glVertexAttrib2d = (PFNGLVERTEXATTRIB2DPROC) LoadEntryPoint("glVertexAttrib2d");
        glVertexAttrib2dv = (PFNGLVERTEXATTRIB2DVPROC) LoadEntryPoint("glVertexAttrib2dv");
        glVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC) LoadEntryPoint("glVertexAttrib2f");
        glVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC) LoadEntryPoint("glVertexAttrib2fv");
        glVertexAttrib2s = (PFNGLVERTEXATTRIB2SPROC) LoadEntryPoint("glVertexAttrib2s");
        glVertexAttrib2sv = (PFNGLVERTEXATTRIB2SVPROC) LoadEntryPoint("glVertexAttrib2sv");
        glVertexAttrib3d = (PFNGLVERTEXATTRIB3DPROC) LoadEntryPoint("glVertexAttrib3d");
        glVertexAttrib3dv = (PFNGLVERTEXATTRIB3DVPROC) LoadEntryPoint("glVertexAttrib3dv");
        glVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC) LoadEntryPoint("glVertexAttrib3f");
        glVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC) LoadEntryPoint("glVertexAttrib3fv");
        glVertexAttrib3s = (PFNGLVERTEXATTRIB3SPROC) LoadEntryPoint("glVertexAttrib3s");
        glVertexAttrib3sv = (PFNGLVERTEXATTRIB3SVPROC) LoadEntryPoint("glVertexAttrib3sv");
        glVertexAttrib4Nbv = (PFNGLVERTEXATTRIB4NBVPROC) LoadEntryPoint("glVertexAttrib4Nbv");
        glVertexAttrib4Niv = (PFNGLVERTEXATTRIB4NIVPROC) LoadEntryPoint("glVertexAttrib4Niv");
        glVertexAttrib4Nsv = (PFNGLVERTEXATTRIB4NSVPROC) LoadEntryPoint("glVertexAttrib4Nsv");
        glVertexAttrib4Nub = (PFNGLVERTEXATTRIB4NUBPROC) LoadEntryPoint("glVertexAttrib4Nub");
        glVertexAttrib4Nubv = (PFNGLVERTEXATTRIB4NUBVPROC) LoadEntryPoint("glVertexAttrib4Nubv");
        glVertexAttrib4Nuiv = (PFNGLVERTEXATTRIB4NUIVPROC) LoadEntryPoint("glVertexAttrib4Nuiv");
        glVertexAttrib4Nusv = (PFNGLVERTEXATTRIB4NUSVPROC) LoadEntryPoint("glVertexAttrib4Nusv");
        glVertexAttrib4bv = (PFNGLVERTEXATTRIB4BVPROC) LoadEntryPoint("glVertexAttrib4bv");
        glVertexAttrib4d = (PFNGLVERTEXATTRIB4DPROC) LoadEntryPoint("glVertexAttrib4d");
        glVertexAttrib4dv = (PFNGLVERTEXATTRIB4DVPROC) LoadEntryPoint("glVertexAttrib4dv");
        glVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC) LoadEntryPoint("glVertexAttrib4f");
        glVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC) LoadEntryPoint("glVertexAttrib4fv");
        glVertexAttrib4iv = (PFNGLVERTEXATTRIB4IVPROC) LoadEntryPoint("glVertexAttrib4iv");
        glVertexAttrib4s = (PFNGLVERTEXATTRIB4SPROC) LoadEntryPoint("glVertexAttrib4s");
        glVertexAttrib4sv = (PFNGLVERTEXATTRIB4SVPROC) LoadEntryPoint("glVertexAttrib4sv");
        glVertexAttrib4ubv = (PFNGLVERTEXATTRIB4UBVPROC) LoadEntryPoint("glVertexAttrib4ubv");
        glVertexAttrib4uiv = (PFNGLVERTEXATTRIB4UIVPROC) LoadEntryPoint("glVertexAttrib4uiv");
        glVertexAttrib4usv = (PFNGLVERTEXATTRIB4USVPROC) LoadEntryPoint("glVertexAttrib4usv");
        glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC) LoadEntryPoint("glVertexAttribPointer");
    }
    if (version >= 21) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 2.1 commands\n"
            "--------------------------------------------------\n");
        glUniformMatrix2x3fv = (PFNGLUNIFORMMATRIX2X3FVPROC) LoadEntryPoint("glUniformMatrix2x3fv");
        glUniformMatrix3x2fv = (PFNGLUNIFORMMATRIX3X2FVPROC) LoadEntryPoint("glUniformMatrix3x2fv");
        glUniformMatrix2x4fv = (PFNGLUNIFORMMATRIX2X4FVPROC) LoadEntryPoint("glUniformMatrix2x4fv");
        glUniformMatrix4x2fv = (PFNGLUNIFORMMATRIX4X2FVPROC) LoadEntryPoint("glUniformMatrix4x2fv");
        glUniformMatrix3x4fv = (PFNGLUNIFORMMATRIX3X4FVPROC) LoadEntryPoint("glUniformMatrix3x4fv");
        glUniformMatrix4x3fv = (PFNGLUNIFORMMATRIX4X3FVPROC) LoadEntryPoint("glUniformMatrix4x3fv");
    }
    if (version >= 30) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 3.0 commands\n"
            "--------------------------------------------------\n");
        glColorMaski = (PFNGLCOLORMASKIPROC) LoadEntryPoint("glColorMaski");
        glGetBooleani_v = (PFNGLGETBOOLEANI_VPROC) LoadEntryPoint("glGetBooleani_v");
        glGetIntegeri_v = (PFNGLGETINTEGERI_VPROC) LoadEntryPoint("glGetIntegeri_v");
        glEnablei = (PFNGLENABLEIPROC) LoadEntryPoint("glEnablei");
        glDisablei = (PFNGLDISABLEIPROC) LoadEntryPoint("glDisablei");
        glIsEnabledi = (PFNGLISENABLEDIPROC) LoadEntryPoint("glIsEnabledi");
        glBeginTransformFeedback = (PFNGLBEGINTRANSFORMFEEDBACKPROC) LoadEntryPoint("glBeginTransformFeedback");
        glEndTransformFeedback = (PFNGLENDTRANSFORMFEEDBACKPROC) LoadEntryPoint("glEndTransformFeedback");
        glBindBufferRange = (PFNGLBINDBUFFERRANGEPROC) LoadEntryPoint("glBindBufferRange");
        glBindBufferBase = (PFNGLBINDBUFFERBASEPROC) LoadEntryPoint("glBindBufferBase");
        glTransformFeedbackVaryings = (PFNGLTRANSFORMFEEDBACKVARYINGSPROC) LoadEntryPoint("glTransformFeedbackVaryings");
        glGetTransformFeedbackVarying = (PFNGLGETTRANSFORMFEEDBACKVARYINGPROC) LoadEntryPoint("glGetTransformFeedbackVarying");
        glClampColor = (PFNGLCLAMPCOLORPROC) LoadEntryPoint("glClampColor");
        glBeginConditionalRender = (PFNGLBEGINCONDITIONALRENDERPROC) LoadEntryPoint("glBeginConditionalRender");
        glEndConditionalRender = (PFNGLENDCONDITIONALRENDERPROC) LoadEntryPoint("glEndConditionalRender");
        glVertexAttribIPointer = (PFNGLVERTEXATTRIBIPOINTERPROC) LoadEntryPoint("glVertexAttribIPointer");
        glGetVertexAttribIiv = (PFNGLGETVERTEXATTRIBIIVPROC) LoadEntryPoint("glGetVertexAttribIiv");
        glGetVertexAttribIuiv = (PFNGLGETVERTEXATTRIBIUIVPROC) LoadEntryPoint("glGetVertexAttribIuiv");
        glVertexAttribI1i = (PFNGLVERTEXATTRIBI1IPROC) LoadEntryPoint("glVertexAttribI1i");
        glVertexAttribI2i = (PFNGLVERTEXATTRIBI2IPROC) LoadEntryPoint("glVertexAttribI2i");
        glVertexAttribI3i = (PFNGLVERTEXATTRIBI3IPROC) LoadEntryPoint("glVertexAttribI3i");
        glVertexAttribI4i = (PFNGLVERTEXATTRIBI4IPROC) LoadEntryPoint("glVertexAttribI4i");
        glVertexAttribI1ui = (PFNGLVERTEXATTRIBI1UIPROC) LoadEntryPoint("glVertexAttribI1ui");
        glVertexAttribI2ui = (PFNGLVERTEXATTRIBI2UIPROC) LoadEntryPoint("glVertexAttribI2ui");
        glVertexAttribI3ui = (PFNGLVERTEXATTRIBI3UIPROC) LoadEntryPoint("glVertexAttribI3ui");
        glVertexAttribI4ui = (PFNGLVERTEXATTRIBI4UIPROC) LoadEntryPoint("glVertexAttribI4ui");
        glVertexAttribI1iv = (PFNGLVERTEXATTRIBI1IVPROC) LoadEntryPoint("glVertexAttribI1iv");
        glVertexAttribI2iv = (PFNGLVERTEXATTRIBI2IVPROC) LoadEntryPoint("glVertexAttribI2iv");
        glVertexAttribI3iv = (PFNGLVERTEXATTRIBI3IVPROC) LoadEntryPoint("glVertexAttribI3iv");
        glVertexAttribI4iv = (PFNGLVERTEXATTRIBI4IVPROC) LoadEntryPoint("glVertexAttribI4iv");
        glVertexAttribI1uiv = (PFNGLVERTEXATTRIBI1UIVPROC) LoadEntryPoint("glVertexAttribI1uiv");
        glVertexAttribI2uiv = (PFNGLVERTEXATTRIBI2UIVPROC) LoadEntryPoint("glVertexAttribI2uiv");
        glVertexAttribI3uiv = (PFNGLVERTEXATTRIBI3UIVPROC) LoadEntryPoint("glVertexAttribI3uiv");
        glVertexAttribI4uiv = (PFNGLVERTEXATTRIBI4UIVPROC) LoadEntryPoint("glVertexAttribI4uiv");
        glVertexAttribI4bv = (PFNGLVERTEXATTRIBI4BVPROC) LoadEntryPoint("glVertexAttribI4bv");
        glVertexAttribI4sv = (PFNGLVERTEXATTRIBI4SVPROC) LoadEntryPoint("glVertexAttribI4sv");
        glVertexAttribI4ubv = (PFNGLVERTEXATTRIBI4UBVPROC) LoadEntryPoint("glVertexAttribI4ubv");
        glVertexAttribI4usv = (PFNGLVERTEXATTRIBI4USVPROC) LoadEntryPoint("glVertexAttribI4usv");
        glGetUniformuiv = (PFNGLGETUNIFORMUIVPROC) LoadEntryPoint("glGetUniformuiv");
        glBindFragDataLocation = (PFNGLBINDFRAGDATALOCATIONPROC) LoadEntryPoint("glBindFragDataLocation");
        glGetFragDataLocation = (PFNGLGETFRAGDATALOCATIONPROC) LoadEntryPoint("glGetFragDataLocation");
        glUniform1ui = (PFNGLUNIFORM1UIPROC) LoadEntryPoint("glUniform1ui");
        glUniform2ui = (PFNGLUNIFORM2UIPROC) LoadEntryPoint("glUniform2ui");
        glUniform3ui = (PFNGLUNIFORM3UIPROC) LoadEntryPoint("glUniform3ui");
        glUniform4ui = (PFNGLUNIFORM4UIPROC) LoadEntryPoint("glUniform4ui");
        glUniform1uiv = (PFNGLUNIFORM1UIVPROC) LoadEntryPoint("glUniform1uiv");
        glUniform2uiv = (PFNGLUNIFORM2UIVPROC) LoadEntryPoint("glUniform2uiv");
        glUniform3uiv = (PFNGLUNIFORM3UIVPROC) LoadEntryPoint("glUniform3uiv");
        glUniform4uiv = (PFNGLUNIFORM4UIVPROC) LoadEntryPoint("glUniform4uiv");
        glTexParameterIiv = (PFNGLTEXPARAMETERIIVPROC) LoadEntryPoint("glTexParameterIiv");
        glTexParameterIuiv = (PFNGLTEXPARAMETERIUIVPROC) LoadEntryPoint("glTexParameterIuiv");
        glGetTexParameterIiv = (PFNGLGETTEXPARAMETERIIVPROC) LoadEntryPoint("glGetTexParameterIiv");
        glGetTexParameterIuiv = (PFNGLGETTEXPARAMETERIUIVPROC) LoadEntryPoint("glGetTexParameterIuiv");
        glClearBufferiv = (PFNGLCLEARBUFFERIVPROC) LoadEntryPoint("glClearBufferiv");
        glClearBufferuiv = (PFNGLCLEARBUFFERUIVPROC) LoadEntryPoint("glClearBufferuiv");
        glClearBufferfv = (PFNGLCLEARBUFFERFVPROC) LoadEntryPoint("glClearBufferfv");
        glClearBufferfi = (PFNGLCLEARBUFFERFIPROC) LoadEntryPoint("glClearBufferfi");
        glGetStringi = (PFNGLGETSTRINGIPROC) LoadEntryPoint("glGetStringi");
        glIsRenderbuffer = (PFNGLISRENDERBUFFERPROC) LoadEntryPoint("glIsRenderbuffer");
        glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC) LoadEntryPoint("glBindRenderbuffer");
        glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC) LoadEntryPoint("glDeleteRenderbuffers");
        glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC) LoadEntryPoint("glGenRenderbuffers");
        glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC) LoadEntryPoint("glRenderbufferStorage");
        glGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC) LoadEntryPoint("glGetRenderbufferParameteriv");
        glIsFramebuffer = (PFNGLISFRAMEBUFFERPROC) LoadEntryPoint("glIsFramebuffer");
        glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC) LoadEntryPoint("glBindFramebuffer");
        glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC) LoadEntryPoint("glDeleteFramebuffers");
        glGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC) LoadEntryPoint("glGenFramebuffers");
        glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC) LoadEntryPoint("glCheckFramebufferStatus");
        glFramebufferTexture1D = (PFNGLFRAMEBUFFERTEXTURE1DPROC) LoadEntryPoint("glFramebufferTexture1D");
        glFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC) LoadEntryPoint("glFramebufferTexture2D");
        glFramebufferTexture3D = (PFNGLFRAMEBUFFERTEXTURE3DPROC) LoadEntryPoint("glFramebufferTexture3D");
        glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC) LoadEntryPoint("glFramebufferRenderbuffer");
        glGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC) LoadEntryPoint("glGetFramebufferAttachmentParameteriv");
        glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC) LoadEntryPoint("glGenerateMipmap");
        glBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC) LoadEntryPoint("glBlitFramebuffer");
        glRenderbufferStorageMultisample = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC) LoadEntryPoint("glRenderbufferStorageMultisample");
        glFramebufferTextureLayer = (PFNGLFRAMEBUFFERTEXTURELAYERPROC) LoadEntryPoint("glFramebufferTextureLayer");
        glMapBufferRange = (PFNGLMAPBUFFERRANGEPROC) LoadEntryPoint("glMapBufferRange");
        glFlushMappedBufferRange = (PFNGLFLUSHMAPPEDBUFFERRANGEPROC) LoadEntryPoint("glFlushMappedBufferRange");
        glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC) LoadEntryPoint("glBindVertexArray");
        glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC) LoadEntryPoint("glDeleteVertexArrays");
        glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC) LoadEntryPoint("glGenVertexArrays");
        glIsVertexArray = (PFNGLISVERTEXARRAYPROC) LoadEntryPoint("glIsVertexArray");
    }
    if (version >= 31) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 3.1 commands\n"
            "--------------------------------------------------\n");
        glDrawArraysInstanced = (PFNGLDRAWARRAYSINSTANCEDPROC) LoadEntryPoint("glDrawArraysInstanced");
        glDrawElementsInstanced = (PFNGLDRAWELEMENTSINSTANCEDPROC) LoadEntryPoint("glDrawElementsInstanced");
        glTexBuffer = (PFNGLTEXBUFFERPROC) LoadEntryPoint("glTexBuffer");
        glPrimitiveRestartIndex = (PFNGLPRIMITIVERESTARTINDEXPROC) LoadEntryPoint("glPrimitiveRestartIndex");
        glGetUniformIndices = (PFNGLGETUNIFORMINDICESPROC) LoadEntryPoint("glGetUniformIndices");
        glGetActiveUniformsiv = (PFNGLGETACTIVEUNIFORMSIVPROC) LoadEntryPoint("glGetActiveUniformsiv");
        glGetActiveUniformName = (PFNGLGETACTIVEUNIFORMNAMEPROC) LoadEntryPoint("glGetActiveUniformName");
        glGetUniformBlockIndex = (PFNGLGETUNIFORMBLOCKINDEXPROC) LoadEntryPoint("glGetUniformBlockIndex");
        glGetActiveUniformBlockiv = (PFNGLGETACTIVEUNIFORMBLOCKIVPROC) LoadEntryPoint("glGetActiveUniformBlockiv");
        glGetActiveUniformBlockName = (PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC) LoadEntryPoint("glGetActiveUniformBlockName");
        glUniformBlockBinding = (PFNGLUNIFORMBLOCKBINDINGPROC) LoadEntryPoint("glUniformBlockBinding");
        glCopyBufferSubData = (PFNGLCOPYBUFFERSUBDATAPROC) LoadEntryPoint("glCopyBufferSubData");
    }
    if (version >= 32) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 3.2 commands\n"
            "--------------------------------------------------\n");
        glGetInteger64i_v = (PFNGLGETINTEGER64I_VPROC) LoadEntryPoint("glGetInteger64i_v");
        glGetBufferParameteri64v = (PFNGLGETBUFFERPARAMETERI64VPROC) LoadEntryPoint("glGetBufferParameteri64v");
        glFramebufferTexture = (PFNGLFRAMEBUFFERTEXTUREPROC) LoadEntryPoint("glFramebufferTexture");
        glDrawElementsBaseVertex = (PFNGLDRAWELEMENTSBASEVERTEXPROC) LoadEntryPoint("glDrawElementsBaseVertex");
        glDrawRangeElementsBaseVertex = (PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC) LoadEntryPoint("glDrawRangeElementsBaseVertex");
        glDrawElementsInstancedBaseVertex = (PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC) LoadEntryPoint("glDrawElementsInstancedBaseVertex");
        glMultiDrawElementsBaseVertex = (PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC) LoadEntryPoint("glMultiDrawElementsBaseVertex");
        glProvokingVertex = (PFNGLPROVOKINGVERTEXPROC) LoadEntryPoint("glProvokingVertex");
        glFenceSync = (PFNGLFENCESYNCPROC) LoadEntryPoint("glFenceSync");
        glIsSync = (PFNGLISSYNCPROC) LoadEntryPoint("glIsSync");
        glDeleteSync = (PFNGLDELETESYNCPROC) LoadEntryPoint("glDeleteSync");
        glClientWaitSync = (PFNGLCLIENTWAITSYNCPROC) LoadEntryPoint("glClientWaitSync");
        glWaitSync = (PFNGLWAITSYNCPROC) LoadEntryPoint("glWaitSync");
        glGetInteger64v = (PFNGLGETINTEGER64VPROC) LoadEntryPoint("glGetInteger64v");
        glGetSynciv = (PFNGLGETSYNCIVPROC) LoadEntryPoint("glGetSynciv");
        glTexImage2DMultisample = (PFNGLTEXIMAGE2DMULTISAMPLEPROC) LoadEntryPoint("glTexImage2DMultisample");
        glTexImage3DMultisample = (PFNGLTEXIMAGE3DMULTISAMPLEPROC) LoadEntryPoint("glTexImage3DMultisample");
        glGetMultisamplefv = (PFNGLGETMULTISAMPLEFVPROC) LoadEntryPoint("glGetMultisamplefv");
        glSampleMaski = (PFNGLSAMPLEMASKIPROC) LoadEntryPoint("glSampleMaski");
    }
    if (version >= 33) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 3.3 commands\n"
            "--------------------------------------------------\n");
        //glVertexAttribDivisor = (PFNGLVERTEXATTRIBDIVISORPROC) LoadEntryPoint("glVertexAttribDivisor");
        glBindFragDataLocationIndexed = (PFNGLBINDFRAGDATALOCATIONINDEXEDPROC) LoadEntryPoint("glBindFragDataLocationIndexed");
        glGetFragDataIndex = (PFNGLGETFRAGDATAINDEXPROC) LoadEntryPoint("glGetFragDataIndex");
        glGenSamplers = (PFNGLGENSAMPLERSPROC) LoadEntryPoint("glGenSamplers");
        glDeleteSamplers = (PFNGLDELETESAMPLERSPROC) LoadEntryPoint("glDeleteSamplers");
        glIsSampler = (PFNGLISSAMPLERPROC) LoadEntryPoint("glIsSampler");
        glBindSampler = (PFNGLBINDSAMPLERPROC) LoadEntryPoint("glBindSampler");
        /*glSamplerParameteri = (PFNGLSAMPLERPARAMETERIPROC) LoadEntryPoint("glSamplerParameteri");
        glSamplerParameteriv = (PFNGLSAMPLERPARAMETERIVPROC) LoadEntryPoint("glSamplerParameteriv");
        glSamplerParameterf = (PFNGLSAMPLERPARAMETERFPROC) LoadEntryPoint("glSamplerParameterf");
        glSamplerParameterfv = (PFNGLSAMPLERPARAMETERFVPROC) LoadEntryPoint("glSamplerParameterfv");
        glSamplerParameterIiv = (PFNGLSAMPLERPARAMETERIIVPROC) LoadEntryPoint("glSamplerParameterIiv");
        glSamplerParameterIuiv = (PFNGLSAMPLERPARAMETERIUIVPROC) LoadEntryPoint("glSamplerParameterIuiv");
        glGetSamplerParameteriv = (PFNGLGETSAMPLERPARAMETERIVPROC) LoadEntryPoint("glGetSamplerParameteriv");
        glGetSamplerParameterIiv = (PFNGLGETSAMPLERPARAMETERIIVPROC) LoadEntryPoint("glGetSamplerParameterIiv");
        glGetSamplerParameterfv = (PFNGLGETSAMPLERPARAMETERFVPROC) LoadEntryPoint("glGetSamplerParameterfv");
        glGetSamplerParameterIuiv = (PFNGLGETSAMPLERPARAMETERIUIVPROC) LoadEntryPoint("glGetSamplerParameterIuiv");*/
        glQueryCounter = (PFNGLQUERYCOUNTERPROC) LoadEntryPoint("glQueryCounter");
        glGetQueryObjecti64v = (PFNGLGETQUERYOBJECTI64VPROC) LoadEntryPoint("glGetQueryObjecti64v");
        glGetQueryObjectui64v = (PFNGLGETQUERYOBJECTUI64VPROC) LoadEntryPoint("glGetQueryObjectui64v");
        glVertexP2ui = (PFNGLVERTEXP2UIPROC) LoadEntryPoint("glVertexP2ui");
        glVertexP2uiv = (PFNGLVERTEXP2UIVPROC) LoadEntryPoint("glVertexP2uiv");
        glVertexP3ui = (PFNGLVERTEXP3UIPROC) LoadEntryPoint("glVertexP3ui");
        glVertexP3uiv = (PFNGLVERTEXP3UIVPROC) LoadEntryPoint("glVertexP3uiv");
        glVertexP4ui = (PFNGLVERTEXP4UIPROC) LoadEntryPoint("glVertexP4ui");
        glVertexP4uiv = (PFNGLVERTEXP4UIVPROC) LoadEntryPoint("glVertexP4uiv");
        glTexCoordP1ui = (PFNGLTEXCOORDP1UIPROC) LoadEntryPoint("glTexCoordP1ui");
        glTexCoordP1uiv = (PFNGLTEXCOORDP1UIVPROC) LoadEntryPoint("glTexCoordP1uiv");
        glTexCoordP2ui = (PFNGLTEXCOORDP2UIPROC) LoadEntryPoint("glTexCoordP2ui");
        glTexCoordP2uiv = (PFNGLTEXCOORDP2UIVPROC) LoadEntryPoint("glTexCoordP2uiv");
        glTexCoordP3ui = (PFNGLTEXCOORDP3UIPROC) LoadEntryPoint("glTexCoordP3ui");
        glTexCoordP3uiv = (PFNGLTEXCOORDP3UIVPROC) LoadEntryPoint("glTexCoordP3uiv");
        glTexCoordP4ui = (PFNGLTEXCOORDP4UIPROC) LoadEntryPoint("glTexCoordP4ui");
        glTexCoordP4uiv = (PFNGLTEXCOORDP4UIVPROC) LoadEntryPoint("glTexCoordP4uiv");
        glMultiTexCoordP1ui = (PFNGLMULTITEXCOORDP1UIPROC) LoadEntryPoint("glMultiTexCoordP1ui");
        glMultiTexCoordP1uiv = (PFNGLMULTITEXCOORDP1UIVPROC) LoadEntryPoint("glMultiTexCoordP1uiv");
        glMultiTexCoordP2ui = (PFNGLMULTITEXCOORDP2UIPROC) LoadEntryPoint("glMultiTexCoordP2ui");
        glMultiTexCoordP2uiv = (PFNGLMULTITEXCOORDP2UIVPROC) LoadEntryPoint("glMultiTexCoordP2uiv");
        glMultiTexCoordP3ui = (PFNGLMULTITEXCOORDP3UIPROC) LoadEntryPoint("glMultiTexCoordP3ui");
        glMultiTexCoordP3uiv = (PFNGLMULTITEXCOORDP3UIVPROC) LoadEntryPoint("glMultiTexCoordP3uiv");
        glMultiTexCoordP4ui = (PFNGLMULTITEXCOORDP4UIPROC) LoadEntryPoint("glMultiTexCoordP4ui");
        glMultiTexCoordP4uiv = (PFNGLMULTITEXCOORDP4UIVPROC) LoadEntryPoint("glMultiTexCoordP4uiv");
        glNormalP3ui = (PFNGLNORMALP3UIPROC) LoadEntryPoint("glNormalP3ui");
        glNormalP3uiv = (PFNGLNORMALP3UIVPROC) LoadEntryPoint("glNormalP3uiv");
        glColorP3ui = (PFNGLCOLORP3UIPROC) LoadEntryPoint("glColorP3ui");
        glColorP3uiv = (PFNGLCOLORP3UIVPROC) LoadEntryPoint("glColorP3uiv");
        glColorP4ui = (PFNGLCOLORP4UIPROC) LoadEntryPoint("glColorP4ui");
        glColorP4uiv = (PFNGLCOLORP4UIVPROC) LoadEntryPoint("glColorP4uiv");
        glSecondaryColorP3ui = (PFNGLSECONDARYCOLORP3UIPROC) LoadEntryPoint("glSecondaryColorP3ui");
        glSecondaryColorP3uiv = (PFNGLSECONDARYCOLORP3UIVPROC) LoadEntryPoint("glSecondaryColorP3uiv");
        glVertexAttribP1ui = (PFNGLVERTEXATTRIBP1UIPROC) LoadEntryPoint("glVertexAttribP1ui");
        glVertexAttribP1uiv = (PFNGLVERTEXATTRIBP1UIVPROC) LoadEntryPoint("glVertexAttribP1uiv");
        glVertexAttribP2ui = (PFNGLVERTEXATTRIBP2UIPROC) LoadEntryPoint("glVertexAttribP2ui");
        glVertexAttribP2uiv = (PFNGLVERTEXATTRIBP2UIVPROC) LoadEntryPoint("glVertexAttribP2uiv");
        glVertexAttribP3ui = (PFNGLVERTEXATTRIBP3UIPROC) LoadEntryPoint("glVertexAttribP3ui");
        glVertexAttribP3uiv = (PFNGLVERTEXATTRIBP3UIVPROC) LoadEntryPoint("glVertexAttribP3uiv");
        glVertexAttribP4ui = (PFNGLVERTEXATTRIBP4UIPROC) LoadEntryPoint("glVertexAttribP4ui");
        glVertexAttribP4uiv = (PFNGLVERTEXATTRIBP4UIVPROC) LoadEntryPoint("glVertexAttribP4uiv");
    }
    if (version >= 40) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 4.0 commands\n"
            "--------------------------------------------------\n");
        glMinSampleShading = (PFNGLMINSAMPLESHADINGPROC) LoadEntryPoint("glMinSampleShading");
        glBlendEquationi = (PFNGLBLENDEQUATIONIPROC) LoadEntryPoint("glBlendEquationi");
        glBlendEquationSeparatei = (PFNGLBLENDEQUATIONSEPARATEIPROC) LoadEntryPoint("glBlendEquationSeparatei");
        glBlendFunci = (PFNGLBLENDFUNCIPROC) LoadEntryPoint("glBlendFunci");
        glBlendFuncSeparatei = (PFNGLBLENDFUNCSEPARATEIPROC) LoadEntryPoint("glBlendFuncSeparatei");
        glDrawArraysIndirect = (PFNGLDRAWARRAYSINDIRECTPROC) LoadEntryPoint("glDrawArraysIndirect");
        glDrawElementsIndirect = (PFNGLDRAWELEMENTSINDIRECTPROC) LoadEntryPoint("glDrawElementsIndirect");
        /*glUniform1d = (PFNGLUNIFORM1DPROC) LoadEntryPoint("glUniform1d");
        glUniform2d = (PFNGLUNIFORM2DPROC) LoadEntryPoint("glUniform2d");
        glUniform3d = (PFNGLUNIFORM3DPROC) LoadEntryPoint("glUniform3d");
        glUniform4d = (PFNGLUNIFORM4DPROC) LoadEntryPoint("glUniform4d");
        glUniform1dv = (PFNGLUNIFORM1DVPROC) LoadEntryPoint("glUniform1dv");
        glUniform2dv = (PFNGLUNIFORM2DVPROC) LoadEntryPoint("glUniform2dv");
        glUniform3dv = (PFNGLUNIFORM3DVPROC) LoadEntryPoint("glUniform3dv");
        glUniform4dv = (PFNGLUNIFORM4DVPROC) LoadEntryPoint("glUniform4dv");
        glUniformMatrix2dv = (PFNGLUNIFORMMATRIX2DVPROC) LoadEntryPoint("glUniformMatrix2dv");
        glUniformMatrix3dv = (PFNGLUNIFORMMATRIX3DVPROC) LoadEntryPoint("glUniformMatrix3dv");
        glUniformMatrix4dv = (PFNGLUNIFORMMATRIX4DVPROC) LoadEntryPoint("glUniformMatrix4dv");
        glUniformMatrix2x3dv = (PFNGLUNIFORMMATRIX2X3DVPROC) LoadEntryPoint("glUniformMatrix2x3dv");
        glUniformMatrix2x4dv = (PFNGLUNIFORMMATRIX2X4DVPROC) LoadEntryPoint("glUniformMatrix2x4dv");
        glUniformMatrix3x2dv = (PFNGLUNIFORMMATRIX3X2DVPROC) LoadEntryPoint("glUniformMatrix3x2dv");
        glUniformMatrix3x4dv = (PFNGLUNIFORMMATRIX3X4DVPROC) LoadEntryPoint("glUniformMatrix3x4dv");
        glUniformMatrix4x2dv = (PFNGLUNIFORMMATRIX4X2DVPROC) LoadEntryPoint("glUniformMatrix4x2dv");
        glUniformMatrix4x3dv = (PFNGLUNIFORMMATRIX4X3DVPROC) LoadEntryPoint("glUniformMatrix4x3dv");
        glGetUniformdv = (PFNGLGETUNIFORMDVPROC) LoadEntryPoint("glGetUniformdv");*/
        glGetSubroutineUniformLocation = (PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC) LoadEntryPoint("glGetSubroutineUniformLocation");
        glGetSubroutineIndex = (PFNGLGETSUBROUTINEINDEXPROC) LoadEntryPoint("glGetSubroutineIndex");
        glGetActiveSubroutineUniformiv = (PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC) LoadEntryPoint("glGetActiveSubroutineUniformiv");
        glGetActiveSubroutineUniformName = (PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC) LoadEntryPoint("glGetActiveSubroutineUniformName");
        glGetActiveSubroutineName = (PFNGLGETACTIVESUBROUTINENAMEPROC) LoadEntryPoint("glGetActiveSubroutineName");
        glUniformSubroutinesuiv = (PFNGLUNIFORMSUBROUTINESUIVPROC) LoadEntryPoint("glUniformSubroutinesuiv");
        glGetUniformSubroutineuiv = (PFNGLGETUNIFORMSUBROUTINEUIVPROC) LoadEntryPoint("glGetUniformSubroutineuiv");
        glGetProgramStageiv = (PFNGLGETPROGRAMSTAGEIVPROC) LoadEntryPoint("glGetProgramStageiv");
        glPatchParameteri = (PFNGLPATCHPARAMETERIPROC) LoadEntryPoint("glPatchParameteri");
        glPatchParameterfv = (PFNGLPATCHPARAMETERFVPROC) LoadEntryPoint("glPatchParameterfv");
        glBindTransformFeedback = (PFNGLBINDTRANSFORMFEEDBACKPROC) LoadEntryPoint("glBindTransformFeedback");
        glDeleteTransformFeedbacks = (PFNGLDELETETRANSFORMFEEDBACKSPROC) LoadEntryPoint("glDeleteTransformFeedbacks");
        glGenTransformFeedbacks = (PFNGLGENTRANSFORMFEEDBACKSPROC) LoadEntryPoint("glGenTransformFeedbacks");
        glIsTransformFeedback = (PFNGLISTRANSFORMFEEDBACKPROC) LoadEntryPoint("glIsTransformFeedback");
        glPauseTransformFeedback = (PFNGLPAUSETRANSFORMFEEDBACKPROC) LoadEntryPoint("glPauseTransformFeedback");
        glResumeTransformFeedback = (PFNGLRESUMETRANSFORMFEEDBACKPROC) LoadEntryPoint("glResumeTransformFeedback");
        glDrawTransformFeedback = (PFNGLDRAWTRANSFORMFEEDBACKPROC) LoadEntryPoint("glDrawTransformFeedback");
        glDrawTransformFeedbackStream = (PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC) LoadEntryPoint("glDrawTransformFeedbackStream");
        glBeginQueryIndexed = (PFNGLBEGINQUERYINDEXEDPROC) LoadEntryPoint("glBeginQueryIndexed");
        glEndQueryIndexed = (PFNGLENDQUERYINDEXEDPROC) LoadEntryPoint("glEndQueryIndexed");
        glGetQueryIndexediv = (PFNGLGETQUERYINDEXEDIVPROC) LoadEntryPoint("glGetQueryIndexediv");
    }
    /*
    glBlendEquationiARB = (PFNGLBLENDEQUATIONIARBPROC) LoadEntryPoint("glBlendEquationiARB");
    glBlendEquationSeparateiARB = (PFNGLBLENDEQUATIONSEPARATEIARBPROC) LoadEntryPoint("glBlendEquationSeparateiARB");
    glBlendFunciARB = (PFNGLBLENDFUNCIARBPROC) LoadEntryPoint("glBlendFunciARB");
    glBlendFuncSeparateiARB = (PFNGLBLENDFUNCSEPARATEIARBPROC) LoadEntryPoint("glBlendFuncSeparateiARB");
    glMinSampleShadingARB = (PFNGLMINSAMPLESHADINGARBPROC) LoadEntryPoint("glMinSampleShadingARB");
    glNamedStringARB = (PFNGLNAMEDSTRINGARBPROC) LoadEntryPoint("glNamedStringARB");
    glDeleteNamedStringARB = (PFNGLDELETENAMEDSTRINGARBPROC) LoadEntryPoint("glDeleteNamedStringARB");
    glCompileShaderIncludeARB = (PFNGLCOMPILESHADERINCLUDEARBPROC) LoadEntryPoint("glCompileShaderIncludeARB");
    glIsNamedStringARB = (PFNGLISNAMEDSTRINGARBPROC) LoadEntryPoint("glIsNamedStringARB");
    glGetNamedStringARB = (PFNGLGETNAMEDSTRINGARBPROC) LoadEntryPoint("glGetNamedStringARB");
    glGetNamedStringivARB = (PFNGLGETNAMEDSTRINGIVARBPROC) LoadEntryPoint("glGetNamedStringivARB");
    */
    if (version >= 41) {
        printf(
            "--------------------------------------------------\n"
            "OpenGL 4.1 commands\n"
            "--------------------------------------------------\n");
        /*glReleaseShaderCompiler = (PFNGLRELEASESHADERCOMPILERPROC) LoadEntryPoint("glReleaseShaderCompiler");
        glShaderBinary = (PFNGLSHADERBINARYPROC) LoadEntryPoint("glShaderBinary");
        glGetShaderPrecisionFormat = (PFNGLGETSHADERPRECISIONFORMATPROC) LoadEntryPoint("glGetShaderPrecisionFormat");
        glDepthRangef = (PFNGLDEPTHRANGEFPROC) LoadEntryPoint("glDepthRangef");
        glClearDepthf = (PFNGLCLEARDEPTHFPROC) LoadEntryPoint("glClearDepthf");
        glGetProgramBinary = (PFNGLGETPROGRAMBINARYPROC) LoadEntryPoint("glGetProgramBinary");
        glProgramBinary = (PFNGLPROGRAMBINARYPROC) LoadEntryPoint("glProgramBinary");
        glProgramParameteri = (PFNGLPROGRAMPARAMETERIPROC) LoadEntryPoint("glProgramParameteri");
        glUseProgramStages = (PFNGLUSEPROGRAMSTAGESPROC) LoadEntryPoint("glUseProgramStages");
        glActiveShaderProgram = (PFNGLACTIVESHADERPROGRAMPROC) LoadEntryPoint("glActiveShaderProgram");
        glCreateShaderProgramv = (PFNGLCREATESHADERPROGRAMVPROC) LoadEntryPoint("glCreateShaderProgramv");
        glBindProgramPipeline = (PFNGLBINDPROGRAMPIPELINEPROC) LoadEntryPoint("glBindProgramPipeline");
        glDeleteProgramPipelines = (PFNGLDELETEPROGRAMPIPELINESPROC) LoadEntryPoint("glDeleteProgramPipelines");
        glGenProgramPipelines = (PFNGLGENPROGRAMPIPELINESPROC) LoadEntryPoint("glGenProgramPipelines");
        glIsProgramPipeline = (PFNGLISPROGRAMPIPELINEPROC) LoadEntryPoint("glIsProgramPipeline");
        glGetProgramPipelineiv = (PFNGLGETPROGRAMPIPELINEIVPROC) LoadEntryPoint("glGetProgramPipelineiv");
        glProgramUniform1i = (PFNGLPROGRAMUNIFORM1IPROC) LoadEntryPoint("glProgramUniform1i");
        glProgramUniform1iv = (PFNGLPROGRAMUNIFORM1IVPROC) LoadEntryPoint("glProgramUniform1iv");
        glProgramUniform1f = (PFNGLPROGRAMUNIFORM1FPROC) LoadEntryPoint("glProgramUniform1f");
        glProgramUniform1fv = (PFNGLPROGRAMUNIFORM1FVPROC) LoadEntryPoint("glProgramUniform1fv");
        glProgramUniform1d = (PFNGLPROGRAMUNIFORM1DPROC) LoadEntryPoint("glProgramUniform1d");
        glProgramUniform1dv = (PFNGLPROGRAMUNIFORM1DVPROC) LoadEntryPoint("glProgramUniform1dv");
        glProgramUniform1ui = (PFNGLPROGRAMUNIFORM1UIPROC) LoadEntryPoint("glProgramUniform1ui");
        glProgramUniform1uiv = (PFNGLPROGRAMUNIFORM1UIVPROC) LoadEntryPoint("glProgramUniform1uiv");
        glProgramUniform2i = (PFNGLPROGRAMUNIFORM2IPROC) LoadEntryPoint("glProgramUniform2i");
        glProgramUniform2iv = (PFNGLPROGRAMUNIFORM2IVPROC) LoadEntryPoint("glProgramUniform2iv");
        glProgramUniform2f = (PFNGLPROGRAMUNIFORM2FPROC) LoadEntryPoint("glProgramUniform2f");
        glProgramUniform2fv = (PFNGLPROGRAMUNIFORM2FVPROC) LoadEntryPoint("glProgramUniform2fv");
        glProgramUniform2d = (PFNGLPROGRAMUNIFORM2DPROC) LoadEntryPoint("glProgramUniform2d");
        glProgramUniform2dv = (PFNGLPROGRAMUNIFORM2DVPROC) LoadEntryPoint("glProgramUniform2dv");
        glProgramUniform2ui = (PFNGLPROGRAMUNIFORM2UIPROC) LoadEntryPoint("glProgramUniform2ui");
        glProgramUniform2uiv = (PFNGLPROGRAMUNIFORM2UIVPROC) LoadEntryPoint("glProgramUniform2uiv");
        glProgramUniform3i = (PFNGLPROGRAMUNIFORM3IPROC) LoadEntryPoint("glProgramUniform3i");
        glProgramUniform3iv = (PFNGLPROGRAMUNIFORM3IVPROC) LoadEntryPoint("glProgramUniform3iv");
        glProgramUniform3f = (PFNGLPROGRAMUNIFORM3FPROC) LoadEntryPoint("glProgramUniform3f");
        glProgramUniform3fv = (PFNGLPROGRAMUNIFORM3FVPROC) LoadEntryPoint("glProgramUniform3fv");
        glProgramUniform3d = (PFNGLPROGRAMUNIFORM3DPROC) LoadEntryPoint("glProgramUniform3d");
        glProgramUniform3dv = (PFNGLPROGRAMUNIFORM3DVPROC) LoadEntryPoint("glProgramUniform3dv");
        glProgramUniform3ui = (PFNGLPROGRAMUNIFORM3UIPROC) LoadEntryPoint("glProgramUniform3ui");
        glProgramUniform3uiv = (PFNGLPROGRAMUNIFORM3UIVPROC) LoadEntryPoint("glProgramUniform3uiv");
        glProgramUniform4i = (PFNGLPROGRAMUNIFORM4IPROC) LoadEntryPoint("glProgramUniform4i");
        glProgramUniform4iv = (PFNGLPROGRAMUNIFORM4IVPROC) LoadEntryPoint("glProgramUniform4iv");
        glProgramUniform4f = (PFNGLPROGRAMUNIFORM4FPROC) LoadEntryPoint("glProgramUniform4f");
        glProgramUniform4fv = (PFNGLPROGRAMUNIFORM4FVPROC) LoadEntryPoint("glProgramUniform4fv");
        glProgramUniform4d = (PFNGLPROGRAMUNIFORM4DPROC) LoadEntryPoint("glProgramUniform4d");
        glProgramUniform4dv = (PFNGLPROGRAMUNIFORM4DVPROC) LoadEntryPoint("glProgramUniform4dv");
        glProgramUniform4ui = (PFNGLPROGRAMUNIFORM4UIPROC) LoadEntryPoint("glProgramUniform4ui");
        glProgramUniform4uiv = (PFNGLPROGRAMUNIFORM4UIVPROC) LoadEntryPoint("glProgramUniform4uiv");
        glProgramUniformMatrix2fv = (PFNGLPROGRAMUNIFORMMATRIX2FVPROC) LoadEntryPoint("glProgramUniformMatrix2fv");
        glProgramUniformMatrix3fv = (PFNGLPROGRAMUNIFORMMATRIX3FVPROC) LoadEntryPoint("glProgramUniformMatrix3fv");
        glProgramUniformMatrix4fv = (PFNGLPROGRAMUNIFORMMATRIX4FVPROC) LoadEntryPoint("glProgramUniformMatrix4fv");
        glProgramUniformMatrix2dv = (PFNGLPROGRAMUNIFORMMATRIX2DVPROC) LoadEntryPoint("glProgramUniformMatrix2dv");
        glProgramUniformMatrix3dv = (PFNGLPROGRAMUNIFORMMATRIX3DVPROC) LoadEntryPoint("glProgramUniformMatrix3dv");
        glProgramUniformMatrix4dv = (PFNGLPROGRAMUNIFORMMATRIX4DVPROC) LoadEntryPoint("glProgramUniformMatrix4dv");
        glProgramUniformMatrix2x3fv = (PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC) LoadEntryPoint("glProgramUniformMatrix2x3fv");
        glProgramUniformMatrix3x2fv = (PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC) LoadEntryPoint("glProgramUniformMatrix3x2fv");
        glProgramUniformMatrix2x4fv = (PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC) LoadEntryPoint("glProgramUniformMatrix2x4fv");
        glProgramUniformMatrix4x2fv = (PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC) LoadEntryPoint("glProgramUniformMatrix4x2fv");
        glProgramUniformMatrix3x4fv = (PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC) LoadEntryPoint("glProgramUniformMatrix3x4fv");
        glProgramUniformMatrix4x3fv = (PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC) LoadEntryPoint("glProgramUniformMatrix4x3fv");
        glProgramUniformMatrix2x3dv = (PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC) LoadEntryPoint("glProgramUniformMatrix2x3dv");
        glProgramUniformMatrix3x2dv = (PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC) LoadEntryPoint("glProgramUniformMatrix3x2dv");
        glProgramUniformMatrix2x4dv = (PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC) LoadEntryPoint("glProgramUniformMatrix2x4dv");
        glProgramUniformMatrix4x2dv = (PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC) LoadEntryPoint("glProgramUniformMatrix4x2dv");
        glProgramUniformMatrix3x4dv = (PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC) LoadEntryPoint("glProgramUniformMatrix3x4dv");
        glProgramUniformMatrix4x3dv = (PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC) LoadEntryPoint("glProgramUniformMatrix4x3dv");
        glValidateProgramPipeline = (PFNGLVALIDATEPROGRAMPIPELINEPROC) LoadEntryPoint("glValidateProgramPipeline");
        glGetProgramPipelineInfoLog = (PFNGLGETPROGRAMPIPELINEINFOLOGPROC) LoadEntryPoint("glGetProgramPipelineInfoLog");
        glVertexAttribL1d = (PFNGLVERTEXATTRIBL1DPROC) LoadEntryPoint("glVertexAttribL1d");
        glVertexAttribL2d = (PFNGLVERTEXATTRIBL2DPROC) LoadEntryPoint("glVertexAttribL2d");
        glVertexAttribL3d = (PFNGLVERTEXATTRIBL3DPROC) LoadEntryPoint("glVertexAttribL3d");
        glVertexAttribL4d = (PFNGLVERTEXATTRIBL4DPROC) LoadEntryPoint("glVertexAttribL4d");
        glVertexAttribL1dv = (PFNGLVERTEXATTRIBL1DVPROC) LoadEntryPoint("glVertexAttribL1dv");
        glVertexAttribL2dv = (PFNGLVERTEXATTRIBL2DVPROC) LoadEntryPoint("glVertexAttribL2dv");
        glVertexAttribL3dv = (PFNGLVERTEXATTRIBL3DVPROC) LoadEntryPoint("glVertexAttribL3dv");
        glVertexAttribL4dv = (PFNGLVERTEXATTRIBL4DVPROC) LoadEntryPoint("glVertexAttribL4dv");
        glVertexAttribLPointer = (PFNGLVERTEXATTRIBLPOINTERPROC) LoadEntryPoint("glVertexAttribLPointer");
        glGetVertexAttribLdv = (PFNGLGETVERTEXATTRIBLDVPROC) LoadEntryPoint("glGetVertexAttribLdv");
        glViewportArrayv = (PFNGLVIEWPORTARRAYVPROC) LoadEntryPoint("glViewportArrayv");
        glViewportIndexedf = (PFNGLVIEWPORTINDEXEDFPROC) LoadEntryPoint("glViewportIndexedf");
        glViewportIndexedfv = (PFNGLVIEWPORTINDEXEDFVPROC) LoadEntryPoint("glViewportIndexedfv");
        glScissorArrayv = (PFNGLSCISSORARRAYVPROC) LoadEntryPoint("glScissorArrayv");
        glScissorIndexed = (PFNGLSCISSORINDEXEDPROC) LoadEntryPoint("glScissorIndexed");
        glScissorIndexedv = (PFNGLSCISSORINDEXEDVPROC) LoadEntryPoint("glScissorIndexedv");
        glDepthRangeArrayv = (PFNGLDEPTHRANGEARRAYVPROC) LoadEntryPoint("glDepthRangeArrayv");
        glDepthRangeIndexed = (PFNGLDEPTHRANGEINDEXEDPROC) LoadEntryPoint("glDepthRangeIndexed");
        glGetFloati_v = (PFNGLGETFLOATI_VPROC) LoadEntryPoint("glGetFloati_v");
        glGetDoublei_v = (PFNGLGETDOUBLEI_VPROC) LoadEntryPoint("glGetDoublei_v");*/
    }
    /*
    glCreateSyncFromCLeventARB = (PFNGLCREATESYNCFROMCLEVENTARBPROC) LoadEntryPoint("glCreateSyncFromCLeventARB");
    glDebugMessageControlARB = (PFNGLDEBUGMESSAGECONTROLARBPROC) LoadEntryPoint("glDebugMessageControlARB");
    glDebugMessageInsertARB = (PFNGLDEBUGMESSAGEINSERTARBPROC) LoadEntryPoint("glDebugMessageInsertARB");
    glDebugMessageCallbackARB = (PFNGLDEBUGMESSAGECALLBACKARBPROC) LoadEntryPoint("glDebugMessageCallbackARB");
    glGetDebugMessageLogARB = (PFNGLGETDEBUGMESSAGELOGARBPROC) LoadEntryPoint("glGetDebugMessageLogARB");
    glGetGraphicsResetStatusARB = (PFNGLGETGRAPHICSRESETSTATUSARBPROC) LoadEntryPoint("glGetGraphicsResetStatusARB");
    glGetnMapdvARB = (PFNGLGETNMAPDVARBPROC) LoadEntryPoint("glGetnMapdvARB");
    glGetnMapfvARB = (PFNGLGETNMAPFVARBPROC) LoadEntryPoint("glGetnMapfvARB");
    glGetnMapivARB = (PFNGLGETNMAPIVARBPROC) LoadEntryPoint("glGetnMapivARB");
    glGetnPixelMapfvARB = (PFNGLGETNPIXELMAPFVARBPROC) LoadEntryPoint("glGetnPixelMapfvARB");
    glGetnPixelMapuivARB = (PFNGLGETNPIXELMAPUIVARBPROC) LoadEntryPoint("glGetnPixelMapuivARB");
    glGetnPixelMapusvARB = (PFNGLGETNPIXELMAPUSVARBPROC) LoadEntryPoint("glGetnPixelMapusvARB");
    glGetnPolygonStippleARB = (PFNGLGETNPOLYGONSTIPPLEARBPROC) LoadEntryPoint("glGetnPolygonStippleARB");
    glGetnColorTableARB = (PFNGLGETNCOLORTABLEARBPROC) LoadEntryPoint("glGetnColorTableARB");
    glGetnConvolutionFilterARB = (PFNGLGETNCONVOLUTIONFILTERARBPROC) LoadEntryPoint("glGetnConvolutionFilterARB");
    glGetnSeparableFilterARB = (PFNGLGETNSEPARABLEFILTERARBPROC) LoadEntryPoint("glGetnSeparableFilterARB");
    glGetnHistogramARB = (PFNGLGETNHISTOGRAMARBPROC) LoadEntryPoint("glGetnHistogramARB");
    glGetnMinmaxARB = (PFNGLGETNMINMAXARBPROC) LoadEntryPoint("glGetnMinmaxARB");
    glGetnTexImageARB = (PFNGLGETNTEXIMAGEARBPROC) LoadEntryPoint("glGetnTexImageARB");
    glReadnPixelsARB = (PFNGLREADNPIXELSARBPROC) LoadEntryPoint("glReadnPixelsARB");
    glGetnCompressedTexImageARB = (PFNGLGETNCOMPRESSEDTEXIMAGEARBPROC) LoadEntryPoint("glGetnCompressedTexImageARB");
    glGetnUniformfvARB = (PFNGLGETNUNIFORMFVARBPROC) LoadEntryPoint("glGetnUniformfvARB");
    glGetnUniformivARB = (PFNGLGETNUNIFORMIVARBPROC) LoadEntryPoint("glGetnUniformivARB");
    glGetnUniformuivARB = (PFNGLGETNUNIFORMUIVARBPROC) LoadEntryPoint("glGetnUniformuivARB");
    glGetnUniformdvARB = (PFNGLGETNUNIFORMDVARBPROC) LoadEntryPoint("glGetnUniformdvARB");
    */

    printf(
        "--------------------------------------------------\n"
        "\nOpenGL %d.%d commands loaded successfully!\n\n"
        "--------------------------------------------------\n", version / 10, version % 10);
}
//-----------------------------------------------------------------------------

} // namespace gl