//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.DataAccess.NequeoCompany.Data
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Data;
    using System.Threading;
    using System.Diagnostics;
    using System.Data.SqlClient;
    using System.Data.OleDb;
    using System.Data.Odbc;
    using System.Collections;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    using Nequeo.Data.DataType;
    using Nequeo.Data;
    using Nequeo.Data.Linq;
    using Nequeo.Data.Control;
    using Nequeo.Data.Custom;
    using Nequeo.Data.LinqToSql;
    using Nequeo.Data.DataSet;
    using Nequeo.Data.Edm;
    using Nequeo.ComponentModel;
    
    
    #region DataContext Context Ling Type
    /// <summary>
    /// The datacontext data context object class.
    /// </summary>
    [DatabaseAttribute("NequeoCompany")]
    public partial class DataContext : DataContextBase
    {
        
        private const string defaultDatabaseConnectionConfigurationKey = "Nequeo.DataAccess.NequeoCompany.Properties.Settings.NequeoCompanyDatabaseConnection";
        
        #region Extensibility Method Definitions
        /// <summary>
        /// On create data entity.
        /// </summary>
		partial void OnCreated();

        /// <summary>
        /// On load data entity.
        /// </summary>
		partial void OnLoaded();

		#endregion
        
        /// <summary>
        /// Default constructor.
        /// </summary>
        public DataContext() : 
                base(defaultDatabaseConnectionConfigurationKey, Nequeo.Data.DataType.ConnectionContext.ConnectionType.SqlConnection, Nequeo.Data.DataType.ConnectionContext.ConnectionDataType.SqlDataType, new Nequeo.Data.SqlServer.DataAccess())
        {
            OnCreated();
        }
        
        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <param name="connectionConfigKey">The database connection configuration key.</param>
        /// <param name="connectionType">The connection type.</param>
        /// <param name="connectionDataType">The connection data type.</param>
        /// <param name="dataAccessProvider">The data access provider.</param>
        public DataContext(string connectionConfigKey, Nequeo.Data.DataType.ConnectionContext.ConnectionType connectionType, Nequeo.Data.DataType.ConnectionContext.ConnectionDataType connectionDataType, Nequeo.Data.DataType.IDataAccess dataAccessProvider) : 
                base(connectionConfigKey, connectionType, connectionDataType, dataAccessProvider)
        {
            OnCreated();
        }
        
        #region Public Ling Properties
        /// <summary>
        /// Gets, the purchasetype queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.PurchaseType> PurchaseTypes
        {
            get
            {
                return this.GetTable<Data.PurchaseType>();
            }
        }
        
        /// <summary>
        /// Gets, the payintervaltype queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.PayIntervalType> PayIntervalTypes
        {
            get
            {
                return this.GetTable<Data.PayIntervalType>();
            }
        }
        
        /// <summary>
        /// Gets, the accounttype queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.AccountType> AccountTypes
        {
            get
            {
                return this.GetTable<Data.AccountType>();
            }
        }
        
        /// <summary>
        /// Gets, the accounttransactions queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.AccountTransactions> AccountTransactions
        {
            get
            {
                return this.GetTable<Data.AccountTransactions>();
            }
        }
        
        /// <summary>
        /// Gets, the employeepayg queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.EmployeePAYG> EmployeePAYGs
        {
            get
            {
                return this.GetTable<Data.EmployeePAYG>();
            }
        }
        
        /// <summary>
        /// Gets, the transactiontype queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.TransactionType> TransactionTypes
        {
            get
            {
                return this.GetTable<Data.TransactionType>();
            }
        }
        
        /// <summary>
        /// Gets, the paymenttype queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.PaymentType> PaymentTypes
        {
            get
            {
                return this.GetTable<Data.PaymentType>();
            }
        }
        
        /// <summary>
        /// Gets, the vendordetails queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.VendorDetails> VendorDetails
        {
            get
            {
                return this.GetTable<Data.VendorDetails>();
            }
        }
        
        /// <summary>
        /// Gets, the datamember queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.DataMember> DataMembers
        {
            get
            {
                return this.GetTable<Data.DataMember>();
            }
        }
        
        /// <summary>
        /// Gets, the companies queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.Companies> Companies
        {
            get
            {
                return this.GetTable<Data.Companies>();
            }
        }
        
        /// <summary>
        /// Gets, the customers queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.Customers> Customers
        {
            get
            {
                return this.GetTable<Data.Customers>();
            }
        }
        
        /// <summary>
        /// Gets, the usertype queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.UserType> UserTypes
        {
            get
            {
                return this.GetTable<Data.UserType>();
            }
        }
        
        /// <summary>
        /// Gets, the employees queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.Employees> Employees
        {
            get
            {
                return this.GetTable<Data.Employees>();
            }
        }
        
        /// <summary>
        /// Gets, the user queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.User> Users
        {
            get
            {
                return this.GetTable<Data.User>();
            }
        }
        
        /// <summary>
        /// Gets, the assets queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.Assets> Assets
        {
            get
            {
                return this.GetTable<Data.Assets>();
            }
        }
        
        /// <summary>
        /// Gets, the vendors queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.Vendors> Vendors
        {
            get
            {
                return this.GetTable<Data.Vendors>();
            }
        }
        
        /// <summary>
        /// Gets, the invoices queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.Invoices> Invoices
        {
            get
            {
                return this.GetTable<Data.Invoices>();
            }
        }
        
        /// <summary>
        /// Gets, the products queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.Products> Products
        {
            get
            {
                return this.GetTable<Data.Products>();
            }
        }
        
        /// <summary>
        /// Gets, the invoiceproducts queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.InvoiceProducts> InvoiceProducts
        {
            get
            {
                return this.GetTable<Data.InvoiceProducts>();
            }
        }
        
        /// <summary>
        /// Gets, the taxreturn queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.TaxReturn> TaxReturns
        {
            get
            {
                return this.GetTable<Data.TaxReturn>();
            }
        }
        
        /// <summary>
        /// Gets, the companypayginstalment queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.CompanyPAYGInstalment> CompanyPAYGInstalments
        {
            get
            {
                return this.GetTable<Data.CompanyPAYGInstalment>();
            }
        }
        
        /// <summary>
        /// Gets, the wages queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.Wages> Wages
        {
            get
            {
                return this.GetTable<Data.Wages>();
            }
        }
        
        /// <summary>
        /// Gets, the invoicedetails queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.InvoiceDetails> InvoiceDetails
        {
            get
            {
                return this.GetTable<Data.InvoiceDetails>();
            }
        }
        
        /// <summary>
        /// Gets, the datamembertables queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.DataMemberTables> DataMemberTables
        {
            get
            {
                return this.GetTable<Data.DataMemberTables>();
            }
        }
        
        /// <summary>
        /// Gets, the assetcategory queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.AssetCategory> AssetCategories
        {
            get
            {
                return this.GetTable<Data.AssetCategory>();
            }
        }
        
        /// <summary>
        /// Gets, the productcategory queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.ProductCategory> ProductCategories
        {
            get
            {
                return this.GetTable<Data.ProductCategory>();
            }
        }
        
        /// <summary>
        /// Gets, the productsubcategory queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.ProductSubCategory> ProductSubCategories
        {
            get
            {
                return this.GetTable<Data.ProductSubCategory>();
            }
        }
        
        /// <summary>
        /// Gets, the super queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.Super> Supers
        {
            get
            {
                return this.GetTable<Data.Super>();
            }
        }
        
        /// <summary>
        /// Gets, the expensetype queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.ExpenseType> ExpenseTypes
        {
            get
            {
                return this.GetTable<Data.ExpenseType>();
            }
        }
        
        /// <summary>
        /// Gets, the employeebankaccounts queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.EmployeeBankAccounts> EmployeeBankAccounts
        {
            get
            {
                return this.GetTable<Data.EmployeeBankAccounts>();
            }
        }
        
        /// <summary>
        /// Gets, the incometype queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.IncomeType> IncomeTypes
        {
            get
            {
                return this.GetTable<Data.IncomeType>();
            }
        }
        
        /// <summary>
        /// Gets, the employeesuperaccounts queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.EmployeeSuperAccounts> EmployeeSuperAccounts
        {
            get
            {
                return this.GetTable<Data.EmployeeSuperAccounts>();
            }
        }
        
        /// <summary>
        /// Gets, the gstincometype queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.GstIncomeType> GstIncomeTypes
        {
            get
            {
                return this.GetTable<Data.GstIncomeType>();
            }
        }
        
        /// <summary>
        /// Gets, the state queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.State> States
        {
            get
            {
                return this.GetTable<Data.State>();
            }
        }
        
        /// <summary>
        /// Gets, the bas queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.BAS> BASs
        {
            get
            {
                return this.GetTable<Data.BAS>();
            }
        }
        
        /// <summary>
        /// Gets, the productstatus queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.ProductStatus> ProductStatus
        {
            get
            {
                return this.GetTable<Data.ProductStatus>();
            }
        }
        
        /// <summary>
        /// Gets, the accounts queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.Accounts> Accounts
        {
            get
            {
                return this.GetTable<Data.Accounts>();
            }
        }
        
        /// <summary>
        /// Gets, the genericdata queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.GenericData> GenericDatas
        {
            get
            {
                return this.GetTable<Data.GenericData>();
            }
        }
        #endregion
        
        #region Public Ling Properties
        /// <summary>
        /// Gets, the accounttransactioncreditdebitsubtotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.AccountTransactionCreditDebitSubtotal> AccountTransactionCreditDebitSubtotals
        {
            get
            {
                return this.GetTable<Data.AccountTransactionCreditDebitSubtotal>();
            }
        }
        
        /// <summary>
        /// Gets, the employeepaygsubtotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.EmployeePAYGSubtotal> EmployeePAYGSubtotals
        {
            get
            {
                return this.GetTable<Data.EmployeePAYGSubtotal>();
            }
        }
        
        /// <summary>
        /// Gets, the employeepaygsubtotaltotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.EmployeePAYGSubtotalTotal> EmployeePAYGSubtotalTotals
        {
            get
            {
                return this.GetTable<Data.EmployeePAYGSubtotalTotal>();
            }
        }
        
        /// <summary>
        /// Gets, the vendordetailssubtotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.VendorDetailsSubtotal> VendorDetailsSubtotals
        {
            get
            {
                return this.GetTable<Data.VendorDetailsSubtotal>();
            }
        }
        
        /// <summary>
        /// Gets, the invoiceproductssubtotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.InvoiceProductsSubtotal> InvoiceProductsSubtotals
        {
            get
            {
                return this.GetTable<Data.InvoiceProductsSubtotal>();
            }
        }
        
        /// <summary>
        /// Gets, the invoiceproductssubtotaltotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.InvoiceProductsSubtotalTotal> InvoiceProductsSubtotalTotals
        {
            get
            {
                return this.GetTable<Data.InvoiceProductsSubtotalTotal>();
            }
        }
        
        /// <summary>
        /// Gets, the customerinvoicedetailstotals queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.CustomerInvoiceDetailsTotals> CustomerInvoiceDetailsTotals
        {
            get
            {
                return this.GetTable<Data.CustomerInvoiceDetailsTotals>();
            }
        }
        
        /// <summary>
        /// Gets, the customerinvoiceproductstotals queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.CustomerInvoiceProductsTotals> CustomerInvoiceProductsTotals
        {
            get
            {
                return this.GetTable<Data.CustomerInvoiceProductsTotals>();
            }
        }
        
        /// <summary>
        /// Gets, the customerinvoicedetailstotaltotals queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.CustomerInvoiceDetailsTotalTotals> CustomerInvoiceDetailsTotalTotals
        {
            get
            {
                return this.GetTable<Data.CustomerInvoiceDetailsTotalTotals>();
            }
        }
        
        /// <summary>
        /// Gets, the customerinvoiceproductstotaltotals queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.CustomerInvoiceProductsTotalTotals> CustomerInvoiceProductsTotalTotals
        {
            get
            {
                return this.GetTable<Data.CustomerInvoiceProductsTotalTotals>();
            }
        }
        
        /// <summary>
        /// Gets, the productsinvoicecustomersummary queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.ProductsInvoiceCustomerSummary> ProductsInvoiceCustomerSummaries
        {
            get
            {
                return this.GetTable<Data.ProductsInvoiceCustomerSummary>();
            }
        }
        
        /// <summary>
        /// Gets, the accounttransactiontypedebit queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.AccountTransactionTypeDebit> AccountTransactionTypeDebits
        {
            get
            {
                return this.GetTable<Data.AccountTransactionTypeDebit>();
            }
        }
        
        /// <summary>
        /// Gets, the accounttransactiontypecredit queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.AccountTransactionTypeCredit> AccountTransactionTypeCredits
        {
            get
            {
                return this.GetTable<Data.AccountTransactionTypeCredit>();
            }
        }
        
        /// <summary>
        /// Gets, the invoicesubtotals queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.InvoiceSubtotals> InvoiceSubtotals
        {
            get
            {
                return this.GetTable<Data.InvoiceSubtotals>();
            }
        }
        
        /// <summary>
        /// Gets, the invoicesubtotaltotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.InvoiceSubtotalTotal> InvoiceSubtotalTotals
        {
            get
            {
                return this.GetTable<Data.InvoiceSubtotalTotal>();
            }
        }
        
        /// <summary>
        /// Gets, the accounttransactioncredittotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.AccountTransactionCreditTotal> AccountTransactionCreditTotals
        {
            get
            {
                return this.GetTable<Data.AccountTransactionCreditTotal>();
            }
        }
        
        /// <summary>
        /// Gets, the employeewagesubtotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.EmployeeWageSubtotal> EmployeeWageSubtotals
        {
            get
            {
                return this.GetTable<Data.EmployeeWageSubtotal>();
            }
        }
        
        /// <summary>
        /// Gets, the accounttransactiondebittotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.AccountTransactionDebitTotal> AccountTransactionDebitTotals
        {
            get
            {
                return this.GetTable<Data.AccountTransactionDebitTotal>();
            }
        }
        
        /// <summary>
        /// Gets, the employeewagesubtotaltotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.EmployeeWageSubtotalTotal> EmployeeWageSubtotalTotals
        {
            get
            {
                return this.GetTable<Data.EmployeeWageSubtotalTotal>();
            }
        }
        
        /// <summary>
        /// Gets, the employeewagetotalbyemployee queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.EmployeeWageTotalByEmployee> EmployeeWageTotalByEmployees
        {
            get
            {
                return this.GetTable<Data.EmployeeWageTotalByEmployee>();
            }
        }
        
        /// <summary>
        /// Gets, the vendordetailssubtotaltotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.VendorDetailsSubtotalTotal> VendorDetailsSubtotalTotals
        {
            get
            {
                return this.GetTable<Data.VendorDetailsSubtotalTotal>();
            }
        }
        
        /// <summary>
        /// Gets, the employeesupersubtotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.EmployeeSuperSubtotal> EmployeeSuperSubtotals
        {
            get
            {
                return this.GetTable<Data.EmployeeSuperSubtotal>();
            }
        }
        
        /// <summary>
        /// Gets, the employeesupersubtotaltotal queryable provider property for the object.
        /// </summary>
        public Nequeo.Data.Linq.Query<Data.EmployeeSuperSubtotalTotal> EmployeeSuperSubtotalTotals
        {
            get
            {
                return this.GetTable<Data.EmployeeSuperSubtotalTotal>();
            }
        }
        #endregion
    }
    #endregion
}
