// Warning 169 (Disables the 'Never used' warning)
#pragma warning disable 169
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.DataAccess.NequeoCompany.Data.Extension
{
    using System;
    using System.Text;
    using System.Data;
    using System.Threading;
    using System.Diagnostics;
    using System.Data.SqlClient;
    using System.Data.OleDb;
    using System.Data.Odbc;
    using System.Collections;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Data.Linq;
    using System.Data.Linq.SqlClient;
    using System.Data.Linq.Mapping;
    using Nequeo.Data.DataType;
    using Nequeo.Data;
    using Nequeo.Data.Linq;
    using Nequeo.Data.Control;
    using Nequeo.Data.Custom;
    using Nequeo.Data.LinqToSql;
    using Nequeo.Data.DataSet;
    using Nequeo.Data.Edm;
    using Nequeo.ComponentModel;
    
    
    /// <summary>
    /// The vendors object class.
    /// </summary>
    public partial class Vendors
    {
        
        #region Public Function Methods
        /// <summary>
        /// Execute the getvendorvendordetailsbetweendatecategoryasset routine.
        /// </summary>
        /// <param name="fromDate">Initial value of FromDate.</param>
        /// <param name="toDate">Initial value of ToDate.</param>
        /// <param name="category">Initial value of Category.</param>
        /// <returns>The execution result.</returns>
        [FunctionRoutineAttribute("dbo.GetVendorVendorDetailsBetweenDateCategoryAsset", FunctionRoutineType.StoredProcedure)]
        public virtual List<Data.Extended.GetVendorVendorDetailsBetweenDateCategoryAssetResult> GetVendorVendorDetailsBetweenDateCategoryAsset([FunctionParameterAttribute("@FromDate", "datetime", 8, ParameterDirection.Input, true)] System.Nullable<System.DateTime> fromDate, [FunctionParameterAttribute("@ToDate", "datetime", 8, ParameterDirection.Input, true)] System.Nullable<System.DateTime> toDate, [FunctionParameterAttribute("@Category", "varchar", 50, ParameterDirection.Input, true)] string category)
        {
            IExecuteFunctionResult result = Common.ExecuteFunction(Common, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fromDate, toDate, category);
            return ((List<Data.Extended.GetVendorVendorDetailsBetweenDateCategoryAssetResult>)(result.ReturnValue));
        }
        
        /// <summary>
        /// Execute the getvendorvendordetailscategoryasset routine.
        /// </summary>
        /// <param name="category">Initial value of Category.</param>
        /// <returns>The execution result.</returns>
        [FunctionRoutineAttribute("dbo.GetVendorVendorDetailsCategoryAsset", FunctionRoutineType.StoredProcedure)]
        public virtual List<Data.Extended.GetVendorVendorDetailsCategoryAssetResult> GetVendorVendorDetailsCategoryAsset([FunctionParameterAttribute("@Category", "varchar", 50, ParameterDirection.Input, true)] string category)
        {
            IExecuteFunctionResult result = Common.ExecuteFunction(Common, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category);
            return ((List<Data.Extended.GetVendorVendorDetailsCategoryAssetResult>)(result.ReturnValue));
        }
        #endregion
    }
}
namespace Nequeo.DataAccess.NequeoCompany.Data.Extended
{
    using System;
    using System.Text;
    using System.Data;
    using System.Threading;
    using System.Diagnostics;
    using System.Data.SqlClient;
    using System.Data.OleDb;
    using System.Data.Odbc;
    using System.Collections;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Data.Linq;
    using System.Data.Linq.SqlClient;
    using System.Data.Linq.Mapping;
    using Nequeo.Data.DataType;
    using Nequeo.Data;
    using Nequeo.Data.Linq;
    using Nequeo.Data.Control;
    using Nequeo.Data.Custom;
    using Nequeo.Data.LinqToSql;
    using Nequeo.Data.DataSet;
    using Nequeo.Data.Edm;
    using Nequeo.ComponentModel;
    
    
    #region GetVendorVendorDetailsBetweenDateCategoryAssetResult Data Entity Type
    /// <summary>
    /// The getvendorvendordetailsbetweendatecategoryassetresult data object class.
    /// </summary>
    [DataContractAttribute(Name = "GetVendorVendorDetailsBetweenDateCategoryAssetResult", IsReference = true)]
    [SerializableAttribute()]
    [KnownTypeAttribute(typeof(DataBase))]
    public partial class GetVendorVendorDetailsBetweenDateCategoryAssetResult : DataBase
    {
        
        private int _VendorID;
        
        private string _CompanyName;
        
        private string _Firstname;
        
        private string _Surname;
        
        private string _Address;
        
        private string _Suburb;
        
        private string _State;
        
        private string _Postcode;
        
        private string _PhoneNumber;
        
        private string _FaxNumber;
        
        private string _MobileNumber;
        
        private string _EmailAddress;
        
        private string _WebSite;
        
        private string _ABN;
        
        private string _PostalAddress;
        
        private string _PostalSuburb;
        
        private string _PostalState;
        
        private string _PostalPostcode;
        
        private string _Comments;
        
        private int _VendorDetailsID;
        
        private int _VendorID1;
        
        private System.Nullable<System.DateTime> _PaymentDate;
        
        private string _InvoiceNumber;
        
        private string _OrderNumber;
        
        private string _Reference;
        
        private decimal _Amount;
        
        private decimal _GST;
        
        private string _Description;
        
        private string _Comments1;
        
        private string _PurchaseType;
        
        private string _ExpenseType;
        
        private int _AssetID;
        
        private System.Nullable<System.Int32> _VendorID2;
        
        private System.Nullable<System.Int32> _VendorDetailsID1;
        
        private string _Location;
        
        private string _Model;
        
        private string _SerialNumber;
        
        private string _Manufacturer;
        
        private string _ManufacturerWebSite;
        
        private string _Category;
        
        private System.Nullable<System.Int32> _Units;
        
        private string _Status;
        
        private string _Description1;
        
        private string _Details;
        
        private string _Comments2;
        
        private System.Nullable<System.Decimal> _Amount1;
        
        #region Extensibility Method Definitions
        /// <summary>
        /// On create data entity.
        /// </summary>
		partial void OnCreated();

        /// <summary>
        /// On load data entity.
        /// </summary>
		partial void OnLoaded();

		#endregion
        
        /// <summary>
        /// Default constructor.
        /// </summary>
        public GetVendorVendorDetailsBetweenDateCategoryAssetResult()
        {
            OnCreated();
        }
        
        #region Public Column Properties
        /// <summary>
        /// Gets sets, the vendorid property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the vendorid property for the object.")]
        [DataMemberAttribute(Name = "VendorID")]
        [XmlElementAttribute(ElementName = "VendorID", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public int VendorID
        {
            get
            {
                return this._VendorID;
            }
            set
            {
                if ((this._VendorID != value))
                {
                    this._VendorID = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the companyname property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the companyname property for the object.")]
        [DataMemberAttribute(Name = "CompanyName")]
        [XmlElementAttribute(ElementName = "CompanyName", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                if ((this._CompanyName != value))
                {
                    this._CompanyName = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the firstname property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the firstname property for the object.")]
        [DataMemberAttribute(Name = "Firstname")]
        [XmlElementAttribute(ElementName = "Firstname", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Firstname
        {
            get
            {
                return this._Firstname;
            }
            set
            {
                if ((this._Firstname != value))
                {
                    this._Firstname = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the surname property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the surname property for the object.")]
        [DataMemberAttribute(Name = "Surname")]
        [XmlElementAttribute(ElementName = "Surname", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                if ((this._Surname != value))
                {
                    this._Surname = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the address property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the address property for the object.")]
        [DataMemberAttribute(Name = "Address")]
        [XmlElementAttribute(ElementName = "Address", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                if ((this._Address != value))
                {
                    this._Address = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the suburb property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the suburb property for the object.")]
        [DataMemberAttribute(Name = "Suburb")]
        [XmlElementAttribute(ElementName = "Suburb", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Suburb
        {
            get
            {
                return this._Suburb;
            }
            set
            {
                if ((this._Suburb != value))
                {
                    this._Suburb = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the state property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the state property for the object.")]
        [DataMemberAttribute(Name = "State")]
        [XmlElementAttribute(ElementName = "State", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                if ((this._State != value))
                {
                    this._State = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the postcode property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the postcode property for the object.")]
        [DataMemberAttribute(Name = "Postcode")]
        [XmlElementAttribute(ElementName = "Postcode", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Postcode
        {
            get
            {
                return this._Postcode;
            }
            set
            {
                if ((this._Postcode != value))
                {
                    this._Postcode = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the phonenumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the phonenumber property for the object.")]
        [DataMemberAttribute(Name = "PhoneNumber")]
        [XmlElementAttribute(ElementName = "PhoneNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string PhoneNumber
        {
            get
            {
                return this._PhoneNumber;
            }
            set
            {
                if ((this._PhoneNumber != value))
                {
                    this._PhoneNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the faxnumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the faxnumber property for the object.")]
        [DataMemberAttribute(Name = "FaxNumber")]
        [XmlElementAttribute(ElementName = "FaxNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string FaxNumber
        {
            get
            {
                return this._FaxNumber;
            }
            set
            {
                if ((this._FaxNumber != value))
                {
                    this._FaxNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the mobilenumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the mobilenumber property for the object.")]
        [DataMemberAttribute(Name = "MobileNumber")]
        [XmlElementAttribute(ElementName = "MobileNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string MobileNumber
        {
            get
            {
                return this._MobileNumber;
            }
            set
            {
                if ((this._MobileNumber != value))
                {
                    this._MobileNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the emailaddress property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the emailaddress property for the object.")]
        [DataMemberAttribute(Name = "EmailAddress")]
        [XmlElementAttribute(ElementName = "EmailAddress", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                if ((this._EmailAddress != value))
                {
                    this._EmailAddress = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the website property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the website property for the object.")]
        [DataMemberAttribute(Name = "WebSite")]
        [XmlElementAttribute(ElementName = "WebSite", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string WebSite
        {
            get
            {
                return this._WebSite;
            }
            set
            {
                if ((this._WebSite != value))
                {
                    this._WebSite = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the abn property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the abn property for the object.")]
        [DataMemberAttribute(Name = "ABN")]
        [XmlElementAttribute(ElementName = "ABN", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string ABN
        {
            get
            {
                return this._ABN;
            }
            set
            {
                if ((this._ABN != value))
                {
                    this._ABN = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the postaladdress property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the postaladdress property for the object.")]
        [DataMemberAttribute(Name = "PostalAddress")]
        [XmlElementAttribute(ElementName = "PostalAddress", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string PostalAddress
        {
            get
            {
                return this._PostalAddress;
            }
            set
            {
                if ((this._PostalAddress != value))
                {
                    this._PostalAddress = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the postalsuburb property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the postalsuburb property for the object.")]
        [DataMemberAttribute(Name = "PostalSuburb")]
        [XmlElementAttribute(ElementName = "PostalSuburb", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string PostalSuburb
        {
            get
            {
                return this._PostalSuburb;
            }
            set
            {
                if ((this._PostalSuburb != value))
                {
                    this._PostalSuburb = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the postalstate property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the postalstate property for the object.")]
        [DataMemberAttribute(Name = "PostalState")]
        [XmlElementAttribute(ElementName = "PostalState", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string PostalState
        {
            get
            {
                return this._PostalState;
            }
            set
            {
                if ((this._PostalState != value))
                {
                    this._PostalState = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the postalpostcode property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the postalpostcode property for the object.")]
        [DataMemberAttribute(Name = "PostalPostcode")]
        [XmlElementAttribute(ElementName = "PostalPostcode", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string PostalPostcode
        {
            get
            {
                return this._PostalPostcode;
            }
            set
            {
                if ((this._PostalPostcode != value))
                {
                    this._PostalPostcode = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the comments property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the comments property for the object.")]
        [DataMemberAttribute(Name = "Comments")]
        [XmlElementAttribute(ElementName = "Comments", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                if ((this._Comments != value))
                {
                    this._Comments = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the vendordetailsid property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the vendordetailsid property for the object.")]
        [DataMemberAttribute(Name = "VendorDetailsID")]
        [XmlElementAttribute(ElementName = "VendorDetailsID", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public int VendorDetailsID
        {
            get
            {
                return this._VendorDetailsID;
            }
            set
            {
                if ((this._VendorDetailsID != value))
                {
                    this._VendorDetailsID = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the vendorid1 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the vendorid1 property for the object.")]
        [DataMemberAttribute(Name = "VendorID1")]
        [XmlElementAttribute(ElementName = "VendorID1", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public int VendorID1
        {
            get
            {
                return this._VendorID1;
            }
            set
            {
                if ((this._VendorID1 != value))
                {
                    this._VendorID1 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the paymentdate property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the paymentdate property for the object.")]
        [DataMemberAttribute(Name = "PaymentDate")]
        [XmlElementAttribute(ElementName = "PaymentDate", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> PaymentDate
        {
            get
            {
                return this._PaymentDate;
            }
            set
            {
                if ((this._PaymentDate != value))
                {
                    this._PaymentDate = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the invoicenumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the invoicenumber property for the object.")]
        [DataMemberAttribute(Name = "InvoiceNumber")]
        [XmlElementAttribute(ElementName = "InvoiceNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string InvoiceNumber
        {
            get
            {
                return this._InvoiceNumber;
            }
            set
            {
                if ((this._InvoiceNumber != value))
                {
                    this._InvoiceNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the ordernumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the ordernumber property for the object.")]
        [DataMemberAttribute(Name = "OrderNumber")]
        [XmlElementAttribute(ElementName = "OrderNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string OrderNumber
        {
            get
            {
                return this._OrderNumber;
            }
            set
            {
                if ((this._OrderNumber != value))
                {
                    this._OrderNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the reference property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the reference property for the object.")]
        [DataMemberAttribute(Name = "Reference")]
        [XmlElementAttribute(ElementName = "Reference", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Reference
        {
            get
            {
                return this._Reference;
            }
            set
            {
                if ((this._Reference != value))
                {
                    this._Reference = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the amount property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the amount property for the object.")]
        [DataMemberAttribute(Name = "Amount")]
        [XmlElementAttribute(ElementName = "Amount", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public decimal Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                if ((this._Amount != value))
                {
                    this._Amount = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the gst property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the gst property for the object.")]
        [DataMemberAttribute(Name = "GST")]
        [XmlElementAttribute(ElementName = "GST", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public decimal GST
        {
            get
            {
                return this._GST;
            }
            set
            {
                if ((this._GST != value))
                {
                    this._GST = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the description property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the description property for the object.")]
        [DataMemberAttribute(Name = "Description")]
        [XmlElementAttribute(ElementName = "Description", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this._Description != value))
                {
                    this._Description = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the comments1 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the comments1 property for the object.")]
        [DataMemberAttribute(Name = "Comments1")]
        [XmlElementAttribute(ElementName = "Comments1", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Comments1
        {
            get
            {
                return this._Comments1;
            }
            set
            {
                if ((this._Comments1 != value))
                {
                    this._Comments1 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the purchasetype property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the purchasetype property for the object.")]
        [DataMemberAttribute(Name = "PurchaseType")]
        [XmlElementAttribute(ElementName = "PurchaseType", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public string PurchaseType
        {
            get
            {
                return this._PurchaseType;
            }
            set
            {
                if ((this._PurchaseType != value))
                {
                    this._PurchaseType = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the expensetype property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the expensetype property for the object.")]
        [DataMemberAttribute(Name = "ExpenseType")]
        [XmlElementAttribute(ElementName = "ExpenseType", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public string ExpenseType
        {
            get
            {
                return this._ExpenseType;
            }
            set
            {
                if ((this._ExpenseType != value))
                {
                    this._ExpenseType = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the assetid property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the assetid property for the object.")]
        [DataMemberAttribute(Name = "AssetID")]
        [XmlElementAttribute(ElementName = "AssetID", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public int AssetID
        {
            get
            {
                return this._AssetID;
            }
            set
            {
                if ((this._AssetID != value))
                {
                    this._AssetID = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the vendorid2 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the vendorid2 property for the object.")]
        [DataMemberAttribute(Name = "VendorID2")]
        [XmlElementAttribute(ElementName = "VendorID2", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.Int32> VendorID2
        {
            get
            {
                return this._VendorID2;
            }
            set
            {
                if ((this._VendorID2 != value))
                {
                    this._VendorID2 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the vendordetailsid1 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the vendordetailsid1 property for the object.")]
        [DataMemberAttribute(Name = "VendorDetailsID1")]
        [XmlElementAttribute(ElementName = "VendorDetailsID1", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.Int32> VendorDetailsID1
        {
            get
            {
                return this._VendorDetailsID1;
            }
            set
            {
                if ((this._VendorDetailsID1 != value))
                {
                    this._VendorDetailsID1 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the location property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the location property for the object.")]
        [DataMemberAttribute(Name = "Location")]
        [XmlElementAttribute(ElementName = "Location", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                if ((this._Location != value))
                {
                    this._Location = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the model property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the model property for the object.")]
        [DataMemberAttribute(Name = "Model")]
        [XmlElementAttribute(ElementName = "Model", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                if ((this._Model != value))
                {
                    this._Model = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the serialnumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the serialnumber property for the object.")]
        [DataMemberAttribute(Name = "SerialNumber")]
        [XmlElementAttribute(ElementName = "SerialNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                if ((this._SerialNumber != value))
                {
                    this._SerialNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the manufacturer property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the manufacturer property for the object.")]
        [DataMemberAttribute(Name = "Manufacturer")]
        [XmlElementAttribute(ElementName = "Manufacturer", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Manufacturer
        {
            get
            {
                return this._Manufacturer;
            }
            set
            {
                if ((this._Manufacturer != value))
                {
                    this._Manufacturer = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the manufacturerwebsite property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the manufacturerwebsite property for the object.")]
        [DataMemberAttribute(Name = "ManufacturerWebSite")]
        [XmlElementAttribute(ElementName = "ManufacturerWebSite", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string ManufacturerWebSite
        {
            get
            {
                return this._ManufacturerWebSite;
            }
            set
            {
                if ((this._ManufacturerWebSite != value))
                {
                    this._ManufacturerWebSite = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the category property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the category property for the object.")]
        [DataMemberAttribute(Name = "Category")]
        [XmlElementAttribute(ElementName = "Category", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                if ((this._Category != value))
                {
                    this._Category = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the units property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the units property for the object.")]
        [DataMemberAttribute(Name = "Units")]
        [XmlElementAttribute(ElementName = "Units", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.Int32> Units
        {
            get
            {
                return this._Units;
            }
            set
            {
                if ((this._Units != value))
                {
                    this._Units = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the status property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the status property for the object.")]
        [DataMemberAttribute(Name = "Status")]
        [XmlElementAttribute(ElementName = "Status", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                if ((this._Status != value))
                {
                    this._Status = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the description1 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the description1 property for the object.")]
        [DataMemberAttribute(Name = "Description1")]
        [XmlElementAttribute(ElementName = "Description1", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Description1
        {
            get
            {
                return this._Description1;
            }
            set
            {
                if ((this._Description1 != value))
                {
                    this._Description1 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the details property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the details property for the object.")]
        [DataMemberAttribute(Name = "Details")]
        [XmlElementAttribute(ElementName = "Details", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Details
        {
            get
            {
                return this._Details;
            }
            set
            {
                if ((this._Details != value))
                {
                    this._Details = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the comments2 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the comments2 property for the object.")]
        [DataMemberAttribute(Name = "Comments2")]
        [XmlElementAttribute(ElementName = "Comments2", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Comments2
        {
            get
            {
                return this._Comments2;
            }
            set
            {
                if ((this._Comments2 != value))
                {
                    this._Comments2 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the amount1 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the amount1 property for the object.")]
        [DataMemberAttribute(Name = "Amount1")]
        [XmlElementAttribute(ElementName = "Amount1", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.Decimal> Amount1
        {
            get
            {
                return this._Amount1;
            }
            set
            {
                if ((this._Amount1 != value))
                {
                    this._Amount1 = value;
                }
            }
        }
        #endregion
        
        /// <summary>
        /// Create a new getvendorvendordetailsbetweendatecategoryassetresult data entity.
        /// </summary>
        /// <param name="vendorID">Initial value of VendorID.</param>
        /// <param name="companyName">Initial value of CompanyName.</param>
        /// <param name="vendorDetailsID">Initial value of VendorDetailsID.</param>
        /// <param name="vendorID1">Initial value of VendorID1.</param>
        /// <param name="amount">Initial value of Amount.</param>
        /// <param name="gST">Initial value of GST.</param>
        /// <param name="purchaseType">Initial value of PurchaseType.</param>
        /// <param name="expenseType">Initial value of ExpenseType.</param>
        /// <param name="assetID">Initial value of AssetID.</param>
        /// <returns>The Data.Extended.GetVendorVendorDetailsBetweenDateCategoryAssetResult entity.</returns>
        public static Data.Extended.GetVendorVendorDetailsBetweenDateCategoryAssetResult CreateGetVendorVendorDetailsBetweenDateCategoryAssetResult(int vendorID, string companyName, int vendorDetailsID, int vendorID1, decimal amount, decimal gST, string purchaseType, string expenseType, int assetID)
        {
            Data.Extended.GetVendorVendorDetailsBetweenDateCategoryAssetResult getVendorVendorDetailsBetweenDateCategoryAssetResult = new Data.Extended.GetVendorVendorDetailsBetweenDateCategoryAssetResult();
            getVendorVendorDetailsBetweenDateCategoryAssetResult.VendorID = vendorID;
            getVendorVendorDetailsBetweenDateCategoryAssetResult.CompanyName = companyName;
            getVendorVendorDetailsBetweenDateCategoryAssetResult.VendorDetailsID = vendorDetailsID;
            getVendorVendorDetailsBetweenDateCategoryAssetResult.VendorID1 = vendorID1;
            getVendorVendorDetailsBetweenDateCategoryAssetResult.Amount = amount;
            getVendorVendorDetailsBetweenDateCategoryAssetResult.GST = gST;
            getVendorVendorDetailsBetweenDateCategoryAssetResult.PurchaseType = purchaseType;
            getVendorVendorDetailsBetweenDateCategoryAssetResult.ExpenseType = expenseType;
            getVendorVendorDetailsBetweenDateCategoryAssetResult.AssetID = assetID;
            return getVendorVendorDetailsBetweenDateCategoryAssetResult;
        }
    }
    #endregion
    
    #region GetVendorVendorDetailsCategoryAssetResult Data Entity Type
    /// <summary>
    /// The getvendorvendordetailscategoryassetresult data object class.
    /// </summary>
    [DataContractAttribute(Name = "GetVendorVendorDetailsCategoryAssetResult", IsReference = true)]
    [SerializableAttribute()]
    [KnownTypeAttribute(typeof(DataBase))]
    public partial class GetVendorVendorDetailsCategoryAssetResult : DataBase
    {
        
        private int _VendorID;
        
        private string _CompanyName;
        
        private string _Firstname;
        
        private string _Surname;
        
        private string _Address;
        
        private string _Suburb;
        
        private string _State;
        
        private string _Postcode;
        
        private string _PhoneNumber;
        
        private string _FaxNumber;
        
        private string _MobileNumber;
        
        private string _EmailAddress;
        
        private string _WebSite;
        
        private string _ABN;
        
        private string _PostalAddress;
        
        private string _PostalSuburb;
        
        private string _PostalState;
        
        private string _PostalPostcode;
        
        private string _Comments;
        
        private int _VendorDetailsID;
        
        private int _VendorID1;
        
        private System.Nullable<System.DateTime> _PaymentDate;
        
        private string _InvoiceNumber;
        
        private string _OrderNumber;
        
        private string _Reference;
        
        private decimal _Amount;
        
        private decimal _GST;
        
        private string _Description;
        
        private string _Comments1;
        
        private string _PurchaseType;
        
        private string _ExpenseType;
        
        private int _AssetID;
        
        private System.Nullable<System.Int32> _VendorID2;
        
        private System.Nullable<System.Int32> _VendorDetailsID1;
        
        private string _Location;
        
        private string _Model;
        
        private string _SerialNumber;
        
        private string _Manufacturer;
        
        private string _ManufacturerWebSite;
        
        private string _Category;
        
        private System.Nullable<System.Int32> _Units;
        
        private string _Status;
        
        private string _Description1;
        
        private string _Details;
        
        private string _Comments2;
        
        private System.Nullable<System.Decimal> _Amount1;
        
        #region Extensibility Method Definitions
        /// <summary>
        /// On create data entity.
        /// </summary>
		partial void OnCreated();

        /// <summary>
        /// On load data entity.
        /// </summary>
		partial void OnLoaded();

		#endregion
        
        /// <summary>
        /// Default constructor.
        /// </summary>
        public GetVendorVendorDetailsCategoryAssetResult()
        {
            OnCreated();
        }
        
        #region Public Column Properties
        /// <summary>
        /// Gets sets, the vendorid property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the vendorid property for the object.")]
        [DataMemberAttribute(Name = "VendorID")]
        [XmlElementAttribute(ElementName = "VendorID", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public int VendorID
        {
            get
            {
                return this._VendorID;
            }
            set
            {
                if ((this._VendorID != value))
                {
                    this._VendorID = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the companyname property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the companyname property for the object.")]
        [DataMemberAttribute(Name = "CompanyName")]
        [XmlElementAttribute(ElementName = "CompanyName", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                if ((this._CompanyName != value))
                {
                    this._CompanyName = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the firstname property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the firstname property for the object.")]
        [DataMemberAttribute(Name = "Firstname")]
        [XmlElementAttribute(ElementName = "Firstname", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Firstname
        {
            get
            {
                return this._Firstname;
            }
            set
            {
                if ((this._Firstname != value))
                {
                    this._Firstname = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the surname property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the surname property for the object.")]
        [DataMemberAttribute(Name = "Surname")]
        [XmlElementAttribute(ElementName = "Surname", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                if ((this._Surname != value))
                {
                    this._Surname = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the address property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the address property for the object.")]
        [DataMemberAttribute(Name = "Address")]
        [XmlElementAttribute(ElementName = "Address", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                if ((this._Address != value))
                {
                    this._Address = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the suburb property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the suburb property for the object.")]
        [DataMemberAttribute(Name = "Suburb")]
        [XmlElementAttribute(ElementName = "Suburb", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Suburb
        {
            get
            {
                return this._Suburb;
            }
            set
            {
                if ((this._Suburb != value))
                {
                    this._Suburb = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the state property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the state property for the object.")]
        [DataMemberAttribute(Name = "State")]
        [XmlElementAttribute(ElementName = "State", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                if ((this._State != value))
                {
                    this._State = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the postcode property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the postcode property for the object.")]
        [DataMemberAttribute(Name = "Postcode")]
        [XmlElementAttribute(ElementName = "Postcode", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Postcode
        {
            get
            {
                return this._Postcode;
            }
            set
            {
                if ((this._Postcode != value))
                {
                    this._Postcode = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the phonenumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the phonenumber property for the object.")]
        [DataMemberAttribute(Name = "PhoneNumber")]
        [XmlElementAttribute(ElementName = "PhoneNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string PhoneNumber
        {
            get
            {
                return this._PhoneNumber;
            }
            set
            {
                if ((this._PhoneNumber != value))
                {
                    this._PhoneNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the faxnumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the faxnumber property for the object.")]
        [DataMemberAttribute(Name = "FaxNumber")]
        [XmlElementAttribute(ElementName = "FaxNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string FaxNumber
        {
            get
            {
                return this._FaxNumber;
            }
            set
            {
                if ((this._FaxNumber != value))
                {
                    this._FaxNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the mobilenumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the mobilenumber property for the object.")]
        [DataMemberAttribute(Name = "MobileNumber")]
        [XmlElementAttribute(ElementName = "MobileNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string MobileNumber
        {
            get
            {
                return this._MobileNumber;
            }
            set
            {
                if ((this._MobileNumber != value))
                {
                    this._MobileNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the emailaddress property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the emailaddress property for the object.")]
        [DataMemberAttribute(Name = "EmailAddress")]
        [XmlElementAttribute(ElementName = "EmailAddress", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                if ((this._EmailAddress != value))
                {
                    this._EmailAddress = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the website property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the website property for the object.")]
        [DataMemberAttribute(Name = "WebSite")]
        [XmlElementAttribute(ElementName = "WebSite", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string WebSite
        {
            get
            {
                return this._WebSite;
            }
            set
            {
                if ((this._WebSite != value))
                {
                    this._WebSite = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the abn property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the abn property for the object.")]
        [DataMemberAttribute(Name = "ABN")]
        [XmlElementAttribute(ElementName = "ABN", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string ABN
        {
            get
            {
                return this._ABN;
            }
            set
            {
                if ((this._ABN != value))
                {
                    this._ABN = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the postaladdress property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the postaladdress property for the object.")]
        [DataMemberAttribute(Name = "PostalAddress")]
        [XmlElementAttribute(ElementName = "PostalAddress", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string PostalAddress
        {
            get
            {
                return this._PostalAddress;
            }
            set
            {
                if ((this._PostalAddress != value))
                {
                    this._PostalAddress = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the postalsuburb property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the postalsuburb property for the object.")]
        [DataMemberAttribute(Name = "PostalSuburb")]
        [XmlElementAttribute(ElementName = "PostalSuburb", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string PostalSuburb
        {
            get
            {
                return this._PostalSuburb;
            }
            set
            {
                if ((this._PostalSuburb != value))
                {
                    this._PostalSuburb = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the postalstate property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the postalstate property for the object.")]
        [DataMemberAttribute(Name = "PostalState")]
        [XmlElementAttribute(ElementName = "PostalState", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string PostalState
        {
            get
            {
                return this._PostalState;
            }
            set
            {
                if ((this._PostalState != value))
                {
                    this._PostalState = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the postalpostcode property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the postalpostcode property for the object.")]
        [DataMemberAttribute(Name = "PostalPostcode")]
        [XmlElementAttribute(ElementName = "PostalPostcode", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string PostalPostcode
        {
            get
            {
                return this._PostalPostcode;
            }
            set
            {
                if ((this._PostalPostcode != value))
                {
                    this._PostalPostcode = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the comments property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the comments property for the object.")]
        [DataMemberAttribute(Name = "Comments")]
        [XmlElementAttribute(ElementName = "Comments", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                if ((this._Comments != value))
                {
                    this._Comments = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the vendordetailsid property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the vendordetailsid property for the object.")]
        [DataMemberAttribute(Name = "VendorDetailsID")]
        [XmlElementAttribute(ElementName = "VendorDetailsID", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public int VendorDetailsID
        {
            get
            {
                return this._VendorDetailsID;
            }
            set
            {
                if ((this._VendorDetailsID != value))
                {
                    this._VendorDetailsID = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the vendorid1 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the vendorid1 property for the object.")]
        [DataMemberAttribute(Name = "VendorID1")]
        [XmlElementAttribute(ElementName = "VendorID1", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public int VendorID1
        {
            get
            {
                return this._VendorID1;
            }
            set
            {
                if ((this._VendorID1 != value))
                {
                    this._VendorID1 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the paymentdate property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the paymentdate property for the object.")]
        [DataMemberAttribute(Name = "PaymentDate")]
        [XmlElementAttribute(ElementName = "PaymentDate", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> PaymentDate
        {
            get
            {
                return this._PaymentDate;
            }
            set
            {
                if ((this._PaymentDate != value))
                {
                    this._PaymentDate = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the invoicenumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the invoicenumber property for the object.")]
        [DataMemberAttribute(Name = "InvoiceNumber")]
        [XmlElementAttribute(ElementName = "InvoiceNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string InvoiceNumber
        {
            get
            {
                return this._InvoiceNumber;
            }
            set
            {
                if ((this._InvoiceNumber != value))
                {
                    this._InvoiceNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the ordernumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the ordernumber property for the object.")]
        [DataMemberAttribute(Name = "OrderNumber")]
        [XmlElementAttribute(ElementName = "OrderNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string OrderNumber
        {
            get
            {
                return this._OrderNumber;
            }
            set
            {
                if ((this._OrderNumber != value))
                {
                    this._OrderNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the reference property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the reference property for the object.")]
        [DataMemberAttribute(Name = "Reference")]
        [XmlElementAttribute(ElementName = "Reference", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Reference
        {
            get
            {
                return this._Reference;
            }
            set
            {
                if ((this._Reference != value))
                {
                    this._Reference = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the amount property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the amount property for the object.")]
        [DataMemberAttribute(Name = "Amount")]
        [XmlElementAttribute(ElementName = "Amount", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public decimal Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                if ((this._Amount != value))
                {
                    this._Amount = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the gst property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the gst property for the object.")]
        [DataMemberAttribute(Name = "GST")]
        [XmlElementAttribute(ElementName = "GST", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public decimal GST
        {
            get
            {
                return this._GST;
            }
            set
            {
                if ((this._GST != value))
                {
                    this._GST = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the description property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the description property for the object.")]
        [DataMemberAttribute(Name = "Description")]
        [XmlElementAttribute(ElementName = "Description", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this._Description != value))
                {
                    this._Description = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the comments1 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the comments1 property for the object.")]
        [DataMemberAttribute(Name = "Comments1")]
        [XmlElementAttribute(ElementName = "Comments1", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Comments1
        {
            get
            {
                return this._Comments1;
            }
            set
            {
                if ((this._Comments1 != value))
                {
                    this._Comments1 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the purchasetype property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the purchasetype property for the object.")]
        [DataMemberAttribute(Name = "PurchaseType")]
        [XmlElementAttribute(ElementName = "PurchaseType", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public string PurchaseType
        {
            get
            {
                return this._PurchaseType;
            }
            set
            {
                if ((this._PurchaseType != value))
                {
                    this._PurchaseType = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the expensetype property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the expensetype property for the object.")]
        [DataMemberAttribute(Name = "ExpenseType")]
        [XmlElementAttribute(ElementName = "ExpenseType", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public string ExpenseType
        {
            get
            {
                return this._ExpenseType;
            }
            set
            {
                if ((this._ExpenseType != value))
                {
                    this._ExpenseType = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the assetid property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the assetid property for the object.")]
        [DataMemberAttribute(Name = "AssetID")]
        [XmlElementAttribute(ElementName = "AssetID", IsNullable = false)]
        [SoapElementAttribute(IsNullable = false)]
        public int AssetID
        {
            get
            {
                return this._AssetID;
            }
            set
            {
                if ((this._AssetID != value))
                {
                    this._AssetID = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the vendorid2 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the vendorid2 property for the object.")]
        [DataMemberAttribute(Name = "VendorID2")]
        [XmlElementAttribute(ElementName = "VendorID2", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.Int32> VendorID2
        {
            get
            {
                return this._VendorID2;
            }
            set
            {
                if ((this._VendorID2 != value))
                {
                    this._VendorID2 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the vendordetailsid1 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the vendordetailsid1 property for the object.")]
        [DataMemberAttribute(Name = "VendorDetailsID1")]
        [XmlElementAttribute(ElementName = "VendorDetailsID1", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.Int32> VendorDetailsID1
        {
            get
            {
                return this._VendorDetailsID1;
            }
            set
            {
                if ((this._VendorDetailsID1 != value))
                {
                    this._VendorDetailsID1 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the location property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the location property for the object.")]
        [DataMemberAttribute(Name = "Location")]
        [XmlElementAttribute(ElementName = "Location", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                if ((this._Location != value))
                {
                    this._Location = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the model property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the model property for the object.")]
        [DataMemberAttribute(Name = "Model")]
        [XmlElementAttribute(ElementName = "Model", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                if ((this._Model != value))
                {
                    this._Model = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the serialnumber property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the serialnumber property for the object.")]
        [DataMemberAttribute(Name = "SerialNumber")]
        [XmlElementAttribute(ElementName = "SerialNumber", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                if ((this._SerialNumber != value))
                {
                    this._SerialNumber = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the manufacturer property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the manufacturer property for the object.")]
        [DataMemberAttribute(Name = "Manufacturer")]
        [XmlElementAttribute(ElementName = "Manufacturer", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Manufacturer
        {
            get
            {
                return this._Manufacturer;
            }
            set
            {
                if ((this._Manufacturer != value))
                {
                    this._Manufacturer = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the manufacturerwebsite property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the manufacturerwebsite property for the object.")]
        [DataMemberAttribute(Name = "ManufacturerWebSite")]
        [XmlElementAttribute(ElementName = "ManufacturerWebSite", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string ManufacturerWebSite
        {
            get
            {
                return this._ManufacturerWebSite;
            }
            set
            {
                if ((this._ManufacturerWebSite != value))
                {
                    this._ManufacturerWebSite = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the category property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the category property for the object.")]
        [DataMemberAttribute(Name = "Category")]
        [XmlElementAttribute(ElementName = "Category", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                if ((this._Category != value))
                {
                    this._Category = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the units property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the units property for the object.")]
        [DataMemberAttribute(Name = "Units")]
        [XmlElementAttribute(ElementName = "Units", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.Int32> Units
        {
            get
            {
                return this._Units;
            }
            set
            {
                if ((this._Units != value))
                {
                    this._Units = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the status property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the status property for the object.")]
        [DataMemberAttribute(Name = "Status")]
        [XmlElementAttribute(ElementName = "Status", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                if ((this._Status != value))
                {
                    this._Status = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the description1 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the description1 property for the object.")]
        [DataMemberAttribute(Name = "Description1")]
        [XmlElementAttribute(ElementName = "Description1", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Description1
        {
            get
            {
                return this._Description1;
            }
            set
            {
                if ((this._Description1 != value))
                {
                    this._Description1 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the details property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the details property for the object.")]
        [DataMemberAttribute(Name = "Details")]
        [XmlElementAttribute(ElementName = "Details", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Details
        {
            get
            {
                return this._Details;
            }
            set
            {
                if ((this._Details != value))
                {
                    this._Details = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the comments2 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the comments2 property for the object.")]
        [DataMemberAttribute(Name = "Comments2")]
        [XmlElementAttribute(ElementName = "Comments2", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public string Comments2
        {
            get
            {
                return this._Comments2;
            }
            set
            {
                if ((this._Comments2 != value))
                {
                    this._Comments2 = value;
                }
            }
        }
        
        /// <summary>
        /// Gets sets, the amount1 property for the object.
        /// </summary>
        [CategoryAttribute("Column")]
        [DescriptionAttribute("Gets sets, the amount1 property for the object.")]
        [DataMemberAttribute(Name = "Amount1")]
        [XmlElementAttribute(ElementName = "Amount1", IsNullable = true)]
        [SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.Decimal> Amount1
        {
            get
            {
                return this._Amount1;
            }
            set
            {
                if ((this._Amount1 != value))
                {
                    this._Amount1 = value;
                }
            }
        }
        #endregion
        
        /// <summary>
        /// Create a new getvendorvendordetailscategoryassetresult data entity.
        /// </summary>
        /// <param name="vendorID">Initial value of VendorID.</param>
        /// <param name="companyName">Initial value of CompanyName.</param>
        /// <param name="vendorDetailsID">Initial value of VendorDetailsID.</param>
        /// <param name="vendorID1">Initial value of VendorID1.</param>
        /// <param name="amount">Initial value of Amount.</param>
        /// <param name="gST">Initial value of GST.</param>
        /// <param name="purchaseType">Initial value of PurchaseType.</param>
        /// <param name="expenseType">Initial value of ExpenseType.</param>
        /// <param name="assetID">Initial value of AssetID.</param>
        /// <returns>The Data.Extended.GetVendorVendorDetailsCategoryAssetResult entity.</returns>
        public static Data.Extended.GetVendorVendorDetailsCategoryAssetResult CreateGetVendorVendorDetailsCategoryAssetResult(int vendorID, string companyName, int vendorDetailsID, int vendorID1, decimal amount, decimal gST, string purchaseType, string expenseType, int assetID)
        {
            Data.Extended.GetVendorVendorDetailsCategoryAssetResult getVendorVendorDetailsCategoryAssetResult = new Data.Extended.GetVendorVendorDetailsCategoryAssetResult();
            getVendorVendorDetailsCategoryAssetResult.VendorID = vendorID;
            getVendorVendorDetailsCategoryAssetResult.CompanyName = companyName;
            getVendorVendorDetailsCategoryAssetResult.VendorDetailsID = vendorDetailsID;
            getVendorVendorDetailsCategoryAssetResult.VendorID1 = vendorID1;
            getVendorVendorDetailsCategoryAssetResult.Amount = amount;
            getVendorVendorDetailsCategoryAssetResult.GST = gST;
            getVendorVendorDetailsCategoryAssetResult.PurchaseType = purchaseType;
            getVendorVendorDetailsCategoryAssetResult.ExpenseType = expenseType;
            getVendorVendorDetailsCategoryAssetResult.AssetID = assetID;
            return getVendorVendorDetailsCategoryAssetResult;
        }
    }
    #endregion
}

#pragma warning restore 169
