// Warning 169 (Disables the 'Never used' warning)
#pragma warning disable 169
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.Logic.NequeoCompany.Company
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	using Nequeo.Data.Control;
	using Nequeo.DataAccess.NequeoCompany;
	using Nequeo.Report;
	using Nequeo.Report.NequeoCompany;
	using Nequeo.Report.Common;

	#region Company report extender
    /// <summary>
    /// The Company report extender.
    /// </summary>
    public partial class ReportCompanyExtender : Nequeo.Report.NequeoCompany.Company.Companies
    {
	}
    #endregion
}
#pragma warning restore 169