
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.DataAccess.ApplicationLogin.Linq.Extension
{
    using System;
    using System.Text;
    using System.Data;
    using System.Threading;
    using System.Diagnostics;
    using System.Data.SqlClient;
    using System.Data.OleDb;
    using System.Data.Odbc;
    using System.Collections;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Data.Linq;
    using System.Data.Linq.SqlClient;
    using System.Data.Linq.Mapping;
    using Nequeo.Data.Base.Exception;
    using Nequeo.Data.DataAccess.Control.Generic;
    using Nequeo.Data.Enumeration;
    using Nequeo.Data.Controller.Custom;
    using Nequeo.Data.Controller.Extension;
    using Linq = Nequeo.DataAccess.ApplicationLogin.Linq;
    
    
    /// <summary>
    /// The data access context replica object class.
    /// </summary>
    public partial class Extension : Disposable, IDisposable
    {
        
        /// <summary>
        /// Default constructor.
        /// </summary>
        public Extension()
        {
        }
        
        /// <summary>
        /// Gets, the screenaccess replica property for the object.
        /// </summary>
        public Linq.Replica.ScreenAccess ScreenAccess
        {
            get
            {
                return new Linq.Replica.ScreenAccess();
            }
        }
        
        /// <summary>
        /// Gets, the tabletype replica property for the object.
        /// </summary>
        public Linq.Replica.TableType TableType
        {
            get
            {
                return new Linq.Replica.TableType();
            }
        }
        
        /// <summary>
        /// Gets, the applicationuser replica property for the object.
        /// </summary>
        public Linq.Replica.ApplicationUser ApplicationUser
        {
            get
            {
                return new Linq.Replica.ApplicationUser();
            }
        }
        
        /// <summary>
        /// Gets, the state replica property for the object.
        /// </summary>
        public Linq.Replica.State State
        {
            get
            {
                return new Linq.Replica.State();
            }
        }
        
        /// <summary>
        /// Gets, the statetimezone replica property for the object.
        /// </summary>
        public Linq.Replica.StateTimeZone StateTimeZone
        {
            get
            {
                return new Linq.Replica.StateTimeZone();
            }
        }
        
        /// <summary>
        /// Gets, the country replica property for the object.
        /// </summary>
        public Linq.Replica.Country Country
        {
            get
            {
                return new Linq.Replica.Country();
            }
        }
        
        /// <summary>
        /// Gets, the useraddress replica property for the object.
        /// </summary>
        public Linq.Replica.UserAddress UserAddress
        {
            get
            {
                return new Linq.Replica.UserAddress();
            }
        }
        
        /// <summary>
        /// Gets, the user replica property for the object.
        /// </summary>
        public Linq.Replica.User User
        {
            get
            {
                return new Linq.Replica.User();
            }
        }
        
        /// <summary>
        /// Gets, the internationaltimezone replica property for the object.
        /// </summary>
        public Linq.Replica.InternationalTimeZone InternationalTimeZone
        {
            get
            {
                return new Linq.Replica.InternationalTimeZone();
            }
        }
        
        /// <summary>
        /// Gets, the errorlog replica property for the object.
        /// </summary>
        public Linq.Replica.ErrorLog ErrorLog
        {
            get
            {
                return new Linq.Replica.ErrorLog();
            }
        }
        
        /// <summary>
        /// Gets, the changelog replica property for the object.
        /// </summary>
        public Linq.Replica.ChangeLog ChangeLog
        {
            get
            {
                return new Linq.Replica.ChangeLog();
            }
        }
        
        /// <summary>
        /// Gets, the loginhistory replica property for the object.
        /// </summary>
        public Linq.Replica.LoginHistory LoginHistory
        {
            get
            {
                return new Linq.Replica.LoginHistory();
            }
        }
        
        /// <summary>
        /// Gets, the language replica property for the object.
        /// </summary>
        public Linq.Replica.Language Language
        {
            get
            {
                return new Linq.Replica.Language();
            }
        }
        
        /// <summary>
        /// Gets, the application replica property for the object.
        /// </summary>
        public Linq.Replica.Application Application
        {
            get
            {
                return new Linq.Replica.Application();
            }
        }
        
        /// <summary>
        /// Gets, the company replica property for the object.
        /// </summary>
        public Linq.Replica.Company Company
        {
            get
            {
                return new Linq.Replica.Company();
            }
        }
        
        /// <summary>
        /// Gets, the department replica property for the object.
        /// </summary>
        public Linq.Replica.Department Department
        {
            get
            {
                return new Linq.Replica.Department();
            }
        }
        
        /// <summary>
        /// Gets, the continent replica property for the object.
        /// </summary>
        public Linq.Replica.Continent Continent
        {
            get
            {
                return new Linq.Replica.Continent();
            }
        }
        
        /// <summary>
        /// Gets, the accesstype replica property for the object.
        /// </summary>
        public Linq.Replica.AccessType AccessType
        {
            get
            {
                return new Linq.Replica.AccessType();
            }
        }
        
        /// <summary>
        /// Gets, the roletype replica property for the object.
        /// </summary>
        public Linq.Replica.RoleType RoleType
        {
            get
            {
                return new Linq.Replica.RoleType();
            }
        }
        
        /// <summary>
        /// Gets, the screen replica property for the object.
        /// </summary>
        public Linq.Replica.Screen Screen
        {
            get
            {
                return new Linq.Replica.Screen();
            }
        }
    }
}
namespace Nequeo.DataAccess.ApplicationLogin.Linq
{
    using System;
    using System.Text;
    using System.Data;
    using System.Threading;
    using System.Diagnostics;
    using System.Data.SqlClient;
    using System.Data.OleDb;
    using System.Data.Odbc;
    using System.Collections;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Data.Linq;
    using System.Data.Linq.SqlClient;
    using System.Data.Linq.Mapping;
    using Nequeo.Data.Base.Exception;
    using Nequeo.Data.DataAccess.Control.Generic;
    using Nequeo.Data.Enumeration;
    using Nequeo.Data.Controller.Custom;
    using Nequeo.Data.Controller.Extension;
    
    
    /// <summary>
    /// The data access context object class.
    /// </summary>
    public partial class CommonDataContext
    {
        
        /// <summary>
        /// Gets, the extension class.
        /// </summary>
        public Linq.Extension.Extension Extension
        {
            get
            {
                return new Linq.Extension.Extension();
            }
        }
    }
}

