//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.Net.ServiceModel.MessageStream
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageStream.IStream")]
    public interface IStream {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBase/SendMessage", ReplyAction="http://tempuri.org/IMessageBase/SendMessageResponse")]
        Nequeo.Model.Message.InformationResponse SendMessage(Nequeo.Model.Message.InformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStream/MessageString", ReplyAction="http://tempuri.org/IStream/MessageStringResponse")]
        string MessageString(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStream/MessageByte", ReplyAction="http://tempuri.org/IStream/MessageByteResponse")]
        byte[] MessageByte(byte[] message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStreamChannel : Nequeo.Net.ServiceModel.MessageStream.IStream, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StreamClient : System.ServiceModel.ClientBase<Nequeo.Net.ServiceModel.MessageStream.IStream>, Nequeo.Net.ServiceModel.MessageStream.IStream
    {
        
        public StreamClient() {
        }
        
        public StreamClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StreamClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Nequeo.Model.Message.InformationResponse SendMessage(Nequeo.Model.Message.InformationRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public string MessageString(string message) {
            return base.Channel.MessageString(message);
        }
        
        public byte[] MessageByte(byte[] message) {
            return base.Channel.MessageByte(message);
        }
    }
}
