//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.DataAccess.NequeoCompany.Enum
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Data;
    using System.Threading;
    using System.Diagnostics;
    using System.Data.SqlClient;
    using System.Data.OleDb;
    using System.Data.Odbc;
    using System.Collections;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    
    
    #region EnumGstType Enum Type
    /// <summary>
    /// The enumerator enumgsttype object.
    /// </summary>
    [SerializableAttribute()]
    [DataContractAttribute()]
    public enum EnumGstType
    {
        
        /// <summary>
        /// The Included enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Included = 1,
        
        /// <summary>
        /// The Calculated enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Calculated = 2,
    }
    #endregion
}
