//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.DataAccess.NequeoCompany.Enum
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Data;
    using System.Threading;
    using System.Diagnostics;
    using System.Data.SqlClient;
    using System.Data.OleDb;
    using System.Data.Odbc;
    using System.Collections;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    
    
    #region EnumStateLongName Enum Type
    /// <summary>
    /// The enumerator enumstatelongname object.
    /// </summary>
    [SerializableAttribute()]
    [DataContractAttribute()]
    public enum EnumStateLongName
    {
        
        /// <summary>
        /// The New South Wales enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        NewSouthWales = 1,
        
        /// <summary>
        /// The Queensland enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Queensland = 2,
        
        /// <summary>
        /// The Australian Capital Territory enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        AustralianCapitalTerritory = 3,
        
        /// <summary>
        /// The Victoria enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Victoria = 4,
        
        /// <summary>
        /// The Tasmainia enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Tasmainia = 5,
        
        /// <summary>
        /// The South Australia enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        SouthAustralia = 6,
        
        /// <summary>
        /// The Western Australia enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        WesternAustralia = 7,
        
        /// <summary>
        /// The Northern Territory enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        NorthernTerritory = 8,
    }
    #endregion
}
