//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.DataAccess.NequeoCompany.Enum
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Data;
    using System.Threading;
    using System.Diagnostics;
    using System.Data.SqlClient;
    using System.Data.OleDb;
    using System.Data.Odbc;
    using System.Collections;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    
    
    #region EnumIncomeType Enum Type
    /// <summary>
    /// The enumerator enumincometype object.
    /// </summary>
    [SerializableAttribute()]
    [DataContractAttribute()]
    public enum EnumIncomeType
    {
        
        /// <summary>
        /// The Other Sales of Goods and Services enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        OtherSalesOfGoodsAndServices = 1,
        
        /// <summary>
        /// The Other Income enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        OtherIncome = 2,
        
        /// <summary>
        /// The Interest enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Interest = 3,
        
        /// <summary>
        /// The Payments Where ABN not Quoted enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        PaymentsWhereABNNotQuoted = 4,
        
        /// <summary>
        /// The Rent and Other Leasing and Hiring Income enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        RentAndOtherLeasingAndHiringIncome = 5,
        
        /// <summary>
        /// The Dividends enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        Dividends = 6,
        
        /// <summary>
        /// The Assessable Government Industry Payments enum value
        /// </summary>
        [EnumMemberAttribute()]
        [XmlEnumAttribute()]
        [SoapEnumAttribute()]
        AssessableGovernmentIndustryPayments = 7,
    }
    #endregion
}
