// Warning 169 (Disables the 'Never used' warning)
#pragma warning disable 169
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.Net.ActiveDirectory
{
    using System;
    using System.Text;
    using System.Data;
    using System.Threading;
    using System.Diagnostics;
    using System.Data.SqlClient;
    using System.Data.OleDb;
    using System.Data.Odbc;
    using System.Collections;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    using System.Linq;
    using System.Linq.Expressions;
    
    #region ApplicationDirectoryClient Extension Type
    /// <summary>
    /// The ApplicationDirectoryClient object class.
    /// </summary>
    public partial class ApplicationDirectoryClient
    {
        private Exception _exception = null;
		private ApplicationDirectoryClientThread _threadApplicationDirectoryClientContext = null;

		/// <summary>
        /// Gets the current async exception; else null;
        /// </summary>
        public Exception ExceptionApplicationDirectoryClient
        {
            get { return _exception; }
        }

		/// <summary>
        /// Gets the ApplicationDirectoryClient threading context.
        /// </summary>
        public ApplicationDirectoryClientThread ApplicationDirectoryClientThreadContext
        {
            get { return _threadApplicationDirectoryClientContext; }
        }

		/// <summary>
        /// On create.
        /// </summary>
        partial void OnCreated();

		/// <summary>
        /// On create instance of ApplicationDirectoryClient
        /// </summary>
		partial void OnCreated()
		{
			// Start the async control.
			_threadApplicationDirectoryClientContext = new ApplicationDirectoryClientThread(this);
			_threadApplicationDirectoryClientContext.AsyncError += new Threading.EventHandler<Exception>(_asyncAccount_AsyncError);
		}

		/// <summary>
        /// Async error
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e1"></param>
        private void _asyncAccount_AsyncError(object sender, Exception e1)
        {
            _exception = e1;
        }

		/// <summary>
        /// ApplicationDirectoryClient threading handler.
        /// </summary>
        public class ApplicationDirectoryClientThread : Nequeo.Threading.AsyncExecutionHandler<ApplicationDirectoryClient>
        {
            /// <summary>
            /// ApplicationDirectoryClient threading handler.
            /// </summary>
            /// <param name="service">The ApplicationDirectoryClient type.</param>
            public ApplicationDirectoryClientThread(ApplicationDirectoryClient service)
                : base(service) { }
        }
    }
    #endregion
}

#pragma warning restore 169
