//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CallMediaInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CallMediaInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CallMediaInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CallMediaInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_CallMediaInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint index {
    set {
      pjsua2PINVOKE.CallMediaInfo_index_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.CallMediaInfo_index_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_pjmedia_type type {
    set {
      pjsua2PINVOKE.CallMediaInfo_type_set(swigCPtr, SWIGTYPE_p_pjmedia_type.getCPtr(value));
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_pjmedia_type ret = new SWIGTYPE_p_pjmedia_type(pjsua2PINVOKE.CallMediaInfo_type_get(swigCPtr), true);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_pjmedia_dir dir {
    set {
      pjsua2PINVOKE.CallMediaInfo_dir_set(swigCPtr, SWIGTYPE_p_pjmedia_dir.getCPtr(value));
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_pjmedia_dir ret = new SWIGTYPE_p_pjmedia_dir(pjsua2PINVOKE.CallMediaInfo_dir_get(swigCPtr), true);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_pjsua_call_media_status status {
    set {
      pjsua2PINVOKE.CallMediaInfo_status_set(swigCPtr, SWIGTYPE_p_pjsua_call_media_status.getCPtr(value));
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_pjsua_call_media_status ret = new SWIGTYPE_p_pjsua_call_media_status(pjsua2PINVOKE.CallMediaInfo_status_get(swigCPtr), true);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int audioConfSlot {
    set {
      pjsua2PINVOKE.CallMediaInfo_audioConfSlot_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.CallMediaInfo_audioConfSlot_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_pjsua_vid_win_id videoIncomingWindowId {
    set {
      pjsua2PINVOKE.CallMediaInfo_videoIncomingWindowId_set(swigCPtr, SWIGTYPE_p_pjsua_vid_win_id.getCPtr(value));
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_pjsua_vid_win_id ret = new SWIGTYPE_p_pjsua_vid_win_id(pjsua2PINVOKE.CallMediaInfo_videoIncomingWindowId_get(swigCPtr), true);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_VideoWindow videoWindow {
    set {
      pjsua2PINVOKE.CallMediaInfo_videoWindow_set(swigCPtr, SWIGTYPE_p_VideoWindow.getCPtr(value));
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_VideoWindow ret = new SWIGTYPE_p_VideoWindow(pjsua2PINVOKE.CallMediaInfo_videoWindow_get(swigCPtr), true);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_pjmedia_vid_dev_index videoCapDev {
    set {
      pjsua2PINVOKE.CallMediaInfo_videoCapDev_set(swigCPtr, SWIGTYPE_p_pjmedia_vid_dev_index.getCPtr(value));
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_pjmedia_vid_dev_index ret = new SWIGTYPE_p_pjmedia_vid_dev_index(pjsua2PINVOKE.CallMediaInfo_videoCapDev_get(swigCPtr), true);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public CallMediaInfo() : this(pjsua2PINVOKE.new_CallMediaInfo(), true) {
  }

  public void fromPj(SWIGTYPE_p_pjsua_call_media_info prm) {
    pjsua2PINVOKE.CallMediaInfo_fromPj(swigCPtr, SWIGTYPE_p_pjsua_call_media_info.getCPtr(prm));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

}
