//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ContainerNode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ContainerNode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ContainerNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ContainerNode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_ContainerNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool hasUnread() {
    bool ret = pjsua2PINVOKE.ContainerNode_hasUnread(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_string unreadName() {
    SWIGTYPE_p_string ret = new SWIGTYPE_p_string(pjsua2PINVOKE.ContainerNode_unreadName(swigCPtr), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int readInt(SWIGTYPE_p_string name) {
    int ret = pjsua2PINVOKE.ContainerNode_readInt__SWIG_0(swigCPtr, SWIGTYPE_p_string.getCPtr(name));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int readInt() {
    int ret = pjsua2PINVOKE.ContainerNode_readInt__SWIG_1(swigCPtr);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float readNumber(SWIGTYPE_p_string name) {
    float ret = pjsua2PINVOKE.ContainerNode_readNumber__SWIG_0(swigCPtr, SWIGTYPE_p_string.getCPtr(name));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float readNumber() {
    float ret = pjsua2PINVOKE.ContainerNode_readNumber__SWIG_1(swigCPtr);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool readBool(SWIGTYPE_p_string name) {
    bool ret = pjsua2PINVOKE.ContainerNode_readBool__SWIG_0(swigCPtr, SWIGTYPE_p_string.getCPtr(name));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool readBool() {
    bool ret = pjsua2PINVOKE.ContainerNode_readBool__SWIG_1(swigCPtr);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_string readString(SWIGTYPE_p_string name) {
    SWIGTYPE_p_string ret = new SWIGTYPE_p_string(pjsua2PINVOKE.ContainerNode_readString__SWIG_0(swigCPtr, SWIGTYPE_p_string.getCPtr(name)), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_string readString() {
    SWIGTYPE_p_string ret = new SWIGTYPE_p_string(pjsua2PINVOKE.ContainerNode_readString__SWIG_1(swigCPtr), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_StringVector readStringVector(SWIGTYPE_p_string name) {
    SWIGTYPE_p_StringVector ret = new SWIGTYPE_p_StringVector(pjsua2PINVOKE.ContainerNode_readStringVector__SWIG_0(swigCPtr, SWIGTYPE_p_string.getCPtr(name)), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_StringVector readStringVector() {
    SWIGTYPE_p_StringVector ret = new SWIGTYPE_p_StringVector(pjsua2PINVOKE.ContainerNode_readStringVector__SWIG_1(swigCPtr), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void readObject(PersistentObject obj) {
    pjsua2PINVOKE.ContainerNode_readObject(swigCPtr, PersistentObject.getCPtr(obj));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public ContainerNode readContainer(SWIGTYPE_p_string name) {
    ContainerNode ret = new ContainerNode(pjsua2PINVOKE.ContainerNode_readContainer__SWIG_0(swigCPtr, SWIGTYPE_p_string.getCPtr(name)), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ContainerNode readContainer() {
    ContainerNode ret = new ContainerNode(pjsua2PINVOKE.ContainerNode_readContainer__SWIG_1(swigCPtr), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ContainerNode readArray(SWIGTYPE_p_string name) {
    ContainerNode ret = new ContainerNode(pjsua2PINVOKE.ContainerNode_readArray__SWIG_0(swigCPtr, SWIGTYPE_p_string.getCPtr(name)), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ContainerNode readArray() {
    ContainerNode ret = new ContainerNode(pjsua2PINVOKE.ContainerNode_readArray__SWIG_1(swigCPtr), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void writeNumber(SWIGTYPE_p_string name, float num) {
    pjsua2PINVOKE.ContainerNode_writeNumber(swigCPtr, SWIGTYPE_p_string.getCPtr(name), num);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void writeInt(SWIGTYPE_p_string name, int num) {
    pjsua2PINVOKE.ContainerNode_writeInt(swigCPtr, SWIGTYPE_p_string.getCPtr(name), num);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void writeBool(SWIGTYPE_p_string name, bool value) {
    pjsua2PINVOKE.ContainerNode_writeBool(swigCPtr, SWIGTYPE_p_string.getCPtr(name), value);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void writeString(SWIGTYPE_p_string name, SWIGTYPE_p_string value) {
    pjsua2PINVOKE.ContainerNode_writeString(swigCPtr, SWIGTYPE_p_string.getCPtr(name), SWIGTYPE_p_string.getCPtr(value));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void writeStringVector(SWIGTYPE_p_string name, SWIGTYPE_p_StringVector arr) {
    pjsua2PINVOKE.ContainerNode_writeStringVector(swigCPtr, SWIGTYPE_p_string.getCPtr(name), SWIGTYPE_p_StringVector.getCPtr(arr));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void writeObject(PersistentObject obj) {
    pjsua2PINVOKE.ContainerNode_writeObject(swigCPtr, PersistentObject.getCPtr(obj));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public ContainerNode writeNewContainer(SWIGTYPE_p_string name) {
    ContainerNode ret = new ContainerNode(pjsua2PINVOKE.ContainerNode_writeNewContainer(swigCPtr, SWIGTYPE_p_string.getCPtr(name)), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ContainerNode writeNewArray(SWIGTYPE_p_string name) {
    ContainerNode ret = new ContainerNode(pjsua2PINVOKE.ContainerNode_writeNewArray(swigCPtr, SWIGTYPE_p_string.getCPtr(name)), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public container_node_op op {
    set {
      pjsua2PINVOKE.ContainerNode_op_set(swigCPtr, container_node_op.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.ContainerNode_op_get(swigCPtr);
      container_node_op ret = (cPtr == global::System.IntPtr.Zero) ? null : new container_node_op(cPtr, false);
      return ret;
    } 
  }

  public container_node_internal_data data {
    set {
      pjsua2PINVOKE.ContainerNode_data_set(swigCPtr, container_node_internal_data.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.ContainerNode_data_get(swigCPtr);
      container_node_internal_data ret = (cPtr == global::System.IntPtr.Zero) ? null : new container_node_internal_data(cPtr, false);
      return ret;
    } 
  }

  public ContainerNode() : this(pjsua2PINVOKE.new_ContainerNode(), true) {
  }

}
