//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class UaConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UaConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UaConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UaConfig() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_UaConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint maxCalls {
    set {
      pjsua2PINVOKE.UaConfig_maxCalls_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.UaConfig_maxCalls_get(swigCPtr);
      return ret;
    } 
  }

  public uint threadCnt {
    set {
      pjsua2PINVOKE.UaConfig_threadCnt_set(swigCPtr, value);
    } 
    get {
      uint ret = pjsua2PINVOKE.UaConfig_threadCnt_get(swigCPtr);
      return ret;
    } 
  }

  public bool mainThreadOnly {
    set {
      pjsua2PINVOKE.UaConfig_mainThreadOnly_set(swigCPtr, value);
    } 
    get {
      bool ret = pjsua2PINVOKE.UaConfig_mainThreadOnly_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_StringVector nameserver {
    set {
      pjsua2PINVOKE.UaConfig_nameserver_set(swigCPtr, SWIGTYPE_p_StringVector.getCPtr(value));
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_StringVector ret = new SWIGTYPE_p_StringVector(pjsua2PINVOKE.UaConfig_nameserver_get(swigCPtr), true);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_string userAgent {
    set {
      pjsua2PINVOKE.UaConfig_userAgent_set(swigCPtr, SWIGTYPE_p_string.getCPtr(value));
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_string ret = new SWIGTYPE_p_string(pjsua2PINVOKE.UaConfig_userAgent_get(swigCPtr), true);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_StringVector stunServer {
    set {
      pjsua2PINVOKE.UaConfig_stunServer_set(swigCPtr, SWIGTYPE_p_StringVector.getCPtr(value));
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_StringVector ret = new SWIGTYPE_p_StringVector(pjsua2PINVOKE.UaConfig_stunServer_get(swigCPtr), true);
      if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool stunIgnoreFailure {
    set {
      pjsua2PINVOKE.UaConfig_stunIgnoreFailure_set(swigCPtr, value);
    } 
    get {
      bool ret = pjsua2PINVOKE.UaConfig_stunIgnoreFailure_get(swigCPtr);
      return ret;
    } 
  }

  public int natTypeInSdp {
    set {
      pjsua2PINVOKE.UaConfig_natTypeInSdp_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.UaConfig_natTypeInSdp_get(swigCPtr);
      return ret;
    } 
  }

  public bool mwiUnsolicitedEnabled {
    set {
      pjsua2PINVOKE.UaConfig_mwiUnsolicitedEnabled_set(swigCPtr, value);
    } 
    get {
      bool ret = pjsua2PINVOKE.UaConfig_mwiUnsolicitedEnabled_get(swigCPtr);
      return ret;
    } 
  }

  public UaConfig() : this(pjsua2PINVOKE.new_UaConfig(), true) {
  }

  public void fromPj(SWIGTYPE_p_pjsua_config ua_cfg) {
    pjsua2PINVOKE.UaConfig_fromPj(swigCPtr, SWIGTYPE_p_pjsua_config.getCPtr(ua_cfg));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_pjsua_config toPj() {
    SWIGTYPE_p_pjsua_config ret = new SWIGTYPE_p_pjsua_config(pjsua2PINVOKE.UaConfig_toPj(swigCPtr), true);
    return ret;
  }

  public virtual void readObject(SWIGTYPE_p_ContainerNode node) {
    pjsua2PINVOKE.UaConfig_readObject(swigCPtr, SWIGTYPE_p_ContainerNode.getCPtr(node));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void writeObject(SWIGTYPE_p_ContainerNode node) {
    pjsua2PINVOKE.UaConfig_writeObject(swigCPtr, SWIGTYPE_p_ContainerNode.getCPtr(node));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

}
