//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TimeZone {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeZone() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nequeo.Resource.TimeZone", typeof(TimeZone).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabian Standard Time.
        /// </summary>
        public static string AbuDhabi {
            get {
                return ResourceManager.GetString("AbuDhabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cen. Australia Standard Time.
        /// </summary>
        public static string Adelaide {
            get {
                return ResourceManager.GetString("Adelaide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. Central Asia Standard Time.
        /// </summary>
        public static string Almaty {
            get {
                return ResourceManager.GetString("Almaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordan Standard Time.
        /// </summary>
        public static string Amman {
            get {
                return ResourceManager.GetString("Amman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W. Europe Standard Time.
        /// </summary>
        public static string Amsterdam {
            get {
                return ResourceManager.GetString("Amsterdam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alaskan Standard Time.
        /// </summary>
        public static string Anchorage {
            get {
                return ResourceManager.GetString("Anchorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa Standard Time.
        /// </summary>
        public static string Apia {
            get {
                return ResourceManager.GetString("Apia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Asia Standard Time.
        /// </summary>
        public static string Astana {
            get {
                return ResourceManager.GetString("Astana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTB Standard Time.
        /// </summary>
        public static string Athens {
            get {
                return ResourceManager.GetString("Athens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand Standard Time.
        /// </summary>
        public static string Auckland {
            get {
                return ResourceManager.GetString("Auckland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azores Standard Time.
        /// </summary>
        public static string Azores {
            get {
                return ResourceManager.GetString("Azores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Standard Time.
        /// </summary>
        public static string Baghdad {
            get {
                return ResourceManager.GetString("Baghdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific Standard Time.
        /// </summary>
        public static string BajaCalifornia {
            get {
                return ResourceManager.GetString("BajaCalifornia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan Standard Time.
        /// </summary>
        public static string Baku {
            get {
                return ResourceManager.GetString("Baku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE Asia Standard Time.
        /// </summary>
        public static string Bangkok {
            get {
                return ResourceManager.GetString("Bangkok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Standard Time.
        /// </summary>
        public static string Beijing {
            get {
                return ResourceManager.GetString("Beijing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle East Standard Time.
        /// </summary>
        public static string Beirut {
            get {
                return ResourceManager.GetString("Beirut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Europe Standard Time.
        /// </summary>
        public static string Belgrade {
            get {
                return ResourceManager.GetString("Belgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W. Europe Standard Time.
        /// </summary>
        public static string Berlin {
            get {
                return ResourceManager.GetString("Berlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W. Europe Standard Time.
        /// </summary>
        public static string Bern {
            get {
                return ResourceManager.GetString("Bern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA Eastern Standard Time.
        /// </summary>
        public static string Bogota {
            get {
                return ResourceManager.GetString("Bogota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Europe Standard Time.
        /// </summary>
        public static string Bratislava {
            get {
                return ResourceManager.GetString("Bratislava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. Australia Standard Time.
        /// </summary>
        public static string Brisbane {
            get {
                return ResourceManager.GetString("Brisbane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance Standard Time.
        /// </summary>
        public static string Brussels {
            get {
                return ResourceManager.GetString("Brussels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTB Standard Time.
        /// </summary>
        public static string Bucharest {
            get {
                return ResourceManager.GetString("Bucharest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Europe Standard Time.
        /// </summary>
        public static string Budapest {
            get {
                return ResourceManager.GetString("Budapest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina Standard Time.
        /// </summary>
        public static string BuenosAires {
            get {
                return ResourceManager.GetString("BuenosAires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt Standard Time.
        /// </summary>
        public static string Cairo {
            get {
                return ResourceManager.GetString("Cairo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India Standard Time.
        /// </summary>
        public static string Calcutta {
            get {
                return ResourceManager.GetString("Calcutta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus Eastern Standard Time.
        /// </summary>
        public static string Canberra {
            get {
                return ResourceManager.GetString("Canberra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cape Verde Standard Time.
        /// </summary>
        public static string CapeVerde {
            get {
                return ResourceManager.GetString("CapeVerde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela Standard Time.
        /// </summary>
        public static string Caracas {
            get {
                return ResourceManager.GetString("Caracas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland Standard Time.
        /// </summary>
        public static string Casablanca {
            get {
                return ResourceManager.GetString("Casablanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India Standard Time.
        /// </summary>
        public static string Chennai {
            get {
                return ResourceManager.GetString("Chennai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Standard Time.
        /// </summary>
        public static string Chicago {
            get {
                return ResourceManager.GetString("Chicago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico Standard Time 2.
        /// </summary>
        public static string Chihuahua {
            get {
                return ResourceManager.GetString("Chihuahua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Standard Time.
        /// </summary>
        public static string Chongqing {
            get {
                return ResourceManager.GetString("Chongqing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka Standard Time.
        /// </summary>
        public static string Colombo {
            get {
                return ResourceManager.GetString("Colombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance Standard Time.
        /// </summary>
        public static string Copenhagen {
            get {
                return ResourceManager.GetString("Copenhagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUS Central Standard Time.
        /// </summary>
        public static string Darwin {
            get {
                return ResourceManager.GetString("Darwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Standard Time.
        /// </summary>
        public static string Denver {
            get {
                return ResourceManager.GetString("Denver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Asia Standard Time.
        /// </summary>
        public static string Dhaka {
            get {
                return ResourceManager.GetString("Dhaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabian Standard Time.
        /// </summary>
        public static string Dubai {
            get {
                return ResourceManager.GetString("Dubai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMT Standard Time.
        /// </summary>
        public static string Dublin {
            get {
                return ResourceManager.GetString("Dublin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMT Standard Time.
        /// </summary>
        public static string Edinburgh {
            get {
                return ResourceManager.GetString("Edinburgh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji Standard Time.
        /// </summary>
        public static string Fiji {
            get {
                return ResourceManager.GetString("Fiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA Eastern Standard Time.
        /// </summary>
        public static string Georgetown {
            get {
                return ResourceManager.GetString("Georgetown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland Standard Time.
        /// </summary>
        public static string Godthab {
            get {
                return ResourceManager.GetString("Godthab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico Standard Time.
        /// </summary>
        public static string Guadalajara {
            get {
                return ResourceManager.GetString("Guadalajara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Pacific Standard Time.
        /// </summary>
        public static string Guadalcanal {
            get {
                return ResourceManager.GetString("Guadalcanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central America Standard Time.
        /// </summary>
        public static string Guatemala {
            get {
                return ResourceManager.GetString("Guatemala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantic Standard Time.
        /// </summary>
        public static string Halifax {
            get {
                return ResourceManager.GetString("Halifax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE Asia Standard Time.
        /// </summary>
        public static string Hanoi {
            get {
                return ResourceManager.GetString("Hanoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa Standard Time.
        /// </summary>
        public static string Harare {
            get {
                return ResourceManager.GetString("Harare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLE Standard Time.
        /// </summary>
        public static string Helsinki {
            get {
                return ResourceManager.GetString("Helsinki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasmania Standard Time.
        /// </summary>
        public static string Hobart {
            get {
                return ResourceManager.GetString("Hobart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Standard Time.
        /// </summary>
        public static string HongKong {
            get {
                return ResourceManager.GetString("HongKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawaiian Standard Time.
        /// </summary>
        public static string Honolulu {
            get {
                return ResourceManager.GetString("Honolulu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Eastern Standard Time.
        /// </summary>
        public static string Indiana {
            get {
                return ResourceManager.GetString("Indiana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Asia East Standard Time.
        /// </summary>
        public static string Irkutsk {
            get {
                return ResourceManager.GetString("Irkutsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Asia Standard Time.
        /// </summary>
        public static string Islamabad {
            get {
                return ResourceManager.GetString("Islamabad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTB Standard Time.
        /// </summary>
        public static string Istanbul {
            get {
                return ResourceManager.GetString("Istanbul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE Asia Standard Time.
        /// </summary>
        public static string Jakarta {
            get {
                return ResourceManager.GetString("Jakarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel Standard Time.
        /// </summary>
        public static string Jerusalem {
            get {
                return ResourceManager.GetString("Jerusalem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa Standard Time.
        /// </summary>
        public static string Johannesburg {
            get {
                return ResourceManager.GetString("Johannesburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan Standard Time.
        /// </summary>
        public static string Kabul {
            get {
                return ResourceManager.GetString("Kabul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji Standard Time.
        /// </summary>
        public static string Kamchatka {
            get {
                return ResourceManager.GetString("Kamchatka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Asia Standard Time.
        /// </summary>
        public static string Karachi {
            get {
                return ResourceManager.GetString("Karachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepal Standard Time.
        /// </summary>
        public static string Katmandu {
            get {
                return ResourceManager.GetString("Katmandu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLE Standard Time.
        /// </summary>
        public static string Kiev {
            get {
                return ResourceManager.GetString("Kiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India Standard Time.
        /// </summary>
        public static string Kolkata {
            get {
                return ResourceManager.GetString("Kolkata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Asia Standard Time.
        /// </summary>
        public static string Krasnoyarsk {
            get {
                return ResourceManager.GetString("Krasnoyarsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore Standard Time.
        /// </summary>
        public static string KualaLumpur {
            get {
                return ResourceManager.GetString("KualaLumpur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Standard Time.
        /// </summary>
        public static string Kuwai {
            get {
                return ResourceManager.GetString("Kuwai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W. Central Africa Standard Time.
        /// </summary>
        public static string Lagos {
            get {
                return ResourceManager.GetString("Lagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico Standard Time 2.
        /// </summary>
        public static string LaPaz {
            get {
                return ResourceManager.GetString("LaPaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA Eastern Standard Time.
        /// </summary>
        public static string Lima {
            get {
                return ResourceManager.GetString("Lima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMT Standard Time.
        /// </summary>
        public static string Lisbon {
            get {
                return ResourceManager.GetString("Lisbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Europe Standard Time.
        /// </summary>
        public static string Ljubljana {
            get {
                return ResourceManager.GetString("Ljubljana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMT Standard Time.
        /// </summary>
        public static string London {
            get {
                return ResourceManager.GetString("London", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific Standard Time.
        /// </summary>
        public static string LosAngeles {
            get {
                return ResourceManager.GetString("LosAngeles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance Standard Time.
        /// </summary>
        public static string Madrid {
            get {
                return ResourceManager.GetString("Madrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Pacific Standard Time.
        /// </summary>
        public static string Magadan {
            get {
                return ResourceManager.GetString("Magadan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Brazilian Standard Time.
        /// </summary>
        public static string Manaus {
            get {
                return ResourceManager.GetString("Manaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji Standard Time.
        /// </summary>
        public static string MarshallIs {
            get {
                return ResourceManager.GetString("MarshallIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico Standard Time 2.
        /// </summary>
        public static string Mazatlan {
            get {
                return ResourceManager.GetString("Mazatlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus Eastern Standard Time.
        /// </summary>
        public static string Melbourne {
            get {
                return ResourceManager.GetString("Melbourne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico Standard Time.
        /// </summary>
        public static string MexicoCity {
            get {
                return ResourceManager.GetString("MexicoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. Europe Standard Time.
        /// </summary>
        public static string Minsk {
            get {
                return ResourceManager.GetString("Minsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland Standard Time.
        /// </summary>
        public static string Monrovia {
            get {
                return ResourceManager.GetString("Monrovia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico Standard Time.
        /// </summary>
        public static string Monterrey {
            get {
                return ResourceManager.GetString("Monterrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montevideo Standard Time.
        /// </summary>
        public static string Montevideo {
            get {
                return ResourceManager.GetString("Montevideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Standard Time.
        /// </summary>
        public static string Moscow {
            get {
                return ResourceManager.GetString("Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India Standard Time.
        /// </summary>
        public static string Mumbai {
            get {
                return ResourceManager.GetString("Mumbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabian Standard Time.
        /// </summary>
        public static string Muscat {
            get {
                return ResourceManager.GetString("Muscat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. Africa Standard Time.
        /// </summary>
        public static string Nairobi {
            get {
                return ResourceManager.GetString("Nairobi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Pacific Standard Time.
        /// </summary>
        public static string NewCaledonia {
            get {
                return ResourceManager.GetString("NewCaledonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India Standard Time.
        /// </summary>
        public static string NewDelhi {
            get {
                return ResourceManager.GetString("NewDelhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Standard Time.
        /// </summary>
        public static string NewYork {
            get {
                return ResourceManager.GetString("NewYork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. Central Asia Standard Time.
        /// </summary>
        public static string Novosibirsk {
            get {
                return ResourceManager.GetString("Novosibirsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokyo Standard Time.
        /// </summary>
        public static string Osaka {
            get {
                return ResourceManager.GetString("Osaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance Standard Time.
        /// </summary>
        public static string Paris {
            get {
                return ResourceManager.GetString("Paris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W. Australia Standard Time.
        /// </summary>
        public static string Perth {
            get {
                return ResourceManager.GetString("Perth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Mountain Standard Time.
        /// </summary>
        public static string Phoenix {
            get {
                return ResourceManager.GetString("Phoenix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Pacific Standard Time.
        /// </summary>
        public static string PortMoresby {
            get {
                return ResourceManager.GetString("PortMoresby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Europe Standard Time.
        /// </summary>
        public static string Prague {
            get {
                return ResourceManager.GetString("Prague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa Standard Time.
        /// </summary>
        public static string Pretoria {
            get {
                return ResourceManager.GetString("Pretoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA Eastern Standard Time.
        /// </summary>
        public static string Quito {
            get {
                return ResourceManager.GetString("Quito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar Standard Time.
        /// </summary>
        public static string Rangoon {
            get {
                return ResourceManager.GetString("Rangoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada Central Standard Time.
        /// </summary>
        public static string Regina {
            get {
                return ResourceManager.GetString("Regina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland Standard Time.
        /// </summary>
        public static string Reykjavik {
            get {
                return ResourceManager.GetString("Reykjavik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLE Standard Time.
        /// </summary>
        public static string Riga {
            get {
                return ResourceManager.GetString("Riga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA Eastern Standard Time.
        /// </summary>
        public static string RioBranco {
            get {
                return ResourceManager.GetString("RioBranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Standard Time.
        /// </summary>
        public static string Riyadh {
            get {
                return ResourceManager.GetString("Riyadh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W. Europe Standard Time.
        /// </summary>
        public static string Rome {
            get {
                return ResourceManager.GetString("Rome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa Standard Time.
        /// </summary>
        public static string Samoa {
            get {
                return ResourceManager.GetString("Samoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific SA Standard Time.
        /// </summary>
        public static string Santiago {
            get {
                return ResourceManager.GetString("Santiago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. South America Standard Time.
        /// </summary>
        public static string SaoPaulo {
            get {
                return ResourceManager.GetString("SaoPaulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokyo Standard Time.
        /// </summary>
        public static string Sapporo {
            get {
                return ResourceManager.GetString("Sapporo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European Standard Time.
        /// </summary>
        public static string Sarajevo {
            get {
                return ResourceManager.GetString("Sarajevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea Standard Time.
        /// </summary>
        public static string Seoul {
            get {
                return ResourceManager.GetString("Seoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Standard Time.
        /// </summary>
        public static string Shanghai {
            get {
                return ResourceManager.GetString("Shanghai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore Standard Time.
        /// </summary>
        public static string Singapore {
            get {
                return ResourceManager.GetString("Singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European Standard Time.
        /// </summary>
        public static string Skopje {
            get {
                return ResourceManager.GetString("Skopje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLE Standard Time.
        /// </summary>
        public static string Sofia {
            get {
                return ResourceManager.GetString("Sofia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Pacific Standard Time.
        /// </summary>
        public static string SolomonIs {
            get {
                return ResourceManager.GetString("SolomonIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid-Atlantic Standard Time.
        /// </summary>
        public static string SouthGeorgia {
            get {
                return ResourceManager.GetString("SouthGeorgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka Standard Time.
        /// </summary>
        public static string SriJayawardenepura {
            get {
                return ResourceManager.GetString("SriJayawardenepura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newfoundland Standard Time.
        /// </summary>
        public static string StJohns {
            get {
                return ResourceManager.GetString("StJohns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W. Europe Standard Time.
        /// </summary>
        public static string Stockholm {
            get {
                return ResourceManager.GetString("Stockholm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Standard Time.
        /// </summary>
        public static string StPetersburg {
            get {
                return ResourceManager.GetString("StPetersburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus Eastern Standard Time.
        /// </summary>
        public static string Sydney {
            get {
                return ResourceManager.GetString("Sydney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipei Standard Time.
        /// </summary>
        public static string Taipei {
            get {
                return ResourceManager.GetString("Taipei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLE Standard Time.
        /// </summary>
        public static string Tallinn {
            get {
                return ResourceManager.GetString("Tallinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Asia Standard Time.
        /// </summary>
        public static string Tashkent {
            get {
                return ResourceManager.GetString("Tashkent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caucasus Standard Time.
        /// </summary>
        public static string Tbilisi {
            get {
                return ResourceManager.GetString("Tbilisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran Standard Time.
        /// </summary>
        public static string Tehran {
            get {
                return ResourceManager.GetString("Tehran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific Standard Time.
        /// </summary>
        public static string Tijuana {
            get {
                return ResourceManager.GetString("Tijuana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokyo Standard Time.
        /// </summary>
        public static string Tokyo {
            get {
                return ResourceManager.GetString("Tokyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonga Standard Time.
        /// </summary>
        public static string Tongatapu {
            get {
                return ResourceManager.GetString("Tongatapu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Asia East Standard Time.
        /// </summary>
        public static string UlaanBataar {
            get {
                return ResourceManager.GetString("UlaanBataar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Standard Time.
        /// </summary>
        public static string Urumqi {
            get {
                return ResourceManager.GetString("Urumqi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W. Europe Standard Time.
        /// </summary>
        public static string Vienna {
            get {
                return ResourceManager.GetString("Vienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLE Standard Time.
        /// </summary>
        public static string Vilnius {
            get {
                return ResourceManager.GetString("Vilnius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vladivostok Standard Time.
        /// </summary>
        public static string Vladivostok {
            get {
                return ResourceManager.GetString("Vladivostok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Standard Time.
        /// </summary>
        public static string Volgograd {
            get {
                return ResourceManager.GetString("Volgograd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European Standard Time.
        /// </summary>
        public static string Warsaw {
            get {
                return ResourceManager.GetString("Warsaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand Standard Time.
        /// </summary>
        public static string Wellington {
            get {
                return ResourceManager.GetString("Wellington", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibia Standard Time.
        /// </summary>
        public static string Windhoek {
            get {
                return ResourceManager.GetString("Windhoek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakutsk Standard Time.
        /// </summary>
        public static string Yakutsk {
            get {
                return ResourceManager.GetString("Yakutsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekaterinburg Standard Time.
        /// </summary>
        public static string Yekaterinburg {
            get {
                return ResourceManager.GetString("Yekaterinburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenian Standard Time.
        /// </summary>
        public static string Yerevan {
            get {
                return ResourceManager.GetString("Yerevan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European Standard Time.
        /// </summary>
        public static string Zagreb {
            get {
                return ResourceManager.GetString("Zagreb", resourceCulture);
            }
        }
    }
}
