//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nequeo.DataAccess.NequeoCompany.Edm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string OrderID { get; set; }
        public string Developer { get; set; }
        public string GSTIncluded { get; set; }
        public string Comments { get; set; }
        public string IncomeType { get; set; }
    }
}
